import {useEffect,useMemo,useRef,useState} from 'react';
import {useJson} from './shared.jsx';
import {nflTeam} from './playerWorkspace.js';
import {newsArticleLeagueContext,newsLeagueDeskContext} from './fantasyNewsContext.js';
import {publicIdentityKey} from './playerIdentity.js';
import {usePublicNews} from './usePublicNews.js';
import {HOURS,NEWS_PANES,defaultNewsLayout,list,players,articleTime,clock,matchesGlobal,wireOrder,encodeNewsFilters,decodeNewsFilters} from './newsCommandModel.js';
import {Grip,WindowFrame,routeOptions,useNewsLayout,useNewsWindows} from './newsWindows.jsx';
import {StatusTable,Wire,Evidence,RoleBoard,FeedHealth,Empty} from './newsCommandViews.jsx';
import {LeagueDesk} from './newsLeagueDesk.jsx';
import './FantasyNews.css';
export {NEWS_LAYOUT_KEY,NEWS_PANES,validateNewsLayout,safeNewsUrl} from './newsCommandModel.js';
export {newsRosterMatches} from './fantasyNewsContext.js';
export {closeFantasyNewsWindows} from './newsWindows.jsx';
const cleanFilters=()=>({search:'',teams:[],pos:[],leagues:[],status:[]});
const NAV=[['players','Player Database'],['waivers','Waivers'],['market-pulse','Market Pulse'],['team-box-scores','Team Box Scores'],['opportunity-tracker','Opportunity Tracker'],['league-hub','League Hub'],['fantasy-news','Fantasy News'],['yahoo','Yahoo Connection']];
export function FantasyNews({season=2026,scoring='ppr',onOpen,yahoo}){
 const [route]=useState(routeOptions),[hours,setHours]=useState(route.hours),[refresh,setRefresh]=useState(0),[autoRead,setAutoRead]=useState(true),[now,setNow]=useState(Date.now);
 const [layout,setLayout,storageError]=useNewsLayout(route.popout),[filters,setFilters]=useState(cleanFilters),[popover,setPopover]=useState(null),popoverRef=useRef(null);
 const [source,setSource]=useState('all'),[dfsWeek,setDfsWeek]=useState(4),[gameIds,setGameIds]=useState([]),[expanded,setExpanded]=useState(new Set());
 const [wireSettings,setWireSettings]=useState({chip:'all',group:'day',sort:'published'});
 const [selectedId,setSelectedId]=useState(route.article),[history,setHistory]=useState([]),[pinned,setPinned]=useState(false);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 const feed=usePublicNews(hours,refresh,autoRead),scheduleState=useJson(`/api/v1/schedule?season=${season}&week=${dfsWeek}`),schedule=list(scheduleState.data?.data);
 const articles=useMemo(()=>list(feed.data?.articles).map(a=>Number.isFinite(Date.parse(a.publishedAt))&&now-Date.parse(a.publishedAt)>6*3600000?{...a,freshness:{...a.freshness,state:'stale'}}:a).sort((a,b)=>articleTime(b)-articleTime(a)),[feed.data,now]);
 const authorizationNow=Math.max(now,Date.now());
 const contextMap=useMemo(()=>new Map(articles.map(a=>[a.id,newsArticleLeagueContext(a,yahoo,season,{now:authorizationNow})])),[articles,yahoo,season,authorizationNow]);
 const context=a=>contextMap.get(a?.id)||newsArticleLeagueContext(a,yahoo,season,{now:authorizationNow});
 const connected=context({players:[]}).connected;
 const meta=useMemo(()=>{const m=feed.data?.meta,basis=m?.freshness?.basis==='source_check'?m.freshness.sourceCheckedAt:m?.freshness?.latestSourcePublishedAt,age=now-Date.parse(basis);return m?.state==='current'&&Number.isFinite(age)&&age>(m.freshness?.staleAfterHours||6)*3600000?{...m,state:'stale',message:'Snapshot freshness expired; verify original sources.'}:m;},[feed.data,now]);
 useEffect(()=>{if(!selectedId&&articles[0])setSelectedId(articles[0].id);},[articles,selectedId]);
 const filtered=articles.filter(a=>matchesGlobal(a,filters,context(a)));
 const selected=articles.find(a=>a.id===selectedId)||(!selectedId?filtered[0]:null)||null;
 const patch=value=>setLayout(old=>({...old,...value}));
 const select=id=>{if(!articles.some(a=>a.id===id))return;if(selected?.id&&id!==selected.id)setHistory(h=>[...h,selected.id].slice(-30));setSelectedId(id);};
 const inspect=id=>{if(pinned)return;select(id);setLayout(old=>({...old,show:{...old.show,evidence:true},maximized:old.maximized&&old.maximized!=='evidence'?null:old.maximized}));};
 const scope=newsLeagueDeskContext(yahoo,season,{now:authorizationNow}),leagueKeys=scope.leagues.map(l=>l.key);
 const acceptFilters=value=>{const next=decodeNewsFilters(value,leagueKeys);if(next)setFilters(old=>JSON.stringify(old)===JSON.stringify(next)?old:next);return Boolean(next);};
 const windows=useNewsWindows({route,articleId:selected?.id||'',hours,setHours,externalSelect:inspect,account:yahoo?.account,connected,filterScopeKey:leagueKeys.join('|'),filterMessage:encodeNewsFilters(filters,leagueKeys),acceptFilters});
 const previousAccount=useRef(yahoo?.account);useEffect(()=>{if((previousAccount.current&&previousAccount.current!==yahoo?.account)||!connected){setFilters(f=>f.leagues.length?{...f,leagues:[]}:f);}previousAccount.current=yahoo?.account;},[yahoo?.account,connected]);
 useEffect(()=>{if(!popover)return;const close=e=>{if(!popoverRef.current?.contains(e.target))setPopover(null);};const key=e=>{if(e.key==='Escape')setPopover(null);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);};},[popover]);
 const options={teams:[...new Set(articles.flatMap(a=>players(a).map(p=>nflTeam(p.team))).filter(Boolean))].sort().map(v=>[v,v]),pos:['QB','RB','WR','TE','K','DEF'].map(v=>[v,v]),leagues:[['mine','My roster'],['available','Available at read'],...scope.leagues.flatMap(l=>[[`mine:${l.key}`,`Mine · ${l.name}`],[`free:${l.key}`,`Free agents · ${l.name}`]])],status:['OUT','QUES','DBT','IR','PUP','CLR'].map(v=>[v,v])};
 const changeFilter=(key,value)=>setFilters(old=>({...old,[key]:old[key].includes(value)?old[key].filter(v=>v!==value):key==='leagues'?[value]:[...old[key],value]}));
 const filterTeam=team=>setFilters(f=>({...f,teams:[nflTeam(team)]}));
 const bodyProps={onOpen,season,scoring,filterTeam};
 const effectiveSource=source==='all'||articles.some(a=>list(a.sources).some(s=>(s.sourceName||s.name)===source))?source:'all';
 const content=id=>id==='status'?<StatusTable articles={filtered} allCount={articles.length} context={context} layout={layout} patch={patch} expanded={expanded} toggle={id=>setExpanded(old=>{const n=new Set(old);n.has(id)?n.delete(id):n.add(id);return n;})} inspect={inspect} source={effectiveSource} setSource={setSource} schedule={schedule} dfsWeek={dfsWeek} setDfsWeek={setDfsWeek} gameIds={gameIds} setGameIds={setGameIds} scheduleState={scheduleState} bodyProps={bodyProps}/>:id==='wire'?<Wire settings={wireSettings} setSettings={setWireSettings} articles={filtered} context={context} inspect={inspect} bodyProps={bodyProps}/>:id==='evidence'?<Evidence article={selected} articles={wireOrder(filtered,wireSettings)} context={context} select={select} back={()=>{const id=history.at(-1);setHistory(h=>h.slice(0,-1));setSelectedId(id);}} history={history} pinned={pinned} setPinned={setPinned} bodyProps={bodyProps}/>:id==='role'?<RoleBoard articles={filtered} inspect={inspect} context={context}/>:id==='health'?<FeedHealth meta={meta} articles={filtered} readAt={feed.readAt} context={context} chooseSource={name=>{setSource(name);patch({tab:'all',leftVisible:true,leftOpen:true});}}/>:<LeagueDesk key={`${connected}-${scope.teams.map(t=>t.key).join('|')}`} yahoo={yahoo} season={season} now={authorizationNow} articles={filtered} inspect={inspect} matchPlayer={p=>{const matched=articles.filter(a=>players(a).some(q=>publicIdentityKey(p)&&publicIdentityKey(p)===publicIdentityKey(q)));return matched.length?matched.some(a=>matchesGlobal(a,filters,context(a))):matchesGlobal({players:[p],headline:p.name},filters,context({players:[p]}));}}/>;
 const move=(id,dir)=>setLayout(old=>{const order=[...old.order],i=order.indexOf(id),j=i+dir;if(j<0||j>=order.length)return old;[order[i],order[j]]=[order[j],order[i]];return {...old,order};});
 const frame=id=><WindowFrame key={id} id={id} layout={layout} patch={patch} windows={windows} popout={route.popout} onMove={move} subtitle={id==='status'?`docked · ${filtered.length} reports`:id==='wire'?`${filtered.length} reports · ${hours}h`:id==='evidence'?'independent · ↗ from any window loads here':id==='role'?'vacated → next up':id==='health'?'public feed · source-linked':`${scope.leagues.length} authorized leagues`} controls={id==='status'?<button className="cc-filters-button" aria-expanded={layout.filtersOpen} onClick={()=>patch({filtersOpen:!layout.filtersOpen})}>Filters ▾</button>:null}>{content(id)}</WindowFrame>;
 const visible=layout.order.filter(id=>layout.show[id]&&(!layout.maximized||layout.maximized===id));const cols=layout.maximized?1:layout.arrange==='tiles'?Math.min(2,visible.length):layout.arrange==='columns'?visible.length:1;const rows=Math.ceil(visible.length/(cols||1));const fractions=(values,n)=>Array.from({length:n},(_,i)=>`minmax(0,${values[i]||1}fr)`).join(' 10px ');
 const enabled=id=>id==='status'?layout.leftVisible:id==='league'?layout.pfOpen:layout.show[id];
 const toggleWindow=id=>{if(enabled(id)){windows.dock(id);patch(id==='status'?{leftVisible:false}:id==='league'?{pfOpen:false}:{show:{...layout.show,[id]:false},maximized:layout.maximized===id?null:layout.maximized});}else patch(id==='status'?{leftVisible:true,leftOpen:true}:id==='league'?{pfOpen:true}:{show:{...layout.show,[id]:true}});};
 return <main className={`news-cc ${route.popout?'cc-popout':''}`} style={{'--p':layout.pageScale,'--d':layout.density}}>
 <header className="cc-appbar"><a className="cc-brand" href="#/players"><span>B</span><b>Bowser</b></a><strong className="cc-app-label">/ Fantasy News</strong><div className="cc-segments cc-hours">{HOURS.map(h=><button key={h} className={hours===h?'active':''} onClick={()=>setHours(h)}>{h===720?'30d':`${h}h`}</button>)}</div><input className="cc-search" aria-label="Search news" placeholder="⌕  Search player, headline, team…" value={filters.search} onChange={e=>setFilters(f=>({...f,search:e.target.value}))}/>
 <div ref={popoverRef} className="cc-global-filters"><div className="cc-segments">{[['teams','Teams'],['pos','Pos'],['leagues','Leagues'],['status','Status']].map(([k,label])=><button key={k} aria-expanded={popover===k} aria-controls="cc-filter-popover" disabled={k==='leagues'&&!connected} className={filters[k].length?'chosen':''} onClick={()=>setPopover(popover===k?null:k)}>{label}{filters[k].length?` ${filters[k].length}`:''} ▾</button>)}{Object.entries(filters).some(([k,v])=>k!=='search'&&v.length>0)&&<button className="cc-clear-global" aria-label="Clear global filters" onClick={()=>setFilters(cleanFilters())}>×</button>}</div>{popover&&<div id="cc-filter-popover" className="cc-filter-popover" role="group" aria-label={`${popover} filters`}><b>{popover} · applies to every window</b><div>{options[popover].map(([id,label])=><label className={filters[popover].includes(id)?'selected':''} key={id}><input type="checkbox" checked={filters[popover].includes(id)} onChange={()=>changeFilter(popover,id)}/>{label} <span className="cc-mono">{articles.filter(a=>matchesGlobal(a,{...filters,[popover]:[id]},context(a))).length}</span></label>)}</div><button onClick={()=>setFilters(f=>({...f,[popover]:[]}))}>Clear {popover}</button><button onClick={()=>setFilters(cleanFilters())}>Clear all filters</button><button onClick={()=>setPopover(null)}>Done</button></div>}</div>
 <div className="cc-app-right"><div className="cc-segments" aria-label="Density">{[[.84,'Compact'],[1,'Regular'],[1.2,'Relaxed']].map(([v,label])=><button key={v} aria-pressed={layout.density===v} className={layout.density===v?'active':''} onClick={()=>patch({density:v})}>{label}</button>)}</div><div className="cc-segments cc-page-scale"><button aria-label="Decrease page text" disabled={layout.pageScale<=.8} onClick={()=>patch({pageScale:Math.round((layout.pageScale-.05)*100)/100})}>A−</button><span>{Math.round(layout.pageScale*100)}%</span><button aria-label="Increase page text" disabled={layout.pageScale>=1.4} onClick={()=>patch({pageScale:Math.round((layout.pageScale+.05)*100)/100})}>A+</button></div><span className="cc-feed-summary"><i/> {feed.loading?'reading':meta?.state||'unavailable'} · sources {clock(meta?.repository?.checkedAt||meta?.freshness?.sourceCheckedAt)} · read {clock(feed.readAt)}</span><span className="cc-yahoo-status">Yahoo: {connected?'connected':'not connected'}</span><button className="cc-primary" disabled={feed.loading} onClick={()=>setRefresh(v=>v+1)}>Refresh feed</button></div></header>
 {!route.popout?<nav className="cc-nav" aria-label="Main navigation">{NAV.map(([id,label])=><a key={id} href={`#/${id}`} aria-current={id==='fantasy-news'?'page':undefined}>{label}</a>)}<span>{filtered.length} of {articles.length} in scope · {hours}h · {meta?.snapshotMode||'stored feed'}</span></nav>:<div className="cc-popout-return"><button onClick={windows.returnToDesk}>Return to workspace</button><label><input type="checkbox" checked={autoRead} onChange={e=>setAutoRead(e.target.checked)}/> Auto read stored feed · 60s</label></div>}
 {(feed.error||storageError||windows.notice)&&<div className="cc-notice" role="alert">{feed.error&&`${feed.error} ${feed.data?'Last successful feed retained in memory.':'No values substituted.'}`} {storageError&&'Layout could not be saved in this browser.'} {windows.notice}{windows.notice&&<button aria-label="Dismiss window notice" onClick={()=>windows.setNotice('')}>×</button>}</div>}
 {route.popout?<div className="cc-desk cc-single">{frame(route.pane)}</div>:<div className="cc-desk" aria-label="Fantasy news workspace">
 {layout.leftVisible&&(layout.leftOpen?<div className="cc-status-dock" style={{width:layout.leftW}}>{frame('status')}<Grip label="Resize Status table" className="cc-dock-grip" value={layout.leftW} min={380} max={1100} onChange={leftW=>patch({leftW})}/></div>:<button className="cc-collapsed-rail" aria-label="Expand Status table" onClick={()=>patch({leftOpen:true})}>Status table ›</button>)}
 <div className="cc-center" role="region" aria-label="Central research windows" style={{gridTemplateColumns:fractions(layout.colFr,cols),gridTemplateRows:fractions(layout.rowFr,rows)}}>{visible.map((id,i)=><div key={id} className="cc-cell" style={{gridColumn:(i%cols)*2+1,gridRow:Math.floor(i/cols)*2+1}}>{frame(id)}</div>)}{Array.from({length:Math.max(0,cols-1)},(_,i)=><div key={`col${i}`} className="cc-grid-grip" style={{gridColumn:i*2+2,gridRow:'1/-1'}}><Grip label={`Resize center column ${i+1}`} value={(layout.colFr[i]||1)*100} min={30} max={500} step={10} onChange={v=>{const colFr=[...layout.colFr];colFr[i]=v/100;patch({colFr});}}/></div>)}{Array.from({length:Math.max(0,rows-1)},(_,i)=><div key={`row${i}`} className="cc-grid-grip" style={{gridRow:i*2+2,gridColumn:'1/-1'}}><Grip label={`Resize center row ${i+1}`} axis="y" value={(layout.rowFr[i]||1)*100} min={30} max={500} step={10} onChange={v=>{const rowFr=[...layout.rowFr];rowFr[i]=v/100;patch({rowFr});}}/></div>)}{!visible.length&&<Empty>Research windows hidden. Reopen a window from the taskbar.</Empty>}</div>
 <button className="cc-focus-edge" aria-expanded={layout.pfOpen} onClick={()=>patch({pfOpen:!layout.pfOpen})}>PLAYER FOCUS · {filtered.filter(a=>context(a).owned.length).length} HITS</button>{layout.pfOpen&&<aside className="cc-league-overlay" style={{width:layout.pfW}}><Grip className="cc-league-grip" label="Resize League desk" value={layout.pfW} min={400} max={1100} reverse onChange={pfW=>patch({pfW})}/>{frame('league')}</aside>}
 </div>}
 {!route.popout&&<footer className="cc-taskbar"><span>WINDOWS</span>{Object.entries(NEWS_PANES).map(([id,{title}])=><button key={id} aria-label={`Toggle ${title}`} aria-pressed={enabled(id)} className={enabled(id)?'active':''} onClick={()=>toggleWindow(id)}>{id==='health'?'Feed health':id==='league'?'Player focus · leagues':title}</button>)}<label className="cc-auto-read"><input type="checkbox" checked={autoRead} onChange={e=>setAutoRead(e.target.checked)}/>60s</label><div className="cc-arrange cc-segments">{['tiles','columns','stack'].map(id=><button key={id} aria-pressed={layout.arrange===id} className={layout.arrange===id?'active':''} onClick={()=>patch({arrange:id,maximized:null,colFr:[1,1,1,1],rowFr:[1,1,1,1]})}>{id[0].toUpperCase()+id.slice(1)}</button>)}</div><button className="cc-reset" onClick={()=>setLayout(defaultNewsLayout())}>Reset layout</button></footer>}
 </main>;
}
