import {useEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {bowserFilterPill} from './selectorStyles.js';
import './selectors.css';

export const filterValues=value=>Array.isArray(value)?value:value==null||value==='All'||value==='all'?[]:[value];
export const matchesFilter=(value,selected)=>!filterValues(selected).length||filterValues(selected).includes(value);
export function FilterPill({children,label,on=false,count,disabled=false,size='small',onClick,dropdown=false,...props}) {
 return <button type="button" {...props} className={`bowser-pill ${size==='small'?'bowser-pill-small':''}`} style={{...bowserFilterPill.base,...(size==='small'?bowserFilterPill.small:{}),...props.style}} data-on={on} disabled={disabled} aria-pressed={dropdown?undefined:on} onClick={onClick}>{label??children}{count>0&&<span className="bowser-pill-count">{count}</span>}{dropdown&&<svg className="bowser-pill-caret" width="10" height="6" viewBox="0 0 10 6" aria-hidden="true"><path d="M1 1 L5 5 L9 1" stroke="currentColor" strokeWidth="1.6" fill="none" strokeLinecap="round"/></svg>}</button>;
}
export function FilterSegments({options,value,onChange,label,multiple=false,size='small'}) {
 const selected=filterValues(value);
 return <div className="bowser-pill-row" role="group" aria-label={label}>{options.map(o=>{const [key,title,count]=Array.isArray(o)?o:[o,o];const all=key==='All'||key==='all';const on=multiple?(all?!selected.length:selected.includes(key)):key===value;return <FilterPill key={key} size={size} on={on} count={count} onClick={()=>onChange(multiple?(all?[]:selected.includes(key)?selected.filter(k=>k!==key):[...selected,key]):key)}>{title}</FilterPill>;})}</div>;
}
export function FilterDropdown({label,ariaLabel=label,options,value=[],onChange,multiple=true,disabled=false,size='small',searchable=false,maxSelections=Infinity}) {
 const selected=filterValues(value),[open,setOpen]=useState(false),[search,setSearch]=useState(''),[at,setAt]=useState({}),button=useRef(null),menu=useRef(null),id=useId();
 const choices=options.map(o=>Array.isArray(o)?{value:o[0],label:o[1],count:o[2]}:typeof o==='object'?o:{value:o,label:o});
 const close=()=>{setOpen(false);setSearch('');};
 useEffect(()=>{if(!open)return;const dismiss=e=>{if(e.key==='Escape'){close();button.current?.querySelector('button')?.focus();}else if(e.type==='pointerdown'&&!button.current?.contains(e.target)&&!menu.current?.contains(e.target))close();};const place=()=>{const r=button.current?.getBoundingClientRect();if(r)setAt({left:Math.max(8,Math.min(r.left,innerWidth-258)),top:Math.min(r.bottom+8,innerHeight-160),maxHeight:Math.max(120,innerHeight-r.bottom-20)});};place();if(!searchable)(menu.current?.querySelector('[role=option][aria-selected=true]:not(:disabled)')||menu.current?.querySelector('[role=option]:not(:disabled)'))?.focus();document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',dismiss);window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',dismiss);window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);};},[open]);
 const choose=key=>{if(multiple){if(selected.includes(key))onChange(selected.filter(k=>k!==key));else if(selected.length<maxSelections)onChange([...selected,key]);}else{onChange(key);close();button.current?.querySelector('button')?.focus();}};
 return <span className="bowser-dropdown"><span ref={button}><FilterPill dropdown label={multiple?label:choices.find(c=>String(c.value)===String(value))?.label||label} count={multiple?selected.length:undefined} size={size} on={selected.length>0} disabled={disabled} aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} aria-controls={open?id:undefined} onClick={()=>{if(open)close();else setOpen(true);}}/></span>{open&&!disabled&&createPortal(<div ref={menu} className="bowser-pill-menu" style={at} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){const items=[...menu.current.querySelectorAll('[role=option]:not(:disabled)')],i=items.indexOf(document.activeElement);e.preventDefault();items[e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}}}>{searchable&&<input autoFocus aria-label={`Search ${label}`} placeholder={`Search ${label.toLowerCase()}`} value={search} onChange={e=>setSearch(e.target.value)}/>}<div id={id} role="listbox" aria-label={`${label} options`} aria-multiselectable={multiple||undefined}>{choices.filter(c=>String(c.label).toLowerCase().includes(search.toLowerCase())).map(c=><button key={c.value} type="button" role="option" aria-selected={selected.includes(c.value)} disabled={c.disabled||multiple&&!selected.includes(c.value)&&selected.length>=maxSelections} onClick={()=>choose(c.value)}><span className="bowser-pill-check" data-checked={selected.includes(c.value)} aria-hidden="true">{selected.includes(c.value)?'✓':''}</span><span>{c.label}</span>{c.count!=null&&<small>{c.count}</small>}</button>)}</div><div className="bowser-pill-menu-actions">{multiple&&<button type="button" onClick={()=>onChange([])}>Clear {label.toLowerCase()}</button>}<button type="button" onClick={()=>{close();button.current?.querySelector('button')?.focus();}}>Done</button></div></div>,document.body)}</span>;
}
