import {faabValue,formatFAAB} from '../waiverTable.js';
import {useState} from 'react';
import {AccountTable,YahooErrors} from './YahooConnection.jsx';
import {Field,Picker,PlayerName,Pool,Shell,Source,Status,Tip,useJson} from './shared.jsx';
import {fmt,stamp} from './model.js';
const TONES=['#3ecf8e','#6ea8e5','#d9b45a','#b284e8'];
const record=s=>s?.wins==null?'—':`${s.wins}–${s.losses??'—'}–${s.ties??'—'}`;
export function exactResearchMatch(player,rows){const clean=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'').replace(/(jr|sr|iii|ii)$/,'');const matches=rows.filter(r=>clean(r.name||r.player_display_name)===clean(player.name)&&r.team===player.team&&(r.position===player.position||player.position.split(',').includes(r.position)));return matches.length===1?matches[0]:null;}
export function LeagueHub({season,setSeason,yahoo:y,onOpen}){
 const [workspace,setWorkspace]=useState('Overview'),[scope,setScope]=useState('all'),[search,setSearch]=useState(''),[rosterView,setRosterView]=useState('all'),[researchTeam,setResearchTeam]=useState(''),[researchStatus,setResearchStatus]=useState('FA');
 const scopes=y.leagues.filter(l=>scope==='all'||l.key===scope),teams=y.teams.filter(t=>scope==='all'||t.leagueKey===scope),summaries=y.summaries.filter(s=>scope==='all'||s.leagueKey===scope),scopeName=y.leagues.find(l=>l.key===scope)?.name||'All leagues';
 const waivers=useJson(y.account&&['Overview','Waivers'].includes(workspace)?`/api/v1/waivers?season=${season}&scoring=ppr&trendWeeks=5`:null);
 const accountReady=Boolean(y.account),verifiedLeagues=new Set(y.summaries.filter(s=>s.checkedAt).map(s=>s.leagueKey)).size;
 const health=summaries.map(s=>({key:s.teamKey,league:s.leagueName,lineup:s.health.lineupComplete==null?'—':s.health.lineupComplete?'Complete':'Open slots',injuries:s.health.concerns?.filter(p=>p.status).length??null,byes:s.health.concerns?.filter(p=>p.bye).length??null,open:s.health.openSlots,faab:s.faabBalance}));
 const matches=summaries.map(s=>({key:s.teamKey,league:s.leagueName,opponent:s.matchup?.opponent?.name,projected:s.matchup?.team?.projected,oppProjected:s.matchup?.opponent?.projected,win:null,lineup:s.health.lineupComplete==null?'—':s.health.lineupComplete?'Yes':'Needs attention',points:s.matchup?.team?.points,oppPoints:s.matchup?.opponent?.points,week:s.week}));
 const ownedRosters=teams.flatMap(t=>(y.dashboards[t.key]?.roster?.players||[]).map(p=>({...p,key:`${t.key}:${p.key}`,league:y.leagues.find(l=>l.key===t.leagueKey)?.name,season}))).filter(p=>(rosterView==='all'||(rosterView==='starters'?!['BN','IR','IR+','NA'].includes(p.slot):['BN','IR','IR+','NA'].includes(p.slot)))&&p.name.toLowerCase().includes(search.toLowerCase()));
 const available=new Map();for(const s of summaries){for(const p of s.availability?.players||[]){if(!available.has(p.key))available.set(p.key,{...p,leagueNames:[],season});available.get(p.key).leagueNames.push(s.leagueName);}}
 const radar=[...available.values()].map(p=>{const target=exactResearchMatch(p,waivers.data?.rows||[]);const ranks=Object.values(target?.rankings||{}).map(r=>r.rank).filter(Number.isFinite);const bidEntry=Object.entries(target?.faab||{}).sort(([a],[b])=>a.localeCompare(b)).map(([id,value])=>({id,value:faabValue(value,'native',{annual:null,remaining:null})})).find(entry=>entry.value),bid=bidEntry?.value,source=waivers.data?.meta?.sources?.find(source=>source.id===bidEntry?.id);return {...p,available:p.leagueNames.join(', '),bid:bid?formatFAAB(bid):null,bidBasis:bid&&['annual','remaining'].includes(bid.budgetBasis)?bid.budgetBasis:'basis unknown',bidSource:source?.label||bidEntry?.id,bidUrl:source?.faabUrl,bidDate:source?.publishedAt||source?.capturedAt,bidScoring:source?.faabScoring||source?.scoring,why:target?`Best sourced positional rank ${ranks.length?Math.min(...ranks):'—'} · ${Object.keys(target.faab||{}).length} FAAB sources; open Waivers`:'Yahoo available pool; no matched expert waiver target',target};}).filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));
 const tradeRows=summaries.flatMap(s=>(s.pendingTrades?.items||[]).map(t=>({key:t.key,league:s.leagueName,partner:y.dashboards[s.teamKey]?.standings?.find(x=>x.key===(t.traderTeamKey===s.teamKey?t.tradeeTeamKey:t.traderTeamKey))?.name||'Unavailable',offer:t.players.map(p=>p.name).join(' · '),delta:null,status:t.status||t.type,players:t.players,season})));
 const exposures=y.exposure.players.map(p=>({...p,ownedTeams:p.ownedTeams.filter(t=>scope==='all'||t.leagueKey===scope)})).filter(p=>p.ownedTeams.length).map(p=>({...p,count:p.ownedTeams.length,risk:p.ownedTeams.length>=3?'Concentrated':p.ownedTeams.length===2?'Shared':'Single',season})).filter(p=>p.name.toLowerCase().includes(search.toLowerCase()));
 const decisions=[{key:'lineups',workflow:'Lineups',detail:accountReady?`${health.filter(h=>h.open>0).length} owned teams with unfilled starter slots`:'Connect Yahoo to check starters and open slots',leagues:accountReady?health.filter(h=>h.open>0).map(h=>h.league).join(', ')||'None known':'—',status:health.length&&health.every(h=>h.open!=null)?'Ready':'Awaiting sync',action:'Lineups'}, {key:'injuries',workflow:'Injury flags',detail:accountReady?`${health.reduce((n,h)=>n+(h.injuries||0),0)} flagged starters in loaded rosters`:'Yahoo starter status and bye-week flags',leagues:accountReady?health.filter(h=>h.injuries>0||h.byes>0).map(h=>h.league).join(', ')||'None known':'—',status:health.length&&health.every(h=>h.injuries!=null)?'Ready':'Awaiting sync',action:'Lineups'},{key:'waivers',workflow:'Waivers',detail:'Read league availability before planning bids',leagues:accountReady?String(summaries.filter(s=>s.availability).length)+' pools read':'—',status:summaries.some(s=>s.availability)?'Partial coverage':'Awaiting sync',action:'Waivers'},{key:'trades',workflow:'Trades',detail:tradeRows.length?`${tradeRows.length} pending trades returned`:'Load the read-only offer inbox',leagues:accountReady?String(summaries.filter(s=>s.pendingTrades).length)+' inboxes read':'—',status:summaries.some(s=>s.pendingTrades)?'Ready':'Awaiting sync',action:'Trades'}];
 const needed=<><div className="lhq-summary">{[accountReady,y.teams.length>0,y.coverage.complete,summaries.some(s=>s.availability)].filter(Boolean).length} of 4 checks complete</div>{[['Yahoo authorization',accountReady,'League access verified by a live API read'],['Owned teams',y.teams.length>0,'Teams discovered for the selected season'],['Team dashboards',y.coverage.complete,`${y.coverage.loadedTeams} of ${y.teams.length} loaded`],['Availability research',summaries.some(s=>s.availability),'Read a league’s current free-agent pool']].map(([title,done,detail])=><div className="lhq-check" key={title}><b className={done?'done':''}>{done?'✓':''}</b><div><strong>{title}</strong><small>{detail}</small></div></div>)}<div className="lhq-panel-actions"><a href="#/yahoo" className="lhq-mini">Go to Yahoo Connection</a></div></>;
 const selectedResearch=teams.find(t=>t.key===researchTeam)||teams[0],research=selectedResearch?y.research[selectedResearch.key]:null;
 const researchControls=<><p className="lhq-note">Research reads the current Yahoo pool, regardless of the historical matchup week. Each page contains at most 25 players. Absence does not prove a player is rostered.</p><Field label="Owned team"><select value={selectedResearch?.key||''} onChange={e=>setResearchTeam(e.target.value)}>{teams.map(t=><option key={t.key} value={t.key}>{t.name}</option>)}</select></Field><Field label="Availability"><select value={researchStatus} onChange={e=>setResearchStatus(e.target.value)}><option value="A">All available</option><option value="FA">Free agents</option><option value="W">Waivers</option></select></Field><div className="lhq-panel-actions"><button className="lhq-mini" disabled={!selectedResearch||y.researchBusy[selectedResearch.key]} onClick={()=>y.loadResearch(selectedResearch.key,{include:'availability,trades,transactions',availabilityStatus:researchStatus})}>Read current research</button>{research?.availability?.status===researchStatus&&research?.availability?.nextStart!=null&&<button className="lhq-mini lhq-outline" disabled={y.researchBusy[selectedResearch.key]} onClick={()=>y.loadResearch(selectedResearch.key,{include:'availability,trades,transactions',availabilityStart:research.availability.nextStart,availabilityStatus:researchStatus})}>Next 25</button>}</div>{research&&<p className="lhq-note">Captured {stamp(research.checkedAt)} · Pool start {research.availability?.start??'—'} · {research.availability?.complete?'Complete pool':'Partial pool'} · {research.availability?.status||'Unavailable'}{Object.values(research.errors||{}).map((error,i)=><span key={i}>{error}</span>)}</p>}</>;
 const module=(key,eyebrow,title,columns,rows,empty,note)=> <section className="lhq-position-window lhq-hub-module" key={key}><div className="lhq-window-title"><span style={{color:TONES[['decisions','matches','health','waivers','trades','exposure'].indexOf(key)%4]}}>{eyebrow}</span><strong>{title}</strong><small>{rows.length||''}</small><em>{note}</em></div><AccountTable title={title} columns={columns.map((c,i)=>({...c,width:({decisions:[22,34,18,14,12],matches:[16,22,12,12,22,16],health:[16,18,18,14,16,18],waivers:[20,8,10,24,14,24],trades:[14,20,34,16,16],exposure:[24,10,12,30,24]}[key]?.[i]??parseFloat(c.width))+'%'}))} rows={rows} empty={<><strong>{title}</strong> — {empty}</>} group={false}/></section>;
 const baseLeague={key:'league',label:'League',width:'22%',render:r=><span className="lhq-league-chip">{r.league||'—'}</span>};
 return <Shell page="league-hub" stacks={<><Picker label="League scope" value={scope} onChange={setScope} options={[["all","All leagues"],...y.leagues.map(l=>[l.key,l.name])]}/><Picker label="Season" value={season} onChange={v=>setSeason(Number(v))} options={[2025,2026]}/><Picker label="Week" value={y.week} onChange={y.setWeek} options={[["current","Current"],...Array.from({length:18},(_,i)=>[i+1,`W${i+1}`])]}/><div className="lhq-stack"><span>Yahoo</span><strong style={{color:accountReady?'#3ecf8e':'#e8735a'}}>{accountReady?`${verifiedLeagues} of ${y.leagues.length} connected`:'Setup required'}</strong></div></>} actions={<><small>Connected</small>{verifiedLeagues} of {y.leagues.length} leagues <a className="lhq-mini lhq-outline" href="#/yahoo">{accountReady?'Yahoo Connection':'Connect Yahoo'}</a></>} sources={<><Source label="LEAGUE SOURCE" title={`Yahoo Fantasy · ${season}`} detail={accountReady?`${y.leagues.length} leagues · ${stamp(y.account.checkedAt)}`:'connect to discover your leagues'}/><Source label="PLAYER DATA" title="nflverse + DraftKings" detail="projections, snaps, salaries" help="Public football data and private Yahoo league data keep their separate source and scoring contexts."/><span className="lhq-source-note">Private Yahoo data stays in memory</span></>} panels={[{id:'needed',title:'Information needed',shortTitle:'Info',content:needed},{id:'exposure',title:'Player exposure',shortTitle:'Exposure',content:<table><tbody>{exposures.slice(0,8).map(p=><tr key={p.key}><td><PlayerName row={p} onOpen={onOpen}/></td><td>{p.count} of {y.exposure.loadedTeams}</td></tr>)}</tbody></table>},{id:'standings',title:'Standings snapshot',shortTitle:'Standings',content:<table><thead><tr><th>League</th><th>Rec</th><th>Rank</th><th>PF</th><th>Playoff %</th></tr></thead><tbody>{summaries.map(s=><tr key={s.teamKey}><td>{s.leagueName}</td><td>{record(s.standing)}</td><td>{fmt(s.standing?.rank)}</td><td>{fmt(s.standing?.pointsFor,1)}</td><td><Tip text="Playoff probability unavailable">—</Tip></td></tr>)}</tbody></table>},{id:'research',title:'League research',shortTitle:'Research',content:researchControls},{id:'filters',title:'Filters & settings',shortTitle:'Filters',content:<><Field label="Player search"><input value={search} onChange={e=>setSearch(e.target.value)}/></Field><Field label="Roster view"><select value={rosterView} onChange={e=>setRosterView(e.target.value)}><option value="all">All slots</option><option value="starters">Starters</option><option value="reserves">Bench / reserve</option></select></Field>{accountReady&&<button className="lhq-mini lhq-outline" disabled={y.busy} onClick={()=>y.load()}>Refresh dashboards</button>}</>}] }>
 <div className="lhq-pool-line"><Pool tabs={['Overview','Lineups','Waivers','Trades','Exposure'].map(w=>({key:w,label:w}))} value={workspace} onChange={setWorkspace}/><span className="lhq-hub-context">{scopeName} · {workspace} · {accountReady?'Yahoo league scoring':'modules populate after the first Yahoo sync'}</span></div><div className="lhq-strip lhq-league-tiles"><button onClick={()=>setScope('all')}>All<br/>✓</button>{y.leagues.map((l,i)=><button className={scope!=='all'&&scope!==l.key?'dim':''} key={l.key} onClick={()=>setScope(l.key)}><b style={{background:TONES[i%4]}}>{l.name?.slice(0,3).toUpperCase()}</b><span><small>Yahoo Fantasy · {l.season}</small><strong>{l.name}</strong><em>{y.teams.filter(t=>t.leagueKey===l.key).map(t=>t.name).join(', ')||'Owned team unavailable'}</em></span><i style={{background:y.summaries.some(s=>s.leagueKey===l.key&&s.checkedAt)?'#3ecf8e':'#c9d6dc'}}/></button>)}{!y.leagues.length&&<span className="lhq-note">No leagues discovered. Connect Yahoo to populate your private workspace.</span>}</div><Status loading={y.busy}/><YahooErrors y={y}/>
 {workspace==='Overview'&&module('decisions','WORKFLOW','Decisions that need attention',[{key:'workflow',label:'Workflow',width:'17%',render:r=><strong style={{color:'#3ecf8e'}}>{r.workflow}</strong>},{key:'detail',label:'Detail',width:'42%'},{key:'leagues',label:'Leagues',width:'18%'},{key:'status',label:'Status',width:'13%'},{key:'action',label:'',width:'10%',render:r=><button className="lhq-data-link" onClick={()=>setWorkspace(r.action)}>Open →</button>}],decisions,'Connect Yahoo to prioritize actions.')}
 {['Overview','Lineups'].includes(workspace)&&<>{module('matches','WEEKLY','Matchup board',[baseLeague,{key:'opponent',label:'Opponent',width:'26%'},{key:'projected',label:'Proj',width:'12%',render:r=>fmt(r.projected,1)},{key:'oppProjected',label:'Opp proj',width:'12%',render:r=>fmt(r.oppProjected,1)},{key:'win',label:'Win %',width:'12%',help:'Unavailable: no win-probability source',render:()=> <Tip text="Yahoo win probability unavailable">—</Tip>},{key:'lineup',label:'Lineup set',width:'16%'}],matches,'Connect Yahoo to load weekly matchups and league-scored projections.','Selected week · projections only where sourced')}{module('health','ROSTER','Team health matrix',[baseLeague,{key:'lineup',label:'Lineup',width:'22%'},{key:'injuries',label:'Flags',width:'14%'},{key:'byes',label:'Byes',width:'12%'},{key:'open',label:'Open spots',width:'14%',render:r=><span style={{color:r.open>0?'#e8735a':undefined}}>{r.open??'—'}</span>},{key:'faab',label:'FAAB',width:'16%',render:r=>r.faab==null?'—':`$${r.faab}`}],health,'Starters, injury flags, bye weeks, empty slots, and FAAB are league-specific.')}</>}
 {workspace==='Lineups'&&module('rosters','LINEUPS','Owned-team rosters',[{key:'name',label:'Player',width:'25%',render:r=><PlayerName row={r} onOpen={onOpen}/>},{key:'slot',label:'Slot',width:'9%'},{key:'position',label:'Pos',width:'9%'},{key:'team',label:'NFL',width:'9%'},{key:'league',label:'League',width:'24%'},{key:'status',label:'Status',width:'12%'},{key:'points',label:'Yahoo pts',width:'12%',render:r=>fmt(r.points,2)}],ownedRosters,'Connect Yahoo to load starters and reserves.','Selected week · league scoring')}
 {['Overview','Waivers'].includes(workspace)&&module('waivers','AVAILABLE PLAYERS','Waiver radar',[{key:'name',label:'Player',width:'18%',render:r=><PlayerName row={r} onOpen={onOpen}/>},{key:'position',label:'Pos',width:'7%'},{key:'team',label:'Team',width:'8%'},{key:'available',label:'Available in',width:'24%',render:r=><span style={{color:'#3ecf8e'}}>{r.available}</span>},{key:'bid',label:'Suggested bid',width:'13%',help:'A source-native published FAAB bid when an exact player match exists; not adjusted to this league budget.',render:r=><Tip text={r.bidSource?`Source: ${r.bidSource}; ${r.bidBasis} budget; ${r.bidScoring||'scoring unspecified'}; ${stamp(r.bidDate)}. Native units, not league adjusted. All source bids on Waivers.`:'No exact sourced bid match available'}><a className="lhq-two-line" href={r.bidUrl||'#/waivers'} target={r.bidUrl?'_blank':undefined} rel={r.bidUrl?'noreferrer':undefined}><b>{r.bid||'—'}</b>{r.bid&&<small>{r.bidBasis}</small>}</a></Tip>},{key:'why',label:'Why',width:'30%',render:r=><Tip text={r.why}><a href="#/waivers">{r.why}</a></Tip>}],radar,'Use League research in the sidebar to read the current available pool.','Availability map · FAAB planner on Waivers · claims are read only')}
 {['Overview','Trades'].includes(workspace)&&module('trades','TRADE CENTER','Trade center',[baseLeague,{key:'partner',label:'Partner',width:'18%'},{key:'offer',label:'Offer',width:'35%',render:r=><Tip text={r.offer}><span>{r.players.map((p,i)=><span key={p.key||i}>{i?' · ':''}<PlayerName row={{...p,season}} onOpen={onOpen}/></span>)}</span></Tip>},{key:'delta',label:'Value delta',width:'13%',help:'Unavailable: no league-specific player value source'},{key:'status',label:'Status',width:'12%'}],tradeRows,'Read the league research inbox to retrieve current pending offers.','No offers or lineup changes are submitted')}
 {workspace==='Exposure'&&module('exposure','PORTFOLIO','Player exposure',[{key:'name',label:'Player',width:'32%',render:r=><PlayerName row={r} onOpen={onOpen}/>},{key:'position',label:'Pos',width:'10%'},{key:'team',label:'Team',width:'12%'},{key:'count',label:'Teams rostering',width:'30%',render:r=><span className="lhq-exposure-bar"><i style={{width:`${100*r.count/Math.max(1,teams.length)}%`}}/>{r.count} of {teams.length}</span>},{key:'risk',label:'Risk',width:'16%',help:'Concentrated: 3+ owned rosters; Shared: 2; Single: 1. Descriptive concentration, not a performance forecast.',render:r=><span style={{color:r.count>=3?'#e8735a':r.count===2?'#d8bf79':'#9e9e9e'}}>{r.risk}</span>}],exposures,'Roster overlap appears after Yahoo teams load.',`${y.exposure.loadedTeams}/${y.exposure.totalTeams} rosters loaded · current selection`)}
 <p className="lhq-footnote">Standings are current season standings. Matchups and rosters use the selected week. Available players and trades are current Yahoo research. — means unavailable.</p></Shell>;
}
