import {useEffect,useMemo,useState} from 'react';
import {Bars,Chips,Field,Grid,Picker,PlayerName,Pool,Ranges,Shell,Source,Status,Tiles,Tip,useStored} from './shared.jsx';
import {COLORS,fmt,inRanges,stamp} from './model.js';
import {combineMarketRows,isWatched,sortMarketRows} from '../marketPulseRows.js';
import {addCommentary,TOPICS,sentimentOf,topicOf} from '../marketCommentary.js';
import commentary from '../../data/market-commentary.json';
import {csvFor} from '../MarketPulse.jsx';
import {useMarketData} from './useMarketData.js';
const FIELD_ROWS=[['watch','★',33,'identity'],['name','Player',141,'identity'],['team','Team',56,'identity'],['position','Pos',47,'identity'],['adds','Adds',84,'usage'],['drops','Drops',84,'usage'],['net','Net',92,'usage'],['addShare','Add / drop',100,'usage'],['rosterPct','Roster %',84,'market'],['startPct','Start %',78,'market'],['rosterDelta','Δ Ros · pp',92,'market'],['newsCount','News',62,'news'],['newsTopic','Latest topic',150,'news'],['positive','Pos +',62,'news'],['neutral','Neutral',72,'news'],['negative','Neg −',62,'news'],['unclear','Unclear',72,'news'],['newsConfidence','Conf %',72,'news'],['newsBalance','Tone',62,'news'],['newsDelta','Δ Tone · pp',96,'news']];
export function MarketPulse({season,setSeason,onOpen}){
 const [rowLimit,setRowLimit]=useState('');
 const [saved,setSaved]=useStored('bowser:market-pulse:v1',{}),[hours,setHours]=useState([6,24,72].includes(saved.hours)?saved.hours:24),[watch,setWatch]=useState(Array.isArray(saved.watch)?saved.watch:[]),[position,setPosition]=useState(saved.position||'All'),[sort,setSort]=useState(saved.sort||{key:'adds',desc:true});
 const [newsHours,setNewsHours]=useState(72),[topic,setTopic]=useState('all'),[tone,setTone]=useState('all'),[pool,setPool]=useState('all'),[search,setSearch]=useState(''),[ranges,setRanges]=useState({}),[matches,setMatches]=useState([]),[team,setTeam]=useState('All'),[single,setSingle]=useState(false),[clock,setClock]=useState(Date.now),[inspect,setInspect]=useState(null),[historyMetric,setHistoryMetric]=useState('adds'),[historyCount,setHistoryCount]=useState(10);
 const [hideNews,setHideNews]=useStored('bowser:lhq:market:hideNews',false),[widths,setWidths]=useStored('bowser:lhq:market:widths',{});
 const {snapshots,busy,errors,notice,load}=useMarketData(hours);
 useEffect(()=>setSaved({hours,position,watch,sort}),[hours,position,watch,sort]);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const combined=useMemo(()=>addCommentary(combineMarketRows(snapshots.sleeper?.window===String(hours)?snapshots.sleeper.rows:[],snapshots.espn?.rows||[]),commentary,{hours:newsHours,topic,now:clock}),[snapshots,hours,newsHours,topic,clock]);
 const toggle=row=>setWatch(w=>isWatched(row,w)?w.filter(id=>!row.aliases.includes(id)):[...w,row.id]);
 const selected=combined.find(r=>r.id===inspect),filtered=combined.filter(r=>(pool!=='watch'||isWatched(r,watch))&&(pool!=='news'||r.newsCount>0)&&(position==='All'||r.position===position)&&(team==='All'||r.team===team)&&(!matches.length||matches.includes(r.match))&&(!single||!r.match.endsWith('only'))&&(topic==='all'||r.newsCount>0)&&(tone==='all'||r[tone]>0)&&`${r.name} ${r.team}`.toLowerCase().includes(search.toLowerCase())&&inRanges(r,ranges,{})),rows=sortMarketRows(filtered,sort,watch);
 const signed=v=>v==null?'—':`${v>0?'+':''}${fmt(v,Math.abs(v)>=1?0:2)}`;
 const columns=FIELD_ROWS.filter(c=>!hideNews||c[3]!=='news').map(([key,label,width,group])=>({key,label,width,group,pin:group==='identity'?'left':undefined,groupLabel:{identity:'Player',usage:`Sleeper · ${hours}h transactions`,market:'ESPN · ownership',news:`News commentary · Jev · ${newsHours}h`}[group],value:r=>key==='watch'?Number(isWatched(r,watch)):r[key],help:key==='newsConfidence'?'Mean accepted model sentiment confidence; not source reliability or probability of football success.':key==='newsBalance'?'100 × (positive − negative) / accepted commentary. Not a popularity score.':key==='rosterDelta'?'Percentage-point change since preceding saved ESPN snapshot.':`${label}; source-specific observation, missing is not zero.`,render:r=>{const v=r[key];if(key==='watch')return <button className={`lhq-star ${isWatched(r,watch)?'active':''}`} aria-label={`Watch ${r.name}`} onClick={()=>toggle(r)}>{isWatched(r,watch)?'★':'☆'}</button>;if(key==='name')return <PlayerName row={r} onOpen={onOpen} marked={isWatched(r,watch)}/>;if(['team','position','newsTopic'].includes(key))return v||'—';if(key==='addShare')return v==null?'—':<div className="lhq-split-bar"><span><i style={{width:`${v}%`}}/></span><small>{fmt(v)}% adds</small></div>;if(key==='newsCount')return v==null?'—':<button className="lhq-data-link" onClick={()=>setInspect(r.id)}>{v}</button>;if(['net','rosterDelta','newsDelta','newsBalance'].includes(key))return <b style={{color:v==null?'#707070':v<0?'#e8735a':'#3ecf8e'}}>{signed(v)}</b>;return <span style={{color:['adds','positive'].includes(key)?'#3ecf8e':['drops','negative'].includes(key)?'#e8735a':undefined}}>{v==null?'—':`${fmt(v,['rosterPct','startPct','newsConfidence'].includes(key)?1:0)}${['rosterPct','startPct','newsConfidence'].includes(key)?'%':''}`}</span>;}}));
 const download=()=>{const url=URL.createObjectURL(new Blob([csvFor(rows,{...snapshots,commentary})],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`bowser-market-${hours}h.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const most=sortMarketRows(combined.filter(r=>r.adds!=null),{key:'adds',desc:true}).slice(0,10),max=most[0]?.adds||1;
 const mostPanel=<table><thead><tr><th>Player</th><th>Relative adds</th><th>Adds</th></tr></thead><tbody>{most.map(r=><tr key={r.id}><td><PlayerName row={r} onOpen={onOpen}/><small>{r.position} · {r.team}</small></td><td><div className="lhq-mover-track"><i style={{width:`${100*r.adds/max}%`}}/></div></td><td>{fmt(r.adds)}</td></tr>)}</tbody></table>;
 const watchPanel=<table><thead><tr><th>Player</th><th>Net</th><th>Roster %</th><th/></tr></thead><tbody>{combined.filter(r=>isWatched(r,watch)).map(r=><tr key={r.id}><td><PlayerName row={r} onOpen={onOpen}/></td><td>{signed(r.net)}</td><td>{fmt(r.rosterPct,1)}</td><td><button className="lhq-data-link" onClick={()=>toggle(r)} aria-label={`Remove ${r.name}`}>×</button></td></tr>)}</tbody></table>;
 const settings=<><Field label="Team"><select value={team} onChange={e=>setTeam(e.target.value)}>{['All',...new Set(combined.map(r=>r.team))].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="News window"><select value={newsHours} onChange={e=>setNewsHours(Number(e.target.value))}>{[24,72,168].map(v=><option key={v} value={v}>{v} hours</option>)}</select></Field><Field label="News topic"><select value={topic} onChange={e=>setTopic(e.target.value)}><option value="all">All topics</option>{Object.entries(TOPICS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Commentary tone"><select value={tone} onChange={e=>setTone(e.target.value)}>{['all','positive','neutral','negative','unclear'].map(v=><option key={v}>{v}</option>)}</select></Field><label><input type="checkbox" checked={single} onChange={e=>setSingle(e.target.checked)}/>Hide single-provider rows</label><Field label="Inspect source history"><select value={inspect||''} onChange={e=>setInspect(e.target.value)}><option value="">Select player</option>{combined.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field></>;
 const provider=['rosterPct','startPct','rosterDelta'].includes(historyMetric)?'espn':'sleeper',source=snapshots[provider],observations=(source?.history||[]).slice(-historyCount),history=observations.map((h,i)=>({key:h.capturedAt,label:stamp(h.capturedAt),snaps:h.rows.find(r=>selected?.aliases.includes(r.id))?.[historyMetric]??null}));const allValues=observations.flatMap(h=>h.rows.map(r=>r[historyMetric])).filter(Number.isFinite),domain={min:Math.min(0,...allValues),max:Math.max(1,...allValues)};
 const detail=selected?<div className="lhq-research"><h3>{selected.name}</h3><Field label="History metric"><select value={historyMetric} onChange={e=>setHistoryMetric(e.target.value)}>{['adds','drops','net','addShare','rosterPct','startPct'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Observations"><select value={historyCount} onChange={e=>setHistoryCount(Number(e.target.value))}>{[5,10,16,32,96].map(v=><option key={v}>{v}</option>)}</select></Field><Bars history={history} metric="snaps" domain={domain} large/><p className="lhq-note">{history.length} saved provider observations, not NFL games. Overlapping windows are not additive.</p>{selected.news?.map(n=><article key={n.id}><a href={n.url} target="_blank" rel="noreferrer">{n.title}</a><small>{n.source} · {stamp(n.publishedAt)} · {TOPICS[topicOf(n)]} · {sentimentOf(n)}</small><p>{n.excerpt}</p></article>)}</div>:<p className="lhq-note">Choose a player in Filters & settings to inspect saved observations and linked news.</p>;
 return <Shell page="market-pulse" focusPanel={{id:'research',key:inspect}} defaultPanel="most" panels={[{id:'most',title:`Most added · ${hours}h`,content:mostPanel},{id:'watch',title:`Watch list (${combined.filter(r=>isWatched(r,watch)).length})`,content:watchPanel},{id:'settings',title:'Filters & settings',content:settings},{id:'research',title:'Source history & news',content:detail}]} stacks={<><Picker label="Season" value={season} options={[2025,2026]} onChange={v=>setSeason(Number(v))}/><Picker label="Window" value={hours} options={[6,24,72].map(v=>[v,`${v}h transactions`])} onChange={v=>setHours(Number(v))}/><Picker label="News" value={newsHours} options={[24,72,168].map(v=>[v,`${v}h · Jev`])} onChange={v=>setNewsHours(Number(v))}/><div className="lhq-stack"><span>Captured</span><strong>{stamp(snapshots.sleeper?.capturedAt)}</strong></div></>} actions={<><small>SHOW <input type="number" min="0" aria-label="Displayed row limit" value={rowLimit===''?rows.length:rowLimit} onChange={e=>setRowLimit(e.target.value)}/> PLAYERS USING</small><Picker label="Sort" value={sort.key} onChange={key=>setSort({key,desc:true})} options={columns.filter(c=>c.sortable!==false).map(c=>[c.key,`${c.groupLabel||c.group||''} · ${c.label}`])}/><button className="lhq-mini lhq-outline" onClick={download}>Export CSV</button><button className="lhq-mini" disabled={busy} onClick={()=>load(true)}>{busy?'Refreshing…':'Refresh data'}</button></>} sources={<><Source label="TRANSACTION SOURCE" title={`Sleeper · ${hours}h`} detail={`${snapshots.sleeper?.rows?.length||0} players · ${stamp(snapshots.sleeper?.capturedAt)}`} help="Rolling transactions; observed top-list counts are not league-specific."/><Source label="OWNERSHIP SOURCE" title="ESPN · ownership" detail={`Roster % · Start % · ${stamp(snapshots.espn?.capturedAt)}`} help="ESPN public league population; change requires a preceding saved observation."/><button className="lhq-mini" onClick={()=>setHideNews(!hideNews)}>{hideNews?'Show':'Hide'} news columns</button><Tip text={`Commentary captured ${stamp(commentary.capturedAt)}. Classifications link to sampled sources.`}><span>ⓘ</span></Tip></>}>
 <div className="lhq-pool-line"><Pool tabs={[{key:'all',label:'All',count:combined.length},{key:'watch',label:'Watch',count:combined.filter(r=>isWatched(r,watch)).length},{key:'news',label:'Has news',count:combined.filter(r=>r.newsCount>0).length}]} value={pool} onChange={setPool} transfer={()=>setWatch([...new Set([...watch,...filtered.map(r=>r.id)])])}/><Ranges definitions={[["adds","Adds"],["net","Net"],["rosterPct","Roster %"],["startPct","Start %"]]} values={ranges} onChange={setRanges}/></div>
 <div className="lhq-strip"><Chips values={['All','QB','RB','WR','TE','K','DEF']} value={position} onChange={setPosition}/><Tiles tiles={['Provider ID','Name, position & team','Team defense','Sleeper only','ESPN only'].map(m=>({key:m,title:m,detail:`${combined.filter(r=>r.match===m).length} players`,sub:m.endsWith('only')?'No cross-provider match':'Unambiguous identities only'}))} selected={matches} onClear={()=>setMatches([])} onToggle={m=>setMatches(a=>a.includes(m)?a.filter(x=>x!==m):[...a,m])}/></div>
 {Object.entries(snapshots).filter(([,snapshot])=>snapshot?.stale).map(([provider])=><p className="lhq-note" role="status" key={provider}>{provider}: retained stale snapshot · captured {stamp(snapshots[provider].capturedAt)}. Refresh to request current observations.</p>)}{Object.entries(errors).map(([k,v])=><Status key={k} error={`${k}: ${v}. Last successful snapshot retained when available.`}/>)}{notice&&<p className="lhq-note" role="status">{notice}</p>}<Status loading={busy&&!combined.length}/><Grid columns={columns} rows={rowLimit===''?rows:rows.slice(0,Math.max(0,Number(rowLimit)||0))} rowKey={r=>r.id} sort={sort} onSort={setSort} search={search} onSearch={setSearch} reset={()=>{setRowLimit('');setPool('all');setPosition('All');setSearch('');setMatches([]);setRanges({});setTeam('All');setSingle(false);setTopic('all');setTone('all');}} widths={widths} resizable onResize={(k,v)=>setWidths(w=>({...w,[k]:v}))}/><div className="lhq-footnote"><span>{rowLimit===''?rows.length:Math.min(rows.length,Math.max(0,Number(rowLimit)||0))} shown · {rows.length} of {combined.length} players · sourced provider observations</span><span>Different provider populations · missing ≠ zero · 96 saved observations per provider/window</span></div>
 </Shell>;
}
