export const COLORS={identity:'#ededed',game:'#ededed',usage:'#3ecf8e',passing:'#5aa9ff',rushing:'#f2ae49',receiving:'#a87cff',dfs:'#d8bf79',fantasy:'#3ecf8e',market:'#5aa9ff',news:'#d8bf79',rank:'#3ecf8e',ranks:'#3ecf8e',faab:'#d8bf79',misc:'#b4b4b4'};
export const POSITIONS=['QB','RB','WR','TE'];
export const SCORING=[['ppr','PPR'],['half','Half PPR'],['standard','Standard']];
export const fmt=(v,d=0)=>v==null||v===''?'—':Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
export const salary=v=>v==null?'—':`$${(v/1000).toFixed(1)}K`;
export const pct=v=>v==null?'—':`${fmt(v,1)}%`;
export const stamp=v=>v&&!Number.isNaN(new Date(v).getTime())?new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Unavailable';
export function sortRows(rows,sort,columns){const c=columns.find(c=>c.key===sort.key);const value=c?.value||((r)=>r[sort.key]);return [...rows].sort((a,b)=>{const x=value(a),y=value(b),missing=v=>v==null||v==='';if(missing(x)||missing(y))return missing(x)?missing(y)?String(a.name||a.player_display_name||'').localeCompare(String(b.name||b.player_display_name||'')):1:-1;return (typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),undefined,{numeric:true}))*(sort.desc?-1:1)||(c?.tieValue?((c.tieValue(a)??0)-(c.tieValue(b)??0))*(sort.desc?-1:1):0)||String(a.name||a.player_display_name||'').localeCompare(String(b.name||b.player_display_name||''));});}
export function inRanges(row,ranges,fields){return Object.entries(ranges).every(([key,r])=>{if(r.min===''&&r.max==='')return true;const v=fields[key]?.(row)??row[key];return Number.isFinite(v)&&(r.min===''||v>=Number(r.min))&&(r.max===''||v<=Number(r.max));});}
export function competitionRank(rows,value=r=>r.fantasy_points,desc=true){const known=rows.filter(r=>{const v=value(r);return v!=null&&v!==''&&(typeof v!=='number'||Number.isFinite(v));});const compare=(a,b)=>typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b),undefined,{numeric:true});const sorted=[...known].sort((a,b)=>compare(value(a),value(b))*(desc?-1:1));const out=new Map();let rank=0,last;sorted.forEach((r,i)=>{const v=value(r);if(i===0||compare(v,last)!==0)rank=i+1;last=v;out.set(r.player_id||r.playerId||r.key||r.name,rank);});return out;}
const STAT_DEFINITIONS={
 select:'Player selection — local selection for this player pool.',
 name:'Player name — opens the sourced player profile when an unambiguous warehouse identity is available.',
 player_display_name:'Player name — opens the sourced player profile.',
 position:'Position — the position reported by the source.',team:'Team — the NFL team reported for the selected statistics or provider observation.',
 rank:'Competition rank — rank among loaded players using the active sort field and direction. Ties share a rank and the next rank skips those places; unknown values are unranked.',
 source_rank:'Published waiver rank — this source’s positional ordering, not an NFL-wide fantasy finish. Lower numbers rank earlier; unranked players remain blank.',
 faab:'Free-agent acquisition budget bid — a published source range or bound. Preserve its stated units and annual, remaining, or unknown budget basis; conversion requires a known matching budget.',
 favorite:'Favorite — a local research preference, not a submitted waiver claim.',watch:'Watch list — a local research preference, not roster ownership.',marker:'Research marker — a local player-ID preference; no source data is changed.',
 games_played:'Games played — sourced appearances in the exact selected statistics weeks.',
 snaps:'Offensive snaps — offensive plays in which the player participated in the selected statistics period.',
 snap_pct:'Snap percentage — the player’s share of team offensive snaps. Across selected weeks, the summary uses the sourced team-snap denominator, not a sum of weekly percentages. Missing participation remains unavailable.',
 passing_line:'Completions–attempts — completed passes followed by pass attempts in the selected statistics period.',
 passing_attempts:'Pass attempts — passes attempted in the selected statistics period; sacks are not pass attempts.',
 pass_attempts:'Pass attempts — passes attempted in the selected statistics period; sacks are not pass attempts.',
 completions:'Completions — completed passes in the selected statistics period.',completion_pct:'Completion percentage — completed passes divided by pass attempts, multiplied by 100; unavailable with no attempts.',
 passing_yards:'Passing yards — sourced passing-yard total for the selected statistics period.',passing_tds:'Passing touchdowns — touchdown passes in the selected statistics period.',interceptions:'Interceptions thrown — passes intercepted by the defense in the selected statistics period.',
 carries:'Rush attempts — rushing attempts in the selected statistics period.',rush_attempts:'Rush attempts — rushing attempts in the selected statistics period.',rushing_yards:'Rushing yards — sourced rushing-yard total for the selected statistics period.',rushing_tds:'Rushing touchdowns — rushing touchdowns in the selected statistics period.',
 targets:'Receiving targets — pass targets credited to the player in the selected statistics period.',receptions:'Receptions — completed catches credited to the player in the selected statistics period.',receiving_yards:'Receiving yards — sourced receiving-yard total for the selected statistics period.',receiving_tds:'Receiving touchdowns — touchdown receptions in the selected statistics period.',catch_pct:'Catch percentage — receptions divided by targets, multiplied by 100; unavailable with no targets.',touches:'Touches — rush attempts plus receptions; unavailable if either input is unknown.',
 fantasy_points:'Fantasy points — actual cumulative points for the exact selected statistics weeks under the selected scoring system, not a projection or per-game average.',
 position_finish:'Weekly positional finish — NFL-wide competition rank against players at the same position in the same NFL week and scoring system. Ties share a rank and skip subsequent places. This rank is calculated before local filters; it is not a multiweek aggregate rank.',
 draft_kings_price:'DraftKings salary — sourced price for the separately selected DFS slate; historical Team Box columns use that exact season/week archive. Missing salaries remain unavailable.',
 draft_kings_projection:'DraftKings fantasy projection — sourced projection for the stated DFS slate and provider, not actual points or historical averages.',
 upcoming_opponent:'Upcoming opponent — the scheduled matchup, independent of the selected historical statistics weeks.',upcoming_kickoff_utc:'Kickoff — sourced scheduled start time, displayed in Eastern Time.',adp:'Average draft position — the draft position reported by the stated source; unavailable without a sourced value.',draft_position_rank:'Draft positional rank — the ranking reported by the draft source, not a weekly fantasy finish.',
 adds:'Public player adds — Sleeper observed top-list adds in the selected rolling transaction window, not this Yahoo league’s transactions.',drops:'Public player drops — Sleeper observed top-list drops in the selected rolling transaction window, not this Yahoo league’s transactions.',net:'Net public adds — observed Sleeper adds minus drops in the same rolling window; unknown inputs remain unavailable.',addShare:'Add share — observed adds divided by adds plus drops, multiplied by 100. Not ownership or a popularity probability.',
 rosterPct:'Roster percentage — ESPN’s public league population rostering the player at the capture time; not ownership in your Yahoo leagues.',startPct:'Start percentage — ESPN’s reported public start percentage at the capture time; not your Yahoo lineup status.',rosterDelta:'Roster percentage change — percentage-point difference from the preceding saved ESPN observation; unavailable without comparable observations.',
 newsCount:'News count — sampled commentary records in the selected news window and topic.',newsTopic:'Latest news topic — the classified topic of the latest matched commentary record.',positive:'Positive commentary — sampled records with an accepted positive sentiment classification.',neutral:'Neutral commentary — sampled records with an accepted neutral sentiment classification.',negative:'Negative commentary — sampled records with an accepted negative sentiment classification.',unclear:'Unclear commentary — sampled records without a qualifying accepted sentiment classification.',newsConfidence:'Sentiment confidence — mean accepted model classification confidence, not source reliability or football outcome probability.',newsBalance:'Commentary balance — 100 × (positive minus negative) divided by accepted commentary records; not player popularity.',newsDelta:'Commentary balance change — percentage-point difference between current and prior news windows, requiring at least two accepted records in each.',
};
export function columnHelp(column){
 const raw=String(column.stat||column.metric||column.widthKey||column.key||''),key=raw.startsWith('rank:')?'source_rank':raw.startsWith('faab:')?'faab':raw.replace(/^\d{4}-\d{1,2}:/,'');
 const labelKey=typeof column.label==='string'?column.label.toLowerCase().replace(/%/g,'pct').replace(/[\s/]+/g,'_'):'';
 const statistic=STAT_DEFINITIONS[key]||STAT_DEFINITIONS[labelKey];
 const isTrend=column.kind==='trend'||/_trend$|^trend:|^chart\d+$/.test(raw);
 const definition=isTrend?[statistic,'Aligned weekly trend — one bar per NFL calendar slot, with bye, DNP and missing-data gaps retained. Bar heights and positive-value color intensity share the largest absolute value in the visible column for the same metric. Higher values are brighter; negative values stay subdued and retain signed labels. Direction compares the first and latest values; missing endpoints remain unavailable.'].filter(Boolean).join(' '):/^avg\d+$/.test(raw)?`${column.label} average — mean of available values in the labeled calendar window. Missing weeks do not become zero; the value count is shown.`:statistic;
 const week=String(column.weekKey||column.key||'').match(/^(\d{4})-(\d{1,2})(?::|$)/);
 const context=week?`${week[1]} Week ${week[2]}.`:'';
 return [definition,context,column.help].filter(Boolean).join(' ')||`${column.label} · ${typeof column.groupLabel==='string'?column.groupLabel:column.group||''}`;
}
export function csvDownload(name,columns,rows){const escape=v=>`"${String(v??'').replace(/^[\s]*[=+@-]/,"'$&").replaceAll('"','""')}"`;const content=[columns.map(c=>c.label),...rows.map(r=>columns.map(c=>c.exportValue?c.exportValue(r):c.value?c.value(r):r[c.key]))].map(r=>r.map(escape).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
export function average(history,metric,read){const values=history.map(h=>read(h,metric)).filter(Number.isFinite);return {value:values.length?values.reduce((a,b)=>a+b,0)/values.length:null,count:values.length};}
