import {GameSelector} from './GameSelector.jsx';
import {useState} from 'react';
import {PlayerName} from './shared.jsx';
import {Grip} from './newsWindows.jsx';
import {COLS,TABLE_TABS,list,players,sources,outlet,publication,clock,statusOf,evidenceOf,tone,catOf,sourceInventory,tabArticles,urgency,missingCounts,safeNewsUrl,wireOrder} from './newsCommandModel.js';
import {ROLE_CHAINS} from '../../scripts/news/role-chains.js';
import {inMatchups} from './playerWorkspace.js';
export function Empty({children}){return <div className="cc-empty">{children}</div>;}
export function Token({value}){return <span className={`cc-mono ${tone(String(value))}`}>{value??'—'}</span>;}
export function LeagueBadge({context}){const entries=[...context.owned.map(o=>({...o,label:'MINE'})),...context.available.map(o=>({...o,label:o.status==='W'?'WAIVERS':'FA'}))];return <span className={`cc-league-badge ${context.owned.length?'green':''}`} title={entries.length?entries.map(o=>`${o.leagueName}: ${o.label} at read · ${o.captureAgeVerified?clock(o.checkedAt):'capture age unverified'}${o.stale?' · stale loaded observation':''}${o.coverage?.partial?' · partial page coverage':''}`).join('\n'):context.connected?'Ownership unavailable; absence from a bounded pool is not ownership evidence':'Yahoo disconnected'}>{entries.length?entries.map(o=>`${o.label} · ${o.leagueName}`).join(' / '):'—'}</span>;}
export function SourceLink({source}){const url=safeNewsUrl(source.url);return <div className="cc-source-link"><div>{url?<a href={url} target="_blank" rel="noopener noreferrer">{outlet(source)} ↗</a>:<strong>{outlet(source)}</strong>}<small>{source.sourceType||'linked evidence'} · {source.accessLabel||source.access||'unverified'}</small><time>{publication(source)}</time></div>{(source.author||source.xHandle)&&<small>{[source.author,source.xHandle].filter(Boolean).join(' · ')}</small>}</div>;}
export function ReportBody({article,context,onOpen,season,scoring,filterTeam,compact=false}){
 if(!article)return <Empty>Select a report using ↗ in any window.</Empty>;const u=urgency(article),ps=players(article);
 return <div className={`cc-report ${compact?'compact':''}`}><div className="cc-badges"><span><Token value={evidenceOf(article)}/></span><span>{catOf(article)} · {article.eventType||'event not supplied'}</span><span className={article.publishedAt?'':'yellow'}>{article.publishedAt?article.freshness?.state==='stale'?'older report':'publication clock supplied':'publication age unknown'}</span></div>{!compact&&<h2>{article.headline}</h2>}
 <div className="cc-identities">{ps.map((p,i)=><span key={i}>{p.playerId||p.player_id?<PlayerName row={{...p,player_id:p.playerId||p.player_id,player_display_name:p.name,season,scoring}} onOpen={onOpen}/>:<b>{p.name}</b>} <button className="cc-team-chip" aria-label={`Filter team ${p.team}`} onClick={()=>filterTeam?.(p.team)}>{p.team}</button> <small>{p.position}</small></span>)}<LeagueBadge context={context(article)}/></div>
 <div className="cc-report-clock">{publication(article)} · source checked {clock(article.checkedAt)} · record updated {clock(article.updatedAt)}</div>
 {article.injury?.isInjuryRelated&&<div className="cc-facts">{[['Game status',article.injury.gameStatus],['Latest practice',article.injury.practiceStatus],['Body part',article.injury.bodyPart],['Expected return',article.injury.expectedReturn]].map(([k,v])=><div key={k}><small>{k}</small><b><Token value={v||'Unavailable'}/></b></div>)}</div>}
 <h3>Report</h3><p>{article.summary||'Summary not supplied. Open the source for the report.'}</p>{article.fantasyAnalysis&&<><h3>Fantasy context</h3><p>{article.fantasyAnalysis}</p></>}
 <h3>Linked evidence · {sources(article).length}</h3>{sources(article).map((s,i)=><SourceLink key={i} source={s}/>)}{!sources(article).length&&<p>No source link supplied.</p>}
 <details className="cc-availability"><summary>Supplied fields & limitations</summary><div>Urgency: {u?`${u.score}/5 · ${u.basis} · ${u.method} · ${clock(u.estimatedAt)}`:'not supplied'}</div><div>Confidence: {Number.isFinite(article.evidence?.confidence)?`${article.evidence.confidence}% · source corroboration, not an outcome probability`:'not supplied'}</div><div>affectedPlayers: {list(article.affectedPlayers).length?list(article.affectedPlayers).map(p=>`${p.name}: ${p.impact||p.relationship}`).join('; '):'not supplied'}</div><div>playerId: {ps.some(p=>p.playerId||p.player_id)?'supplied for linked identities':'not supplied'}</div><div>Report ID: <span className="cc-mono">{article.id}</span></div><div>Per-day practice grades: not supplied. Latest practice is not a Wednesday/Thursday/Friday history.</div></details>
 </div>;
}
export function TabStrip({label,tabs,value,onChange}){return <div className="cc-tabs" role="tablist" aria-label={label}>{tabs.map(([id,title,count],i)=><button key={id} role="tab" aria-selected={value===id} tabIndex={value===id?0:-1} onClick={()=>onChange(id)} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length;onChange(tabs[n][0]);e.currentTarget.parentElement.querySelectorAll('[role="tab"]')[n]?.focus();}}>{title}{count!=null&&<small>{count}</small>}</button>)}</div>;}
export function StatusTable({articles,allCount,context,layout,patch,expanded,toggle,inspect,source,setSource,schedule,dfsWeek,setDfsWeek,gameIds,setGameIds,scheduleState,bodyProps}){
 const [sort,setSort]=useState({key:null,desc:true});const gameScoped=articles.filter(a=>!schedule.length||players(a).some(p=>inMatchups({team:p.team},gameIds,schedule,false))),inventory=sourceInventory(gameScoped),scoped=gameScoped.filter(a=>source==='all'||sources(a).some(s=>outlet(s)===source));const rows=tabArticles(layout.tab,scoped,context),cols=TABLE_TABS[layout.tab][1].split(' ');
 const value=(a,k)=>{const p=players(a)[0]||{};return ({game:statusOf(a),name:p.name||'NFL news',pos:p.position,team:p.team,lg:[...context(a).owned,...context(a).available].map(o=>o.leagueName).join(' '),body:a.injury?.bodyPart,wed:'—',thu:'—',prac:a.injury?.practiceStatus,ev:evidenceOf(a),imp:a.fantasyImpact||a.impact,src:a.source||outlet(sources(a)[0]),chk:a.checkedAt,pub:a.publishedAt||a.publishedDate,cat:catOf(a),evType:a.eventType,headline:a.headline})[k]??'—';};
 const sorted=[...rows].sort((a,b)=>!sort.key?0:(String(value(a,sort.key)).localeCompare(String(value(b,sort.key)),undefined,{numeric:true}))*(sort.desc?-1:1));
 const grid=cols.map(k=>`${layout.colW[k]||COLS[k][1]}px`).join(' '),width=cols.reduce((n,k)=>n+(layout.colW[k]||COLS[k][1])+6,14)+24;
 const sourceRows=[...inventory].sort((a,b)=>!sort.key?0:(typeof a[{sname:'name',cites:'count'}[sort.key]||sort.key]==='number'?a[{cites:'count'}[sort.key]||sort.key]-b[{cites:'count'}[sort.key]||sort.key]:String(a[{sname:'name'}[sort.key]||sort.key]).localeCompare(String(b[{sname:'name'}[sort.key]||sort.key])))*(sort.desc?-1:1));
 return <><div className="cc-status-filters" hidden={!layout.filtersOpen}><button className="cc-disclosure" aria-expanded={layout.gamesOpen} onClick={()=>patch({gamesOpen:!layout.gamesOpen})}>{layout.gamesOpen?'▾':'▸'} Game selector · DFS week {dfsWeek} <small>team · position · status · league filters live in the top bar</small></button><div className="cc-status-pickers"><select aria-label="News source" value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{inventory.map(s=><option key={s.name}>{s.name}</option>)}</select><label>DFS WEEK <select aria-label="DFS week" value={dfsWeek} onChange={e=>{setDfsWeek(Number(e.target.value));setGameIds([]);}}>{Array.from({length:18},(_,i)=><option key={i} value={i+1}>Week {i+1}</option>)}</select></label></div>
 {layout.gamesOpen&&<GameSelector label="News games" games={schedule} selected={gameIds} onChange={setGameIds} compact={layout.density<1} empty={scheduleState.loading?'Reading schedule…':scheduleState.error?'Schedule unavailable · Status table unfiltered':'No sourced schedule for this week · Status table unfiltered'} details={g=>{const id=g.gameId||g.game_id,reports=articles.filter(a=>players(a).some(p=>inMatchups({team:p.team},[id],schedule,false)));return `${reports.length} reports · ${reports.filter(a=>['OUT','IR'].includes(statusOf(a))).length} OUT · ${reports.filter(a=>statusOf(a)==='QUES').length} Q`;}}/>}</div>
 <TabStrip label="Status table views" tabs={Object.entries(TABLE_TABS).map(([id,[label]])=>[id,label,id==='sources'?inventory.length:tabArticles(id,scoped,context).length])} value={layout.tab} onChange={tab=>{patch({tab});setSort({key:null,desc:true});}}/>
 <div className="cc-table-scroll"><div role="table" aria-label={`${TABLE_TABS[layout.tab][0]} status reports`} style={{minWidth:width}}><div role="row" className="cc-table-header" style={{gridTemplateColumns:grid}}>{cols.map(k=><div key={k} role="columnheader" aria-sort={sort.key===k?sort.desc?'descending':'ascending':'none'}><button title={`Sort ${COLS[k][0]}`} onClick={()=>setSort({key:k,desc:sort.key===k?!sort.desc:true})}>{COLS[k][0]} {sort.key===k?(sort.desc?'▾':'▴'):''}</button><Grip className="cc-col-grip" label={`Resize ${COLS[k][0]} column`} value={layout.colW[k]||COLS[k][1]} min={24} max={420} step={8} onChange={v=>patch({colW:{...layout.colW,[k]:v}})}/></div>)}</div>
 {layout.tab==='sources'?sourceRows.map(s=><div role="row" key={s.name} className="cc-table-row" style={{gridTemplateColumns:grid}} onClick={()=>{setSource(s.name);patch({tab:'all'});}}>{cols.map(k=><div role="cell" key={k}>{k==='sname'?<button>{s.name}</button>:k==='cites'?s.count:s[k]??'—'}</div>)}</div>):sorted.map(a=><div key={a.id}><div role="row" className={`cc-table-row ${expanded.has(a.id)?'expanded':''}`} style={{gridTemplateColumns:grid}} onClick={()=>toggle(a.id)}>{cols.map(k=><div role="cell" key={k} title={['wed','thu'].includes(k)?'Per-day practice grades not supplied':k==='prac'?'Latest returned practice grade; day not supplied':String(value(a,k))}>{k==='name'||k==='headline'?<button className={k==='name'?'cc-player-label':''} aria-label={`${k==='headline'?'Toggle headline':'Expand'} ${a.headline}`} aria-expanded={expanded.has(a.id)} onClick={e=>{e.stopPropagation();toggle(a.id);}}>{value(a,k)}</button>:k==='lg'?<LeagueBadge context={context(a)}/>:k==='chk'?<span className="cc-mono">{clock(a.checkedAt)}</span>:k==='pub'?<span className="cc-mono">{publication(a)}</span>:<span className={`${['game','pos','team','wed','thu','prac','ev','imp'].includes(k)?'cc-mono':''} ${tone(String(value(a,k)))}`}>{value(a,k)}</span>}</div>)}<button className="cc-inspect" aria-label={`Inspect ${a.headline}`} onClick={e=>{e.stopPropagation();inspect(a.id);}}>↗</button></div>{expanded.has(a.id)&&<div className="cc-inline"><div className="cc-inline-actions"><button onClick={()=>inspect(a.id)}>Open in Evidence desk ↗</button>{players(a)[0]?.team&&<button onClick={()=>bodyProps.filterTeam(players(a)[0].team)}>Filter {players(a)[0].team}</button>}</div><ReportBody article={a} context={context} {...bodyProps} compact/></div>}</div>)}
 </div>{layout.tab!=='sources'&&!rows.length&&<Empty>{layout.tab==='roster'&&!context({players:[]}).connected?'Yahoo league context unavailable':'No reports match this view. Missing coverage is not evidence of no news.'}</Empty>}</div>
 <footer className="cc-status-footer">{layout.tab==='sources'?inventory.length:rows.length} shown · {articles.length} of {allCount} in scope · DFS W{dfsWeek} · Fri = latest practiceStatus (day not supplied) · click a row to expand</footer></>;
}
export function Wire({articles,context,inspect,bodyProps,settings,setSettings}){
 const {chip,group,sort}=settings;const setChip=chip=>setSettings(s=>({...s,chip})),setGroup=group=>setSettings(s=>({...s,group})),setSort=sort=>setSettings(s=>({...s,sort}));const [expanded,setExpanded]=useState(new Set());const rows=wireOrder(articles,settings);const groups=new Map();for(const a of rows){const key=group==='team'?players(a)[0]?.team||'NFL':a.publishedDate||a.publishedAt?.slice(0,10)||'Date unknown';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(a);}
 return <><div className="cc-toolbar"><div className="cc-pills">{['all','injury','practice','role','news'].map(id=><button key={id} aria-pressed={chip===id} className={chip===id?'active':''} onClick={()=>setChip(id)}>{id==='all'?'All':id[0].toUpperCase()+id.slice(1)} {id==='all'?articles.length:articles.filter(a=>catOf(a)===id).length}</button>)}</div><div className="cc-segments">{['day','team'].map(id=><button key={id} className={group===id?'active':''} onClick={()=>setGroup(id)}>By {id}</button>)}</div><div className="cc-segments">{['published','checked'].map(id=><button key={id} className={sort===id?'active':''} onClick={()=>setSort(id)}>{id==='published'?'Published':'Checked'}</button>)}</div></div>
 <div className="cc-scroll">{[...groups].map(([key,entries])=><div key={key}><div className="cc-group-label">{key}<span>{entries.length}</span></div>{entries.map(a=><article className="cc-wire-row" key={a.id}><time>{sort==='checked'?clock(a.checkedAt):a.publishedAt?new Date(a.publishedAt).toLocaleTimeString('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'}):a.publishedDate?'date only':'—'}</time><div><button className="cc-wire-headline" aria-label={`Expand ${a.headline}`} aria-expanded={expanded.has(a.id)} onClick={()=>setExpanded(old=>{const n=new Set(old);return n.has(a.id)?new Set():new Set([a.id]);})}>{a.headline}</button><div className="cc-wire-meta">{players(a).map(p=>`${p.name} · ${p.team} ${p.position}`).join(' / ')} <Token value={statusOf(a)}/> · {a.source||outlet(sources(a)[0])} <Token value={evidenceOf(a)}/> <Token value={a.fantasyImpact||a.impact||'—'}/> <LeagueBadge context={context(a)}/></div>{expanded.has(a.id)&&<ReportBody article={a} context={context} {...bodyProps} compact/>}</div><button className="cc-inspect" aria-label={`Inspect ${a.headline}`} onClick={()=>inspect(a.id)}>↗</button></article>)}</div>)}{!rows.length&&<Empty>No reports match these filters.</Empty>}</div></>;
}
export function Evidence({article,articles,context,select,back,history,pinned,setPinned,bodyProps}){const index=articles.findIndex(a=>a.id===article?.id),opts=article&&index<0?[article,...articles]:articles;return <><div className="cc-evidence-controls"><button aria-label="Evidence back" disabled={!history.length} onClick={back}>↶</button><button aria-label="Previous evidence" disabled={!articles.length} onClick={()=>select(articles[(index-1+articles.length)%articles.length].id)}>◀</button><button aria-label="Next evidence" disabled={!articles.length} onClick={()=>select(articles[(index+1)%articles.length].id)}>▶</button><select aria-label="Evidence report" value={article?.id||''} onChange={e=>select(e.target.value)}><option value="" disabled>Select report</option>{opts.map(a=><option key={a.id} value={a.id}>{index<0&&a.id===article?.id?'Outside filters · ':''}{statusOf(a)} · {players(a)[0]?.name||'NFL'} — {a.headline}</option>)}</select><span className="cc-mono">{index+1} / {articles.length}</span><button aria-pressed={pinned} className={pinned?'active':''} onClick={()=>setPinned(!pinned)}>{pinned?'PINNED':'PIN'}</button></div><div className="cc-scroll"><ReportBody article={article} context={context} {...bodyProps}/>{article&&<div className="cc-related"><h3>Related reports</h3>{articles.filter(a=>a.id!==article.id&&players(a).some(p=>players(article).some(q=>p.team===q.team||p.name===q.name)||String(article.summary).includes(p.name))).map(a=><button key={a.id} onClick={()=>select(a.id)}>{a.headline}</button>)}</div>}</div></>;}
export function RoleBoard({articles,inspect,context}){
 const [filter,setFilter]=useState('all'),[open,setOpen]=useState(new Set());const ids=new Set(articles.map(a=>a.id));const supplied=articles.filter(a=>list(a.affectedPlayers).length).map(a=>({team:players(a)[0]?.team||'—',room:players(a)[0]?.position||'—',vacated:players(a).map(p=>[p.name,statusOf(a)]),next:list(a.affectedPlayers).map(p=>[p.name,p.relationship||'—']),basis:a.eventType||'REPORT',ev:evidenceOf(a),fact:a.headline,note:list(a.affectedPlayers).map(p=>p.impact).filter(Boolean).join(' · '),ids:[a.id],supplied:true}));const suppliedIds=new Set(supplied.flatMap(c=>c.ids));const chains=[...supplied,...ROLE_CHAINS.filter(c=>c.ids.some(id=>ids.has(id))&&!c.ids.some(id=>suppliedIds.has(id)))];const bucket=c=>c.basis==='PERFORMANCE'?'usage':c.basis==='DEPTH_CHART'?'starters':c.vacated.some(([,s])=>/OUT|IR/.test(s))?'vacated':'watch';const rows=chains.filter(c=>filter==='all'||bucket(c)===filter);
 return <><div className="cc-toolbar"><div className="cc-pills">{[['all','All rooms'],['vacated','Vacated'],['starters','Starters named'],['usage','Usage facts'],['watch','Watch']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label} {id==='all'?chains.length:chains.filter(c=>bucket(c)===id).length}</button>)}</div><small>vacated → next up · report prose, not projections</small></div><div className="cc-scroll"><div className="cc-role-grid cc-table-header"><span>Team</span><span>Room</span><span>Vacated / changed</span><span>Next up</span><span>Basis</span><span>What the report says</span></div>{rows.map((c,i)=>{const id=c.ids.find(k=>ids.has(k)),key=`${c.team}-${c.room}-${i}`;return <div key={key}><div className="cc-role-grid cc-role-row"><span className="cc-mono">{c.team}</span><span className="cc-mono">{c.room}</span><div>{c.vacated.map(([n,s])=><div key={n}><b>{n}</b> <Token value={s}/></div>)}</div><div>{c.next.map(([n,s])=>{const identities=articles.flatMap(players).filter(p=>p.name===n&&p.team===c.team&&p.position===c.room);const identity=identities[0];return <div key={n}><b>→ {n}</b> <Token value={s}/>{identity&&<LeagueBadge context={context({players:[identity]})}/>}</div>})}</div><span className="cc-mono">{c.basis}<br/><Token value={c.ev}/></span><button title={c.fact} aria-expanded={open.has(key)} onClick={()=>setOpen(old=>{const n=new Set(old);n.has(key)?n.delete(key):n.add(key);return n;})}>{c.fact}</button><button className="cc-inspect" aria-label={`Inspect role ${c.team} ${c.room}`} onClick={()=>inspect(id)}>↗</button></div>{open.has(key)&&<div className="cc-inline"><p>{c.note}</p><small>{c.supplied?'Supplied affectedPlayers':'Curated public writer role chain · editorial interpretation · 2026-10-02'} · linked reports establish the dated basis; no workload forecast is supplied.</small>{c.ids.filter(id=>ids.has(id)).map(id=><button key={id} onClick={()=>inspect(id)}>{articles.find(a=>a.id===id).headline} ↗</button>)}</div>}</div>;})}{!rows.length&&<Empty>No source-linked role chains in this scope. affectedPlayers not supplied where absent.</Empty>}</div></>;
}
export function FeedHealth({meta,articles,readAt,context,chooseSource}){const inventory=sourceInventory(articles),missing=missingCounts(articles),citations=articles.reduce((n,a)=>n+sources(a).length,0),urls=new Set(articles.flatMap(a=>sources(a).map(s=>safeNewsUrl(s.url)).filter(Boolean)));return <div className="cc-health-body cc-scroll"><div><dl>{[['state',meta?.state||'unavailable'],['live',String(meta?.live===true)],['coverage',meta?.coverage?.complete?'complete as reported':'partial / unverified'],['sources checked',clock(meta?.repository?.checkedAt||meta?.freshness?.sourceCheckedAt)],['repository updated',clock(meta?.repository?.updatedAt)],['cache fetched',clock(meta?.repository?.fetchedAt)],['latest exact pub',clock(meta?.freshness?.latestSourcePublishedAt)],['feed read',clock(readAt)],['exact citation clocks',`${articles.reduce((n,a)=>n+sources(a).filter(s=>s.publishedAt).length,0)} / ${citations}`],['undated reports',`${articles.filter(a=>!a.publishedAt).length} / ${articles.length}`],['revision',meta?.repository?.revision?.slice(0,12)||'Unavailable'],['scheduler verified',String(meta?.refresh?.schedulerVerified===true)],['yahoo context',context({players:[]}).connected?'authorized · partial observations':'unavailable']].map(([k,v])=><div key={k}><dt>{k}</dt><dd><Token value={v}/></dd></div>)}</dl><h3>Providers</h3>{list(meta?.sources).map((s,i)=><div className="cc-provider" key={s.id||i}><span title={s.message||s.coverage}>{s.name||s.id}</span><Token value={s.ready?'configured':'unavailable'}/></div>)}<h3>Not supplied in this snapshot</h3><p className="cc-mono cc-missing">{Object.entries(missing).map(([k,v])=><span key={k}>{k}: not supplied {v}/{articles.length}<br/></span>)}</p><details><summary>Coverage & clock methodology</summary><p>{meta?.message}</p><p>Refresh reads stored reports, not provider ingestion. Undated reports have unknown publication age. Source checks, publication, repository update and feed read are separate clocks.</p>{list(meta?.coverage?.limitations).map((s,i)=><p key={i}>{s}</p>)}<p>Yahoo observations stay in memory. Absence from a bounded pool does not prove ownership.</p></details></div><div><h3>Outlet · click to scope the table</h3><p className="cc-mono">{inventory.length} outlets · {citations} citations · {urls.size} URLs</p>{inventory.slice(0,14).map(s=><button className="cc-outlet" key={s.name} onClick={()=>chooseSource(s.name)}><span>{s.name}</span><i style={{width:`${s.count/(inventory[0]?.count||1)*64}px`}}/><small>{s.count}</small></button>)}</div></div>;}
