import { nflTeam } from './playerWorkspace.js';
export const NEWS_LAYOUT_KEY = 'bowser:news-cc:layout:v2';
export const NEWS_PANES = { status:{title:'Status table'},wire:{title:'Wire'},evidence:{title:'Evidence desk'},role:{title:'Role board'},health:{title:'Feed health & sources'},league:{title:'League desk'} };
export const CENTER = ['wire','evidence','role','health'];
export const HOURS = [24,72,168,720];
export const COLS = {game:['Status',50],name:['Player',130],pos:['Pos',30],team:['Team',38],lg:['League',86],body:['Body',78],wed:['Wed',30],thu:['Thu',30],prac:['Fri',30],ev:['Evid.',42],imp:['Impact',44],src:['Source',100],chk:['Checked',66],pub:['Published',92],cat:['Category',64],evType:['Event',92],headline:['Headline',220],sname:['Outlet',180],cites:['Cites',44],urls:['URLs',40],domain:['Domain',170],access:['Access',180]};
export const TABLE_TABS = {injuries:['Injuries','game name pos team lg body wed thu prac ev imp src chk'],practice:['Practice','name pos team lg wed thu prac game body imp src chk'],role:['Role','name pos team lg evType headline ev src pub'],all:['All','pub name team pos lg cat headline ev imp chk'],roster:['My roster','lg game name pos team prac body headline imp'],sources:['Sources','sname cites urls domain access']};
export const list = v => Array.isArray(v) ? v : [];
export const text = v => typeof v === 'string' ? v : '';
export const clamp = (v,min,max,fallback) => typeof v === 'number' && Number.isFinite(v) ? Math.max(min,Math.min(max,v)) : fallback;
export function defaultNewsLayout() { const w=typeof window==='undefined'?1920:window.innerWidth; return {version:2,leftW:Math.min(600,Math.max(420,w*.34)),leftOpen:true,leftVisible:true,pfOpen:false,pfW:Math.min(620,Math.max(420,w*.36)),show:Object.fromEntries(CENTER.map(k=>[k,true])),order:[...CENTER],arrange:'tiles',maximized:null,colFr:[1,1],rowFr:[1,1],filtersOpen:true,gamesOpen:true,tab:'injuries',ts:Object.fromEntries(Object.keys(NEWS_PANES).map(k=>[k,1])),pageScale:1,density:1,colW:{}}; }
/** Strict preference projection: neither unknown keys nor response bodies can survive storage. */
export function validateNewsLayout(v) {
 const d=defaultNewsLayout(); if(v?.version!==2)return d;
 const order=[...new Set(list(v.order).filter(k=>CENTER.includes(k)))];
 return {version:2,leftW:clamp(v.leftW,380,1100,d.leftW),leftOpen:v.leftOpen!==false,leftVisible:v.leftVisible!==false,pfOpen:v.pfOpen===true,pfW:clamp(v.pfW,400,1100,d.pfW),show:Object.fromEntries(CENTER.map(k=>[k,v.show?.[k]!==false])),order:[...order,...CENTER.filter(k=>!order.includes(k))],arrange:['tiles','columns','stack'].includes(v.arrange)?v.arrange:'tiles',maximized:CENTER.includes(v.maximized)?v.maximized:null,colFr:Array.from({length:4},(_,i)=>clamp(v.colFr?.[i],.3,5,1)),rowFr:Array.from({length:4},(_,i)=>clamp(v.rowFr?.[i],.3,5,1)),filtersOpen:v.filtersOpen!==false,gamesOpen:v.gamesOpen!==false,tab:Object.hasOwn(TABLE_TABS,v.tab)?v.tab:'injuries',ts:Object.fromEntries(Object.keys(NEWS_PANES).map(k=>[k,clamp(v.ts?.[k],.8,1.5,1)])),pageScale:clamp(v.pageScale,.8,1.4,1),density:[.84,1,1.2].includes(v.density)?v.density:1,colW:Object.fromEntries(Object.entries(COLS).filter(([k])=>Number.isFinite(v.colW?.[k])).map(([k])=>[k,clamp(v.colW[k],24,420,COLS[k][1])]))};
}
export function safeNewsUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
export const players = a=>list(a?.players).filter(p=>p&&text(p.name));
export const sources = a=>list(a?.sources).filter(s=>s&&typeof s==='object');
export const outlet = s=>text(s?.sourceName||s?.name)||'Source unavailable';
export const categories = a=>[...new Set([a.category,...list(a.categories)].filter(Boolean))];
export const catOf = a=>categories(a).includes('playing_time')||['COACH_COMMENT','PERFORMANCE'].includes(a.eventType)?'role':categories(a).includes('injury')?'injury':categories(a).includes('practice')?'practice':'news';
export const articleTime = a=>Date.parse(a?.publishedAt)||Date.parse(a?.publishedDate)||0;
export function clock(v){return v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})+' CT':'Unavailable';}
export function publication(a){return a?.publishedAt?clock(a.publishedAt):a?.publishedDate?`${a.publishedDate} · time/TZ unknown`:a?.publishedAtRaw||'Publication unknown';}
export function statusOf(a){const s=text(a?.injury?.gameStatus).toUpperCase();if(s.includes('OUT'))return 'OUT';if(s.includes('QUESTION'))return 'QUES';if(s.includes('DOUBT'))return 'DBT';if(s.includes('PUP'))return 'PUP';if(s==='IR'||s.includes('RESERVE'))return 'IR';if(s.includes('CLEAR')||s==='NONE'||s==='NO DESIGNATION')return 'CLR';return s||(a?.injury?.isInjuryRelated?'CLR':'—');}
export function evidenceOf(a){return text(a.status)||text(a.evidence?.label)||'not supplied';}
export const tone = s=>/\b(OUT|DNP|HIGH)\b/i.test(s)?'red':/\b(CLR|FP|FULL|CONFIRMED|START|current)\b/i.test(s)?'green':/\b(QUES|LP|LIMIT|REPORTED|MED|unknown|unavailable)\b/i.test(s)?'yellow':'';
export function urgency(a){const v=a?.urgency;return Number.isInteger(v?.score)&&v.score>=1&&v.score<=5&&text(v.basis)&&text(v.method)&&Number.isFinite(Date.parse(v.estimatedAt))?v:null;}
export function sourceInventory(articles){const m=new Map();for(const a of articles)for(const s of sources(a)){const name=outlet(s),entry=m.get(name)||{name,count:0,urls:new Set(),domain:'—',access:new Set()};entry.count++;const url=safeNewsUrl(s.url);if(url){entry.urls.add(url);entry.domain=new URL(url).hostname;}entry.access.add(s.accessLabel||s.access||'unverified');m.set(name,entry);}return [...m.values()].sort((a,b)=>b.count-a.count).map(s=>({...s,urls:s.urls.size,access:[...s.access].join(' · ')}));}
export function matchesGlobal(a,filters,context){
 const ps=players(a),query=filters.search.trim().toLowerCase();
 return (!query||[a.headline,a.summary,a.fantasyAnalysis,...ps.flatMap(p=>[p.name,p.team,p.position])].join(' ').toLowerCase().includes(query))&&(!filters.teams.length||ps.some(p=>filters.teams.includes(nflTeam(p.team))))&&(!filters.pos.length||ps.some(p=>filters.pos.includes(p.position)))&&(!filters.status.length||filters.status.includes(statusOf(a)))&&(!filters.leagues.length||filters.leagues.some(k=>k==='mine'?context.owned.length:k==='available'?context.available.length:k.startsWith('mine:')?context.owned.some(o=>o.leagueKey===k.slice(5)):k.startsWith('free:')?context.available.some(o=>o.leagueKey===k.slice(5)):[...context.owned,...context.available].some(o=>o.leagueKey===k)));
}
export function tabArticles(id,articles,context){return articles.filter(a=>id==='injuries'?a.injury?.isInjuryRelated===true&&a.status==='CONFIRMED':id==='practice'?categories(a).includes('practice'):id==='role'?catOf(a)==='role':id==='roster'?context(a).relevant:true);}
export function missingCounts(rows){return {urgency:rows.filter(a=>!urgency(a)).length,confidence:rows.filter(a=>!Number.isFinite(a.evidence?.confidence)).length,affectedPlayers:rows.filter(a=>!list(a.affectedPlayers).length).length,playerId:rows.filter(a=>!players(a).some(p=>p.playerId||p.player_id)).length,'per-day practice grades':rows.length};}

export function wireOrder(articles,{chip,sort}){return articles.filter(a=>chip==='all'||catOf(a)===chip).sort((a,b)=>sort==='checked'?(Date.parse(b.checkedAt)||0)-(Date.parse(a.checkedAt)||0):articleTime(b)-articleTime(a));}

const TEAMS='ARI ATL BAL BUF CAR CHI CIN CLE DAL DEN DET GB HOU IND JAX KC LA LAC LV MIA MIN NE NO NYG NYJ PHI PIT SEA SF TB TEN WAS'.split(' ');
/** Public scope preferences only; a bounded league ordinal conveys no Yahoo key or payload. */
export function encodeNewsFilters(filters,leagueKeys=[]){const raw=filters.leagues[0]||'',mode=raw.startsWith('mine:')?'mine-league':raw.startsWith('free:')?'free-league':['mine','available'].includes(raw)?raw:'all';return {search:String(filters.search||'').slice(0,200),teams:filters.teams.filter(v=>TEAMS.includes(v)),pos:filters.pos.filter(v=>['QB','RB','WR','TE','K','DEF'].includes(v)),status:filters.status.filter(v=>['OUT','QUES','DBT','IR','PUP','CLR'].includes(v)),league:{mode,index:mode.endsWith('-league')?leagueKeys.indexOf(raw.slice(5)):-1}};}
export function decodeNewsFilters(value,leagueKeys=[]){if(!value||typeof value!=='object'||typeof value.search!=='string'||value.search.length>200)return null;for(const [k,allow] of [['teams',TEAMS],['pos',['QB','RB','WR','TE','K','DEF']],['status',['OUT','QUES','DBT','IR','PUP','CLR']]])if(!Array.isArray(value[k])||value[k].length>allow.length||value[k].some(v=>!allow.includes(v)))return null;const mode=value.league?.mode,index=value.league?.index;if(!['all','mine','available','mine-league','free-league'].includes(mode))return null;if(mode.endsWith('-league')&&(!Number.isInteger(index)||index<0||index>31||!leagueKeys[index]))return null;return {search:value.search,teams:[...new Set(value.teams)],pos:[...new Set(value.pos)],status:[...new Set(value.status)],leagues:mode==='all'?[]:mode==='mine'||mode==='available'?[mode]:[`${mode==='mine-league'?'mine':'free'}:${leagueKeys[index]}`]};}
