import {useState} from 'react';
import {newsLeagueDeskContext,newsPlayerLeagueContext} from './fantasyNewsContext.js';
import {list,players,clock,publication,catOf,statusOf,tone,evidenceOf} from './newsCommandModel.js';
import {publicIdentityKey} from './playerIdentity.js';
import {Empty,Token,TabStrip} from './newsCommandViews.jsx';
const benchSlot=s=>['BN','IR','IR+'].includes(s);
const shortName=n=>{const words=n.split(' ');return words.length>1?`${words[0][0]}. ${words.slice(1).join(' ')}`:n;};
export function LeagueDesk({yahoo,season,now,articles,inspect,matchPlayer}){
 const scope=newsLeagueDeskContext(yahoo,season,{now});const [leagueKey,setLeagueKey]=useState(''),[view,setView]=useState('matchup'),[bench,setBench]=useState(false),[pos,setPos]=useState('All'),[expanded,setExpanded]=useState(new Set());
 if(!scope.connected)return <Empty><b>Yahoo not connected</b><p>Connect Yahoo to see your leagues, matchups, rosters and affirmative free-agent observations.</p><a href="#/yahoo">Open Yahoo Connection ↗</a><p>No sample leagues or rosters are substituted.</p></Empty>;
 const league=scope.leagues.find(l=>l.key===leagueKey)||scope.leagues[0],teams=scope.teams.filter(t=>t.leagueKey===league?.key),team=teams[0],dashboard=team?.dashboard;
 const hits=p=>articles.filter(a=>players(a).some(q=>publicIdentityKey(p)&&publicIdentityKey(p)===publicIdentityKey(q)));
 const trusted=(p,type)=>newsPlayerLeagueContext(p,yahoo,season,{now})[type].some(o=>o.leagueKey===league?.key&&o.player.key===p.key);
 const rawRoster=t=>list(t?.dashboard?.roster?.players);
 const roster=t=>rawRoster(t).filter(p=>trusted(p,'owned'));
 const status=p=>hits(p)[0]?statusOf(hits(p)[0]):'—';
 const matchups=dashboard&&!dashboard.errors?.scoreboard?list(dashboard.scoreboard?.matchups):[],matchup=matchups.find(m=>list(m.teams).some(t=>t.key===team?.key)),opponent=list(matchup?.teams).find(t=>t.key!==team?.key),ownScore=list(matchup?.teams).find(t=>t.key===team?.key),opponentTeam=teams.find(t=>t.key===opponent?.key);
 const settings=dashboard&&!dashboard.errors?.settings?dashboard.settings:null;
 const slots=list(settings?.rosterPositions).filter(r=>!benchSlot(r.position)&&Number.isInteger(r.count)&&r.count>0&&r.count<=10).flatMap(r=>Array.from({length:r.count},()=>r.position)).slice(0,30);
 const actualSlots=slots.length?slots:rawRoster(team).filter(p=>!benchSlot(p.slot)).map(p=>p.slot);
 const inSlot=(t,slot,index)=>{const p=rawRoster(t).filter(p=>p.slot===slot)[actualSlots.slice(0,index).filter(s=>s===slot).length];return p&&!trusted(p,'owned')?{name:'Player identity unavailable',slot,unknown:true}:p;};
 const pool=new Map();for(const t of teams)if(!t.research?.errors?.availability)for(const p of list(t.research?.availability?.players))if(trusted(p,'available')&&matchPlayer(p)&&(pos==='All'||p.position===pos))pool.set(p.key,p);
 const impact=a=>({HIGH:3,MEDIUM:2,LOW:1}[a?.fantasyImpact]||0),poolRows=[...pool.values()].sort((a,b)=>impact(hits(b)[0])-impact(hits(a)[0])||hits(b).length-hits(a).length||a.name.localeCompare(b.name));
 const ownHits=teams.flatMap(t=>roster(t).filter(matchPlayer).flatMap(p=>hits(p).map(a=>({p,a,t}))));
 const managers=new Map();for(const m of matchups)for(const t of list(m.teams))managers.set(t.key,t);for(const t of teams)managers.set(t.key,{...managers.get(t.key),...t});
 const person=(p,known=false)=>p?<div className={!matchPlayer(p)?'cc-dimmed':''}><button className="cc-league-player" disabled={!hits(p).length} onClick={()=>inspect(hits(p)[0].id)}>{p.name}</button><small>{p.team} {p.position}</small>{hits(p)[0]&&<button className="cc-hit" title={hits(p)[0].headline} onClick={()=>inspect(hits(p)[0].id)}>{hits(p)[0].headline}</button>}</div>:known?<div className="red"><b>empty slot</b><small>open slot · fill before lock</small></div>:<span className="cc-muted">Unavailable</span>;
 return <><div className="cc-league-tabs" role="tablist" aria-label="Yahoo leagues">{scope.leagues.map(l=>{const ts=scope.teams.filter(t=>t.leagueKey===l.key),ps=ts.flatMap(t=>list(t.dashboard?.roster?.players)),owned=ps.filter(p=>newsPlayerLeagueContext(p,yahoo,season,{now}).owned.some(o=>o.leagueKey===l.key));return <button key={l.key} role="tab" aria-selected={l.key===league?.key} onClick={()=>{setLeagueKey(l.key);setExpanded(new Set());}}><b>{l.name}</b><small>{l.numTeams?`${l.numTeams}-tm`:'Team count unavailable'}</small><span>{owned.filter(p=>status(p)==='OUT').length} OUT · {owned.filter(p=>status(p)==='QUES').length} Q · {owned.filter(p=>hits(p).length).length} hits</span></button>})}</div>
 <div className="cc-league-summary"><b>{team?.name||'No authorized team returned'}</b><span>Week {dashboard?.week||'—'} · Yahoo read {clock(dashboard?.checkedAt)}</span><small>Loaded observations · confirm in Yahoo · partial league coverage</small></div>
 <TabStrip label="League desk views" tabs={[["matchup","Matchup",actualSlots.length],["rosters","Rosters",managers.size],["free","Free agents",pool.size],["news","News hits",ownHits.length]]} value={view} onChange={setView}/>
 <div className="cc-scroll">
 {view==='matchup'&&<><div className="cc-league-match-title"><b>{team?.name||'Your team'}</b><span><Token value={ownScore?.points??'—'}/> – <Token value={opponent?.points??'—'}/></span><b>{opponent?.name||'Opponent unavailable'}</b></div><label className="cc-check"><input type="checkbox" checked={bench} onChange={e=>setBench(e.target.checked)}/> Include bench & IR</label><div className="cc-match-row cc-table-header"><span>Slot</span><span>Mine · news</span><span>Status</span><span>Opponent · news</span><span>Status</span></div>{actualSlots.map((slot,i)=>{const mine=inSlot(team,slot,i),other=inSlot(opponentTeam,slot,i);return <div className="cc-match-row" key={`${slot}-${i}`}><span className="cc-mono">{slot}</span>{person(mine,Boolean(dashboard?.roster&&slots.length))}<Token value={mine?status(mine):'—'}/>{person(other,Boolean(opponentTeam?.dashboard&&slots.length))}<Token value={other?status(other):'—'}/></div>})}{bench&&roster(team).filter(p=>benchSlot(p.slot)).map(p=><div className="cc-match-row cc-bench-row" key={p.key}><span className="cc-mono">{p.slot}</span>{person(p)}<Token value={status(p)}/><span>—</span><span>—</span></div>)}{!actualSlots.length&&<Empty>No starting slots or roster rows returned.</Empty>}<p className="cc-limitation">Status tokens come from the public feed, not Yahoo’s badge. Opponent player rosters are unavailable unless already returned for an authorized team. Missing roster responses are not empty slots.</p></>}
 {view==='rosters'&&<><p className="cc-limitation">Only your authorized teams’ loaded rosters are available. Other managers’ roster details are not supplied.</p><div className="cc-roster-matrix" style={{minWidth:Math.max(560,160+actualSlots.length*62),gridTemplateColumns:`minmax(130px,1.3fr) repeat(${Math.max(1,actualSlots.length)},minmax(56px,1fr)) 34px`}}><div className="cc-matrix-heading">Manager</div>{(actualSlots.length?actualSlots:['Roster']).map((s,i)=><div className="cc-matrix-heading" key={i}>{s}</div>)}<div className="cc-matrix-heading">Hits</div>{[...managers.values()].map(t=>{const own=teams.find(v=>v.key===t.key),ps=roster(own);return <div className="cc-matrix-manager" key={t.key}><button className={own?'green':''} aria-expanded={expanded.has(t.key)} onClick={()=>setExpanded(old=>{const n=new Set(old);n.has(t.key)?n.delete(t.key):n.add(t.key);return n;})}>{t.name}{own?' · you':t.key===opponent?.key?' · opp':''}</button>{(actualSlots.length?actualSlots:['Roster']).map((s,i)=>{const p=inSlot(own,s,i);return <div key={i} className={`cc-matrix-cell ${p?tone(status(p)):own?.dashboard&&slots.length?'red':''} ${p&&!matchPlayer(p)?'cc-dimmed':''}`}>{p?<button title={`${p.name} · ${status(p)}`} disabled={!hits(p).length} onClick={()=>inspect(hits(p)[0].id)}><i/>{shortName(p.name)}</button>:own?.dashboard&&slots.length?'empty':'—'}</div>})}<span className="cc-mono">{own?ps.filter(p=>hits(p).length).length:'—'}</span>{expanded.has(t.key)&&<div className="cc-matrix-bench">{own?ps.filter(p=>benchSlot(p.slot)).map(p=><button key={p.key} disabled={!hits(p).length} onClick={()=>inspect(hits(p)[0].id)}>{p.slot} · {p.name} <Token value={status(p)}/></button>):'Roster unavailable for this manager.'}</div>}</div>})}</div></>}
 {view==='free'&&<><div className="cc-toolbar"><select aria-label="Free agent position" value={pos} onChange={e=>setPos(e.target.value)}>{['All','QB','RB','WR','TE','K','DEF'].map(v=><option key={v}>{v}</option>)}</select><button disabled={!team||yahoo.researchBusy?.[team?.key]||!yahoo.loadResearch} onClick={()=>yahoo.loadResearch(team.key,{include:'availability',availabilityStatus:'FA',availabilityStart:0})}>Read free agents</button>{teams.some(t=>Number.isInteger(t.research?.availability?.nextStart))&&<button disabled={!yahoo.loadResearch} onClick={()=>{const t=teams.find(t=>Number.isInteger(t.research?.availability?.nextStart));yahoo.loadResearch(t.key,{include:'availability',availabilityStatus:t.research.availability.status,availabilityStart:t.research.availability.nextStart});}}>Read next page</button>}</div><div className="cc-fa-table"><div className="cc-fa-row cc-table-header">{['Available player','Pos','Team','Avail','Status','Fri','Latest report','Evid.','Impact','↗'].map(v=><span key={v}>{v}</span>)}</div>{poolRows.map(p=>{const news=hits(p),observation=newsPlayerLeagueContext(p,yahoo,season,{now}).available.find(o=>o.leagueKey===league.key);return <div className="cc-fa-row" key={p.key}><b>{p.name}</b><span>{p.position}</span><span>{p.team}</span><span title={`Read ${clock(observation?.checkedAt)} · ${observation?.captureAgeVerified?'loaded observation':'capture age unverified'}`}>{observation?.status||'—'}</span><Token value={status(p)}/><Token value={news[0]?.injury?.practiceStatus||'—'}/><button disabled={!news.length} onClick={()=>inspect(news[0].id)}>{news[0]?.headline||'No report returned'}</button><Token value={news[0]?evidenceOf(news[0]):'—'}/><Token value={news[0]?.fantasyImpact||'—'}/><button aria-label={`Inspect free agent ${p.name}`} disabled={!news.length} onClick={()=>inspect(news[0].id)}>↗</button></div>})}</div>{!pool.size&&<Empty>No affirmative free-agent observations loaded for these filters.</Empty>}<p className="cc-limitation">Bounded Yahoo pool · absence does not imply owned. Nothing here is an add recommendation. FAAB remaining: {ownScore?.faabBalance??'unavailable'} · waiver rule: {settings?.waiverType||'unavailable'}. Fri means latest practiceStatus; per-day grades not supplied.</p></>}
 {view==='news'&&<>{teams.map(t=>{const entries=ownHits.filter(h=>h.t.key===t.key);if(!entries.length)return null;return <div key={t.key}><div className="cc-group-label">{t.name}<span>{entries.length} hits</span></div>{entries.map(({p,a})=><div className="cc-league-news" key={`${p.key}-${a.id}`}><b>{p.name}</b><small>{p.slot} · {catOf(a)} · <Token value={statusOf(a)}/></small><button onClick={()=>inspect(a.id)}>{a.headline} ↗</button><time>{publication(a)}</time></div>)}</div>})}{!ownHits.length&&<Empty>No public news hits matched your loaded roster identities.</Empty>}</>}
 </div></>;
}
