import {useEffect,useRef,useState} from 'react';
import {CENTER,HOURS,NEWS_PANES,NEWS_LAYOUT_KEY,defaultNewsLayout,validateNewsLayout} from './newsCommandModel.js';
const paneWindows=new Map();
export function closeFantasyNewsWindows(){const ids=[...paneWindows.keys()];for(const child of paneWindows.values()){try{child.close();}catch{/* already closed */}}paneWindows.clear();if(ids.length)window.dispatchEvent(new CustomEvent('bowser-fantasy-news-windows-closed',{detail:ids}));}
export function routeOptions(){const q=new URLSearchParams(window.location.hash.split('?')[1]||'');const aliases={feed:'status',roles:'role',player:'league',sources:'health',acquisition:'league'};const pane=aliases[q.get('pane')]||q.get('pane');return {popout:q.get('popout')==='1'&&Object.hasOwn(NEWS_PANES,pane),pane,hours:HOURS.includes(Number(q.get('hours')))?Number(q.get('hours')):168,article:(q.get('article')||'').slice(0,200)};}
export function useNewsLayout(popout){const [layout,set]=useState(()=>{try{return popout?defaultNewsLayout():validateNewsLayout(JSON.parse(localStorage.getItem(NEWS_LAYOUT_KEY)));}catch{return defaultNewsLayout();}}),[error,setError]=useState(false);useEffect(()=>{if(popout)return;try{localStorage.setItem(NEWS_LAYOUT_KEY,JSON.stringify(validateNewsLayout(layout)));setError(false);}catch{setError(true);}},[layout,popout]);return [layout,next=>set(old=>validateNewsLayout(typeof next==='function'?next(old):next)),error];}
/** Only public report IDs and validated scope preferences cross registered window boundaries. */
export function useNewsWindows({route,articleId,hours,setHours,externalSelect,account,connected,filterScopeKey,filterMessage,acceptFilters}){
 const [states,setStates]=useState({}),[notice,setNotice]=useState('');const scopeReady=useRef(!route.popout),pendingFilters=useRef(null);const latest=useRef({articleId,hours,externalSelect,filterMessage,acceptFilters});latest.current={articleId,hours,externalSelect,filterMessage,acceptFilters};
 const send=child=>{try{child.postMessage({type:'bowser-fantasy-news-selection',articleId:latest.current.articleId||'',hours:latest.current.hours},window.location.origin);child.postMessage({type:'bowser-fantasy-news-filters',filters:latest.current.filterMessage},window.location.origin);}catch{/* independently reads public feed */}};
 const dock=id=>{try{paneWindows.get(id)?.close();}catch{/* already closed */}paneWindows.delete(id);setStates(s=>({...s,[id]:'closed'}));};
 const pop=id=>{const existing=paneWindows.get(id);try{if(existing&&!existing.closed){existing.focus();send(existing);return;}}catch{paneWindows.delete(id);}const url=new URL(window.location.href);url.hash=`/fantasy-news?${new URLSearchParams({pane:id,popout:'1',hours:latest.current.hours,...(latest.current.articleId?{article:latest.current.articleId}:{})})}`;let child;try{child=window.open(url.href,`bowser-fantasy-news-${id}`,'popup,width=900,height=800,resizable=yes,scrollbars=yes');}catch{child=null;}if(!child){setNotice(`The browser blocked ${NEWS_PANES[id].title}. Allow popups or use this workspace.`);return;}paneWindows.set(id,child);setStates(s=>({...s,[id]:'open'}));};
 useEffect(()=>{const check=()=>setStates(old=>{const next={...old};for(const [id,child] of paneWindows){try{if(child.closed)paneWindows.delete(id);}catch{paneWindows.delete(id);}}for(const id of Object.keys(next))next[id]=paneWindows.has(id)?'open':'closed';return Object.keys(next).every(k=>next[k]===old[k])?old:next;});const timer=setInterval(check,1000);window.addEventListener('bowser-fantasy-news-windows-closed',check);return()=>{clearInterval(timer);window.removeEventListener('bowser-fantasy-news-windows-closed',check);};},[]);
 const filterKey=JSON.stringify(filterMessage);
 useEffect(()=>{if(!route.popout){for(const child of paneWindows.values())try{child.postMessage({type:'bowser-fantasy-news-selection',articleId:latest.current.articleId||'',hours:latest.current.hours},window.location.origin);}catch{/* closed */}}},[articleId,hours,route]);
 useEffect(()=>{if(!route.popout){for(const child of paneWindows.values())try{child.postMessage({type:'bowser-fantasy-news-filters',filters:latest.current.filterMessage},window.location.origin);}catch{/* closed */}}else if(scopeReady.current&&!pendingFilters.current)try{window.opener?.postMessage({type:'bowser-fantasy-news-filters',pane:route.pane,filters:latest.current.filterMessage},window.location.origin);}catch{/* no opener */}},[route,filterKey]);
 useEffect(()=>{if(pendingFilters.current&&latest.current.acceptFilters(pendingFilters.current)){pendingFilters.current=null;scopeReady.current=true;}},[filterScopeKey]);
 useEffect(()=>{const receive=e=>{if(e.origin!==window.location.origin||!e.data||typeof e.data!=='object')return;if(route.popout){if(e.source!==window.opener)return;if(e.data.type==='bowser-fantasy-news-filters'){scopeReady.current=false;pendingFilters.current=e.data.filters;if(latest.current.acceptFilters(e.data.filters)){pendingFilters.current=null;scopeReady.current=true;}return;}if(e.data.type!=='bowser-fantasy-news-selection')return;if(typeof e.data.articleId==='string'&&e.data.articleId.length<=200)latest.current.externalSelect(e.data.articleId);if(HOURS.includes(e.data.hours))setHours(e.data.hours);}else{const id=[...paneWindows].find(([,w])=>w===e.source)?.[0];if(!id||e.data.pane!==id)return;if(e.data.type==='bowser-fantasy-news-filters'){latest.current.acceptFilters(e.data.filters);return;}if(e.data.type==='bowser-fantasy-news-ready')send(e.source);if(['bowser-fantasy-news-dock','bowser-fantasy-news-closed'].includes(e.data.type))dock(id);}};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[route,setHours]);
 const previous=useRef({account,connected});useEffect(()=>{if(previous.current.account!==account||previous.current.connected&&!connected)closeFantasyNewsWindows();previous.current={account,connected};},[account,connected]);
 useEffect(()=>{if(!route.popout){window.addEventListener('pagehide',closeFantasyNewsWindows);return()=>window.removeEventListener('pagehide',closeFantasyNewsWindows);}const title=document.title;document.title=`${NEWS_PANES[route.pane].title} · Bowser Fantasy News`;const notify=type=>{try{window.opener?.postMessage({type,pane:route.pane},window.location.origin);}catch{/* no opener */}};notify('bowser-fantasy-news-ready');const close=()=>notify('bowser-fantasy-news-closed');window.addEventListener('pagehide',close);return()=>{document.title=title;window.removeEventListener('pagehide',close);};},[route]);
 const returnToDesk=()=>{if(window.opener&&!window.opener.closed){window.opener.postMessage({type:'bowser-fantasy-news-dock',pane:route.pane},window.location.origin);window.close();}else window.location.hash='/fantasy-news';};
 return {states,notice,setNotice,pop,dock,returnToDesk};
}
export function Grip({label,value,min,max,onChange,axis='x',reverse=false,step=20,className=''}){
 const stop=useRef(null);useEffect(()=>()=>stop.current?.(),[]);
 const begin=e=>{e.preventDefault();e.stopPropagation();stop.current?.();const start=axis==='x'?e.clientX:e.clientY;const move=event=>onChange(Math.max(min,Math.min(max,value+((axis==='x'?event.clientX:event.clientY)-start)*(reverse?-1:1))));const end=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',end);document.removeEventListener('pointercancel',end);window.removeEventListener('blur',end);stop.current=null;};stop.current=end;document.addEventListener('pointermove',move);document.addEventListener('pointerup',end);document.addEventListener('pointercancel',end);window.addEventListener('blur',end);};
 return <div className={`cc-grip ${axis==='y'?'horizontal':''} ${className}`} role="separator" aria-label={label} aria-orientation={axis==='x'?'vertical':'horizontal'} aria-valuemin={min} aria-valuemax={max} aria-valuenow={Math.round(value*100)/100} tabIndex={0} onPointerDown={begin} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();onChange(e.key==='Home'?min:e.key==='End'?max:Math.max(min,Math.min(max,value+(['ArrowRight','ArrowDown'].includes(e.key)?step:-step)*(reverse?-1:1))));}}/>;
}
export function WindowFrame({id,layout,patch,children,subtitle,controls,windows,popout=false,onMove}){
 const title=NEWS_PANES[id].title,t=layout.ts[id];
 const close=()=>{windows.dock(id);patch(id==='status'?{leftVisible:false}:id==='league'?{pfOpen:false}:{show:{...layout.show,[id]:false},maximized:layout.maximized===id?null:layout.maximized});};
 return <section className={`cc-window cc-${id}`} aria-label={title} style={{'--t':t,'--k':Math.max(.5,2-t),'--r':.6+.4*t}}>
 <header className="cc-title"><b>{title}</b><span className="cc-subtitle">{subtitle}</span><div className="cc-title-actions">{controls}<button aria-label={`Decrease ${title} text`} disabled={t<=.8} onClick={()=>patch({ts:{...layout.ts,[id]:Math.round((t-.1)*10)/10}})}>A−</button><button aria-label={`Increase ${title} text`} disabled={t>=1.5} onClick={()=>patch({ts:{...layout.ts,[id]:Math.round((t+.1)*10)/10}})}>A+</button>{!popout&&<><span className="cc-title-sep"/>{CENTER.includes(id)&&<><button aria-label={`Move ${title} left`} onClick={()=>onMove(id,-1)}>←</button><button aria-label={`Move ${title} right`} onClick={()=>onMove(id,1)}>→</button><button aria-label={`${layout.maximized===id?'Restore':'Maximize'} ${title}`} onClick={()=>patch({maximized:layout.maximized===id?null:id})}>⤢</button></>}{id==='status'&&<button aria-label="Collapse Status table" onClick={()=>patch({leftOpen:false})}>−</button>}<button aria-label={`Close ${title}`} onClick={close}>×</button></>}<details className="cc-window-menu"><summary aria-label={`${title} window menu`}>⋮</summary><button onClick={()=>windows.pop(id)}>Open browser window ↗</button></details></div></header>
 {windows.states[id]==='open'&&!popout?<div className="cc-empty">Open in browser window<button onClick={()=>windows.pop(id)}>Focus window</button><button onClick={()=>windows.dock(id)}>Return to workspace</button></div>:<div className="cc-window-content">{children}</div>}
 </section>;
}
