import {PlayerResearch} from './PlayerResearch.jsx';
import {DfsLineupBuilder} from './DfsLineupBuilder.jsx';
import {useEffect,useState} from 'react';
import {Bars,Chips,Field,Grid,MetricSelect,Picker,PlayerName,Pool,Shell,Source,Status,Tip,useJson,useStored} from './shared.jsx';
import {POSITIONS,SCORING,fmt,salary,sortRows,stamp} from './model.js';
import {TREND_METRICS,trendValue} from '../trendMetrics.js';
const DEFAULTS={QB:['snaps','pass_attempts','fantasy_points'],RB:['snaps','rush_attempts','fantasy_points'],WR:['snaps','targets','fantasy_points'],TE:['snaps','targets','fantasy_points']};
const TONES={QB:'#a87cff',RB:'#3ecf8e',WR:'#5aa9ff',TE:'#d8bf79'},COLORS=['#3ecf8e','#f2ae49','#d8bf79'];
export function calendarComparison(history,metric,n=3){const avg=a=>{const values=a.map(h=>trendValue(h,metric)).filter(Number.isFinite);return {count:values.length,average:values.length?values.reduce((s,v)=>s+v,0)/values.length:null};};const recent=avg(history.slice(-n)),prior=avg(history.slice(-2*n,-n));return {recent,prior,delta:recent.count>=2&&prior.count>=2?recent.average-prior.average:null};}
export function OpportunityTracker({season,setSeason,scoring,setScoring,onOpen}){
 const [team,setTeam]=useState('NYG'),[selectedWeek,setWeek]=useState(null),[position,setPosition]=useState('All'),[pool,setPool]=useState('all'),[slate,setSlate]=useState('current'),[search,setSearch]=useState(''),[sort,setSort]=useState('depth'),[windowSize,setWindow]=useState(3),[localSort,setLocalSort]=useState({});
 const [saved,setSaved]=useStored('bowser:lhq:opportunity',{});const n=[3,5,8,10,18].includes(saved.history)?saved.history:10,values=saved.values!==false;const metrics=Object.fromEntries(POSITIONS.map(p=>[p,DEFAULTS[p].map((fallback,i)=>TREND_METRICS[saved.metrics?.[p]?.[i]]?saved.metrics[p][i]:fallback)]));const patch=v=>setSaved(s=>({...s,...v}));
 const meta=useJson(`/api/v1/meta?season=${season}`),week=selectedWeek??meta.data?.availableWeeks?.at(-1)??1,payload=useJson(`/api/v1/opportunity-tracker?${new URLSearchParams({season,team,weeks:week,games:[3,5,8,10,18].find(v=>v>=Math.max(n,windowSize*2)),scoring,dfsSlate:slate})}`),m=payload.data?.meta||{},all=(payload.data?.data?.groups||[]).flatMap(g=>g.players.map(r=>({...r,season,positionGroup:g.position,comparison:calendarComparison(r.history,metrics[g.position]?.[1]||'targets',windowSize)})));
 useEffect(()=>{setWeek(null);setLocalSort({});},[season]);
 const rows=all.filter(r=>(position==='All'||r.positionGroup===position)&&(pool!=='recorded'||r.history.slice(-n).some(h=>h.played))&&(pool!=='rising'||r.comparison.delta>0)&&(pool!=='falling'||r.comparison.delta<0)&&r.name.toLowerCase().includes(search.toLowerCase()));
 const slots=(m.trendSlots||[]).slice(-n),label=slots.length?`${slots[0].label} → ${slots.at(-1).label}`:'Unavailable';
 const movers=[...all].filter(r=>r.comparison.delta!=null).sort((a,b)=>Math.abs(b.comparison.delta)-Math.abs(a.comparison.delta)).slice(0,6),maxDelta=Math.max(1,...movers.map(r=>Math.abs(r.comparison.delta)));
 const settings=<><Field label="Search players"><input value={search} onChange={e=>setSearch(e.target.value)}/></Field><Field label="History weeks"><select value={n} onChange={e=>patch({history:Number(e.target.value)})}>{[3,5,8,10,18].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Compare window"><select value={windowSize} onChange={e=>setWindow(Number(e.target.value))}>{[3,4,5].map(v=><option key={v} value={v}>Last {v} vs prior {v}</option>)}</select></Field><Field label="Scoring"><select value={scoring} onChange={e=>setScoring(e.target.value)}>{SCORING.map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></Field><label><input type="checkbox" checked={values} onChange={e=>patch({values:e.target.checked})}/>Values above bars</label>{POSITIONS.map(p=><div className="lhq-chart-settings" key={p}><strong style={{color:TONES[p]}}>{p} chart metrics</strong>{metrics[p].map((metric,i)=><MetricSelect key={i} label={`Chart ${i+1}`} value={metric} onChange={v=>patch({metrics:{...metrics,[p]:metrics[p].map((x,j)=>i===j?v:x)}})}/>)}</div>)}</>;
 const panelMovers=<>{movers.length?movers.map(r=><div className="lhq-mover" key={r.playerId}><PlayerName row={r} onOpen={onOpen}/><span>{r.comparison.delta>0?'+':''}{fmt(r.comparison.delta,1)}</span><span className="lhq-diverging"><i style={{width:`${Math.abs(r.comparison.delta)/maxDelta*50}%`,left:r.comparison.delta>=0?'50%':`${50-Math.abs(r.comparison.delta)/maxDelta*50}%`,background:r.comparison.delta>=0?'#3ecf8e':'#e8735a'}}/></span><small>{TREND_METRICS[metrics[r.positionGroup][1]].label} · last {windowSize} vs prior {windowSize}</small></div>):<p className="lhq-note">Not enough observations to compare this window.</p>}</>;
 const chartWidth=n*((n<=5?36:n<=8?28:24)+3)+16;
 return <Shell page="opportunity-tracker" panels={[{id:'movers',title:'Biggest movers',content:panelMovers},{id:'filters',title:'Filters & settings',content:settings},{id:'depth',title:'Depth chart',content:<PlayerResearch kind="depth" team={team} season={season} weeks={String(week)} scoring={scoring} onOpen={onOpen}/>},{id:'schedule',title:'Team schedule',content:<PlayerResearch kind="schedule" team={team} season={season} weeks={String(week)} scoring={scoring} onOpen={onOpen}/>},{id:'lineups',title:'DraftKings lineup cards',content:<DfsLineupBuilder slate={slate} season={season} onOpen={onOpen}/>},{id:'reading',title:'Reading the tracker',content:<div className="lhq-note"><p>Every player shares the same calendar weeks; byes and DNPs stay in place.</p><p>Bars use one NFL-wide scale per statistic.</p><p>Delta needs at least two values in both comparison windows.</p><p>{m.injuryNewsMessage||'Practice injury news unavailable. Current roster status is shown.'}</p></div>}]} stacks={<><Picker label="Team" value={team} onChange={setTeam} options={meta.data?.teams||[team]}/><Picker label="Season" value={season} onChange={v=>setSeason(Number(v))} options={[2025,2026]}/><Picker label="Week" value={week} onChange={v=>setWeek(Number(v))} options={Array.from({length:18},(_,i)=>[i+1,`${season} · W${i+1}`])}/><Picker label="History" value={n} onChange={v=>patch({history:Number(v)})} options={[3,5,8,10,18].map(v=>[v,`${v} weeks`])}/><Picker label="DFS slate" value={slate} onChange={setSlate} options={m.dfs?.options?.map(v=>[v.key,v.label])||[['current','Current Classic']]} /></>} actions={<><Picker label="Compare" value={windowSize} onChange={v=>setWindow(Number(v))} options={[3,4,5].map(v=>[v,`Last ${v} vs prior ${v}`])}/><Picker label="Sort by" value={sort} onChange={v=>{setSort(v);setLocalSort({});}} options={[['depth','Depth chart'],['fantasy','Last-3 fantasy avg'],['snaps','Last-3 snaps avg'],['delta','Chart 2 delta']]}/></>} sources={<><Source label="DEPTH CHART" title={`nflverse official · ${m.depthUpdatedAt?.slice(5,10).replace('-','/')||'unavailable'}`} detail="then recent recorded snap volume" help={`Official depth chart captured ${m.depthUpdatedAt||'unavailable'}. Roster season ${m.rosterSeason||season}.`}/><Source label="STATS WINDOW" title={label} detail="calendar weeks · gaps kept" help={`Fantasy scoring: ${scoring}; source ${m.source||'nflverse'}.`}/><span className="lhq-source-note">{m.queryMs!=null?`${fmt(m.queryMs)} ms`:''}</span></>} options={<label><input type="checkbox" checked={values} onChange={e=>patch({values:e.target.checked})}/>Show values above bars</label>}>
 <Pool tabs={[{key:'all',label:'All',count:all.length},{key:'recorded',label:'Recorded games',count:all.filter(r=>r.history.slice(-n).some(h=>h.played)).length},{key:'rising',label:'Rising',count:all.filter(r=>r.comparison.delta>0).length},{key:'falling',label:'Falling',count:all.filter(r=>r.comparison.delta<0).length}]} value={pool} onChange={setPool}/><div className="lhq-strip"><Chips values={['All',...POSITIONS]} value={position} onChange={setPosition}/><Chips label="HISTORY WEEKS" values={[3,5,8,10,18]} value={n} onChange={v=>patch({history:v})}/><div className="lhq-metric-tiles">{['Chart 1','Chart 2','Chart 3'].map((name,i)=><div key={name}><strong style={{color:COLORS[i]}}>{position==='All'?['Snaps','Chart 2','Fantasy points'][i]:TREND_METRICS[metrics[position][i]].label}</strong><small>shared NFL scale</small></div>)}</div></div><Status loading={payload.loading} error={payload.error}/>
 {POSITIONS.filter(p=>position==='All'||position===p).map(p=>{const group=rows.filter(r=>r.positionGroup===p),ms=metrics[p],avg=(r,key)=>calendarComparison(r.history,key,3).recent;const columns=[{key:'name',label:'Player / roster status',group:'identity',groupLabel:'Player',width:236,pin:'left',value:r=>r.name,render:r=><div className="lhq-roster-player"><b className="lhq-monogram">{r.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</b><div><small style={{color:TONES[p]}}>{r.depthRank?`${r.depthPosition} ${r.depthRank}`:'ROSTERED'}</small><PlayerName row={r} onOpen={onOpen}/><small>{r.yearsExperience??'—'} yrs exp · {r.rosterStatusLabel||'Unavailable'}</small><Tip text={`Finish: ${r.position_finish_season||season} W${r.position_finish_week||week}. DFS: ${m.dfs?.label||'unavailable'}. Missing values unavailable.`}><small>FIN {r.position_finish?`${p}${r.position_finish}`:'—'} · DK {salary(r.draft_kings_price)} · PROJ {fmt(r.draft_kings_projection,2)}</small></Tip></div></div>},{key:'delta',label:`Last ${windowSize} vs prior ${windowSize}`,group:'context',groupLabel:'Chart 2',width:232,value:r=>r.comparison.delta,render:r=><div className="lhq-trend-context"><strong style={{color:r.comparison.delta==null?'#9e9e9e':r.comparison.delta>=0?'#3ecf8e':'#e8735a'}}>{r.comparison.delta==null?'→ comparison unavailable':`${r.comparison.delta===0?'→':r.comparison.delta>0?'↗':'↘'} ${TREND_METRICS[ms[1]].label} ${r.comparison.delta>=0?'+':''}${fmt(r.comparison.delta,1)} avg`}</strong><small>Last {windowSize} calendar weeks vs prior {windowSize}</small><small>{r.comparison.recent.count}/{windowSize} recent · {r.comparison.prior.count}/{windowSize} prior values</small>{!r.history.slice(-n).some(h=>h.played)&&<small className="lhq-amber">⚡ No recorded games in this window</small>}</div>},...ms.map((metric,i)=>({key:`chart${i}`,label:TREND_METRICS[metric].label,group:`chart${i}`,groupLabel:<span style={{color:COLORS[i]}}>{TREND_METRICS[metric].label} · {n} weeks</span>,width:chartWidth,sortable:false,render:r=><Bars large values={values} history={r.history.slice(-n)} metric={metric} domain={m.trendDomains?.[metric]} color={COLORS[i]}/>})),...ms.map((metric,i)=>({key:`avg${i}`,label:TREND_METRICS[metric].label,group:'averages',groupLabel:'Last 3 calendar weeks avg',width:[84,108,84][i],value:r=>avg(r,metric).average,render:r=><div className="lhq-avg" style={{color:i===2?'#d8bf79':undefined}}><b>{fmt(avg(r,metric).average,1)}</b><small>{avg(r,metric).count}/3 values</small></div>}))];const selection=localSort[p]||(sort==='depth'?null:{key:sort==='delta'?'delta':sort==='snaps'?'snapAvg':'fantasyAvg',desc:true});const enriched=group.map(r=>({...r,snapAvg:avg(r,'snaps').average,fantasyAvg:avg(r,'fantasy_points').average}));const ordered=selection?sortRows(enriched,selection,[...columns,{key:'snapAvg',value:r=>r.snapAvg},{key:'fantasyAvg',value:r=>r.fantasyAvg}]):enriched;
 return <section className="lhq-position-window lhq-opportunity" key={p}><div className="lhq-window-title"><b style={{background:TONES[p]}}>{p}</b><strong>{{QB:'Quarterbacks',RB:'Running backs',WR:'Wide receivers',TE:'Tight ends'}[p]}</strong><small>{group.length} players</small><em>{selection?`${columns.find(c=>c.key===selection.key)?.label||sort} ${selection.desc?'▼':'▲'}`:'Depth chart order'}</em></div><Grid columns={columns} rows={ordered} rowKey={r=>r.playerId} sort={selection} onSort={s=>setLocalSort(old=>({...old,[p]:s}))} label={`${p} opportunity tracker`} rowHeight={72}/></section>;})}<p className="lhq-footnote">{label} · Scoring {scoring} · DFS {m.dfs?.label||'unavailable'}. Practice reports: {m.injuryNewsAvailable?'available':'unavailable'}.</p></Shell>;
}
