import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {Bars,Chips,Field,Grid,MetricSelect,Picker,PlayerName,Pool,Ranges,Shell,Source,Status,Tiles,Tip,useJson,useStored} from './shared.jsx';
import {COLORS,POSITIONS,SCORING,competitionRank,csvDownload,fmt,inRanges,salary,sortRows,stamp} from './model.js';
import {TREND_METRICS,trendValue} from '../trendMetrics.js';
const DEFAULT_METRICS={usage:'snaps',rushing:'rush_attempts',receiving:'targets',fantasy:'fantasy_points'};
export function PlayerDatabase({season,setSeason,scoring,setScoring,onOpen}){
 const [rowLimit,setRowLimit]=useState(''),[rankSort,setRankSort]=useState({key:'fantasy_points',desc:true});
 const [weeks,setWeeks]=useState('1'),[slate,setSlate]=useState('current'),[search,setSearch]=useState(''),[position,setPosition]=useState('All'),[pool,setPool]=useState('all'),[hideZero,setHideZero]=useState(false),[ranges,setRanges]=useState({}),[games,setGames]=useState([]),[sort,updateSort]=useState({key:'fantasy_points',desc:true}),[selected,setSelected]=useState([]),[manage,setManage]=useState(false),[drafts,setDrafts]=useState(false),[exporting,setExporting]=useState(false),[exportError,setExportError]=useState('');
 const [showTrends,setShowTrends]=useStored('bowser:lhq:players:show-trends',true);
 const [hidden,setHidden]=useStored('bowser:lhq:players:hidden',[]),[widths,setWidths]=useStored('bowser:lhq:players:widths',{}),[count,setCount]=useStored('bowser:lhq:players:history',5),[savedMetrics,setMetrics]=useStored('bowser:lhq:players:metrics',DEFAULT_METRICS);
 const metrics=Object.fromEntries(Object.entries(DEFAULT_METRICS).map(([g,m])=>[g,TREND_METRICS[savedMetrics[g]]?savedMetrics[g]:m]));
 useEffect(()=>setGames([]),[weeks,season]);
 const metadata=useJson(`/api/v1/meta?season=${season}`),result=useJson(`/api/v1/player-stats?${new URLSearchParams({season,weeks,seasonType:'ALL',limit:'all',includeTrends:'1',trendWeeks:[5,8,10,18].includes(count)?count:5,dfsSlate:slate,scoring})}`),schedule=useJson(`/api/v1/schedule?season=${season}&week=${weeks}`);
 const all=result.data?.data||[],meta=result.data?.meta||{};let ranks=new Map();const setSort=next=>{updateSort(next);if(next.key!=='rank')setRankSort(next);};
 const toggleSelected=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const raw=(key,label,width,group,extra={})=>({key,label,width,group,groupLabel:group==='identity'?'Details':group[0].toUpperCase()+group.slice(1),color:group==='dfs'?COLORS.dfs:undefined,value:r=>r[key],render:r=>fmt(r[key]),...extra});
 const trend=(group)=>raw(`${group}_trend`,{usage:'Snap trend',rushing:'Rush trend',receiving:'Tgt trend',fantasy:'Fpts trend'}[group],100,group,{value:r=>trendValue(r.player_trends?.at(-1),metrics[group]),render:r=><Bars history={r.player_trends} metric={metrics[group]} domain={meta.trendDomains?.[metrics[group]]} color={group==='fantasy'?COLORS.faab:COLORS[group]}/>,help:`${metrics[group]} · ${count} aligned regular-season weeks; shared NFL scale`});
 const columns=[
 raw('select','',33,'identity',{pin:'left',sortable:false,render:r=><input type="checkbox" aria-label={`Select ${r.player_display_name}`} checked={selected.includes(r.player_id)} onChange={()=>toggleSelected(r.player_id)}/>}),
 raw('rank','Rank',47,'identity',{pin:'left',value:r=>ranks.get(r.player_id),render:r=>fmt(ranks.get(r.player_id))}),
 raw('player_display_name','Name',141,'identity',{pin:'left',render:r=><PlayerName row={r} onOpen={onOpen}/>}),raw('position','Pos',47,'identity',{pin:'left',render:r=>r.position}),
 raw('team','Team',62,'game',{render:r=>r.team}),raw('upcoming_opponent','Opp',72,'game',{render:r=>r.upcoming_opponent||'—',help:'Upcoming opponent; DFS slate and selected statistics weeks are independent.'}),raw('upcoming_kickoff_utc','Kick',92,'game',{render:r=>r.upcoming_kickoff_utc?new Date(r.upcoming_kickoff_utc).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/New_York'}):'—'}),
 raw('games_played','GP',47,'usage'),raw('snaps','Snaps',62,'usage'),raw('snap_pct','Snp%',62,'usage',{render:r=>r.snap_pct==null?'—':`${fmt(r.snap_pct)}%`}),trend('usage'),
 raw('passing_attempts','Att',56,'passing'),raw('completions','Cmp',56,'passing'),raw('passing_yards','Yds',62,'passing'),raw('passing_tds','TD',47,'passing'),
 raw('carries','Att',56,'rushing'),raw('rushing_yards','Yds',62,'rushing'),raw('rushing_tds','TD',47,'rushing'),trend('rushing'),
 raw('targets','Tgt',56,'receiving'),raw('receptions','Rec',56,'receiving'),raw('receiving_yards','Yds',62,'receiving'),raw('receiving_tds','TD',47,'receiving'),trend('receiving'),
 raw('draft_kings_price','Sal',62,'dfs',{render:r=><Tip text={`${meta.dfs?.label||'Unavailable'} · DraftKings salary`}>{salary(r.draft_kings_price)}</Tip>}),raw('draft_kings_projection','Proj',62,'dfs',{render:r=><Tip text={r.dfs_projection_source||'Projection unavailable'}>{fmt(r.draft_kings_projection,1)}</Tip>}),
 ...(drafts?[raw('adp','ADP',70,'draft'),raw('draft_position_rank','Pos rank',80,'draft')]:[]),
 {...trend('fantasy'),pin:'right'},raw('fantasy_points','Fpts',62,'fantasy',{pin:'right',color:COLORS.fantasy,render:r=><strong>{fmt(r.fantasy_points,1)}</strong>}),raw('position_finish','Fin',68,'fantasy',{pin:'right',render:r=>r.position_finish==null?'—':`${r.position}${r.position_finish}`,help:`NFL positional competition rank · ${season} week ${meta.weeks?.length===1?meta.weeks[0]:'latest selected week'} · ${scoring}`})];
 const rankColumn=columns.find(c=>c.key===rankSort.key);ranks=competitionRank(all,rankColumn?.value||((r)=>r[rankSort.key]),rankSort.desc);
 const filtered=all.filter(r=>(pool!=='offense'||POSITIONS.includes(r.position))&&(pool!=='kdst'||['K','DST','DEF'].includes(r.position))&&(position==='All'||r.position===position)&&(!hideZero||r.snaps>0)&&r.player_display_name.toLowerCase().includes(search.toLowerCase())&&(!games.length||schedule.data?.data.some(g=>games.includes(g.gameId)&&String(r.team||'').split(',').some(t=>[g.homeTeam,g.awayTeam].includes(t))))&&inRanges(r,ranges,{}));
 const rows=sortRows(filtered,sort,columns),shownRows=rowLimit===''?rows:rows.slice(0,Math.max(0,Number(rowLimit)||0)),visible=columns.filter(c=>!hidden.includes(c.key)&&(showTrends||!c.key.endsWith('_trend')));
 const reset=()=>{setRowLimit('');setSearch('');setPosition('All');setPool('all');setHideZero(false);setRanges({});setGames([]);setSort({key:'fantasy_points',desc:true});};
 useEffect(()=>{if(!manage)return;const close=e=>{if(e.key==='Escape')setManage(false);if(e.key==='Tab'){const nodes=[...document.querySelectorAll('.lhq-column-modal button,.lhq-column-modal input')];if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[manage]);
 const exportRows=async(allSlates=false)=>{setExporting(true);setExportError('');try{
 const keys=allSlates?[...new Set((meta.dfs?.options||[]).filter(o=>o.key!=='current').map(o=>o.key))]:[slate];let data=[];
 for(const key of keys){let payload=result.data;if(allSlates){const response=await fetch(`/api/v1/player-stats?${new URLSearchParams({season,weeks,seasonType:'ALL',limit:'all',dfsSlate:key,scoring})}`);if(!response.ok)throw Error(`Cannot export slate ${key}`);payload=await response.json();}
 const matching=new Set(rows.map(r=>r.player_id));data.push(...payload.data.filter(r=>matching.has(r.player_id)).map(r=>({...r,_stats_season:season,_stats_weeks:weeks,_scoring:scoring,_dfs_slate:payload.meta.dfs?.key,_dfs_season:payload.meta.dfs?.season,_dfs_week:payload.meta.dfs?.week,_dfs_captured:payload.meta.dfs?.capturedAt,_salary_url:payload.meta.dfs?.salaryUrl,_projection_provider:r.dfs_projection_source,_projection_url:r.dfs_projection_url})));}
 csvDownload(`bowser-${season}-weeks-${weeks}-${allSlates?'all-slates':slate}.csv`,[...visible,...['_stats_season','_stats_weeks','_scoring','_dfs_slate','_dfs_season','_dfs_week','_dfs_captured','_salary_url','_projection_provider','_projection_url'].map(key=>({key,label:key.slice(1)}))],data);
 }catch(e){setExportError(e.message);}finally{setExporting(false);}};
 const filters=<><Field label="Weeks"><input aria-label="Weeks comma-separated" value={weeks} onChange={e=>setWeeks(e.target.value)} placeholder="1,2,3"/></Field><p className="lhq-note">Exact NFL week numbers; postseason remains selectable. No data is substituted for unplayed weeks.</p><Field label="History"><select value={count} onChange={e=>setCount(Number(e.target.value))}>{[5,8,10,18].map(n=><option key={n} value={n}>{n} weeks</option>)}</select></Field>{Object.keys(metrics).map(g=><MetricSelect key={g} label={`${g} trend`} value={metrics[g]} onChange={v=>setMetrics({...metrics,[g]:v})}/>)}<label><input type="checkbox" checked={drafts} onChange={e=>setDrafts(e.target.checked)}/>Show sourced draft fields</label><button className="lhq-outline lhq-mini" onClick={()=>setManage(true)}>Manage columns</button></>;
 const totals=<><table className="lhq-summary-table"><thead><tr><th>Position</th><th>Players</th><th>Avg Fpts</th><th>Top</th></tr></thead><tbody>{POSITIONS.map(p=>{const a=filtered.filter(r=>r.position===p),known=a.map(r=>r.fantasy_points).filter(Number.isFinite);return <tr key={p}><td>{p}</td><td>{a.length}</td><td>{known.length?fmt(known.reduce((n,v)=>n+v,0)/known.length,1):'—'}</td><td>{known.length?<span><PlayerName row={a.filter(r=>Number.isFinite(r.fantasy_points)).sort((a,b)=>b.fantasy_points-a.fantasy_points)[0]} onOpen={onOpen}/><small> {fmt(Math.max(...known),1)}</small></span>:'—'}</td></tr>;})}</tbody></table></>;
 return <><Shell page="players" sidebarWidth={367} defaultPanel="totals" panels={[{id:'filters',title:'Filters & settings',content:filters},{id:'totals',title:'Position Totals',content:totals}]} stacks={<><Picker label="Season" value={season} options={metadata.data?.seasons||[2025,2026]} onChange={v=>{setSeason(Number(v));setGames([]);}}/><Picker label="Week(s)" value={weeks} options={[[weeks,weeks.includes(',')?`Weeks ${weeks}`:`Week ${weeks}`],...Array.from({length:22},(_,i)=>[String(i+1),`Week ${i+1}`]).filter(x=>x[0]!==weeks)]} onChange={setWeeks}/><Picker label="DFS slate" value={slate} options={meta.dfs?.options?.map(o=>[o.key,o.label])||[['current','Current Classic']]} onChange={setSlate} wide/><Picker label="Scoring" value={scoring} options={SCORING} onChange={setScoring}/></>} actions={<><small>SHOW <input type="number" min="0" aria-label="Displayed row limit" value={rowLimit===''?rows.length:rowLimit} onChange={e=>setRowLimit(e.target.value)}/> PLAYERS USING</small><Picker label="Sort" value={sort.key} onChange={key=>setSort({key,desc:true})} options={columns.filter(c=>c.sortable!==false).map(c=>[c.key,`${c.groupLabel||c.group||''} · ${c.label}`])}/><button className="lhq-outline lhq-mini" onClick={()=>setManage(true)}>Column options</button></>} sources={<><Source label="STATS SOURCE" title={`nflverse · ${season} season`} detail={`Updated: ${stamp(metadata.data?.warehouse?.imported_at)}`} help="Immutable nflverse weekly statistics, selected scoring and exact weeks."/><Source label="DFS SOURCE" title={meta.dfs?.scoring||'DraftKings'} detail={`${meta.dfs?.season||'—'} W${meta.dfs?.week||'—'} · ${stamp(meta.dfs?.capturedAt)}`} help={meta.dfs?.projectionProvider||'Projection source unavailable'}/><button className="lhq-mini" onClick={()=>setHidden(h=>h.includes('draft_kings_price')?h.filter(k=>!['draft_kings_price','draft_kings_projection'].includes(k)):[...h,'draft_kings_price','draft_kings_projection'])}>Hide / Show DFS fields ☁</button><Tip text="Download currently filtered rows with source slate context"><button disabled={exporting} onClick={()=>exportRows(false)}>↓</button></Tip><Tip text="Download filtered players for every archived slate with source provenance"><button disabled={exporting} aria-label="Download all slates" onClick={()=>exportRows(true)}>↓↓</button></Tip></>} options={<><button onClick={()=>{setManage(true);}}>Manage Columns</button><label><input type="checkbox" checked={showTrends} onChange={e=>setShowTrends(e.target.checked)}/>Show trend columns</label></>}>
 <div className="lhq-pool-line"><Pool transfer={()=>setSelected(filtered.map(r=>r.player_id))} tabs={[{key:'all',label:'All',count:all.length},{key:'offense',label:'Offense',count:all.filter(r=>POSITIONS.includes(r.position)).length},{key:'kdst',label:'K / DST',count:all.filter(r=>['K','DST','DEF'].includes(r.position)).length}]} value={pool} onChange={setPool}><label><input type="checkbox" checked={hideZero} onChange={e=>setHideZero(e.target.checked)}/>Hide players with 0 snaps</label></Pool><Ranges definitions={[["draft_kings_price","Salary"],["fantasy_points","FPTS"],["snaps","Snaps"],["targets","Targets"]]} values={ranges} onChange={setRanges}/></div>
 <div className="lhq-strip"><Chips values={['All',...POSITIONS,'K','DST']} value={position} onChange={setPosition}/><Tiles tiles={(schedule.data?.data||[]).map(g=>({key:g.gameId,title:`${g.awayTeam} @ ${g.homeTeam}`,detail:g.totalPoints==null?'O/U unavailable':`${g.awayScore}–${g.homeScore} · ${g.totalPoints} total`,sub:`${g.gameday||''} ${g.gametime||''} ET`}))} selected={games} onClear={()=>setGames([])} onToggle={id=>setGames(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id])}/></div>
 <Status loading={result.loading} error={result.error||exportError}/>{exporting&&<p className="lhq-note" role="status">Preparing sourced slate export…</p>}<Grid columns={visible} rows={shownRows} sort={sort} onSort={setSort} search={search} onSearch={setSearch} reset={reset} resizable widths={widths} onResize={(k,v)=>setWidths(w=>({...w,[k]:v}))}/><div className="lhq-footnote"><span>{shownRows.length} shown · {rows.length} filtered of {all.length} players · {season} W{weeks} · {scoring.toUpperCase()}</span><span>nflverse · DraftKings / {meta.dfs?.projectionProvider||'projections unavailable'} · NFL-wide trend domains</span></div>
 </Shell>{manage&&createPortal(<div className="lhq-modal-backdrop" onClick={()=>setManage(false)}><section className="lhq lhq-column-modal" role="dialog" aria-modal="true" aria-label="Manage columns" onClick={e=>e.stopPropagation()}><header><strong>Manage Columns</strong><button autoFocus onClick={()=>setManage(false)}>×</button></header><div className="lhq-modal-tabs">{['All',...POSITIONS].map(p=><button key={p} className={position===p?'active':''} onClick={()=>setPosition(p)}>{p.toUpperCase()}</button>)}</div><div className="lhq-column-groups">{[...new Set(columns.map(c=>c.group))].map(group=><fieldset key={group}><legend>{group}</legend>{columns.filter(c=>c.group===group&&c.key!=='select').map(c=><label key={c.key}><input type="checkbox" checked={!hidden.includes(c.key)} onChange={e=>setHidden(h=>e.target.checked?h.filter(k=>k!==c.key):[...h,c.key])}/>{c.label}</label>)}</fieldset>)}</div><footer><button className="lhq-mini lhq-outline" onClick={()=>{setHidden([]);setShowTrends(true);}}>Show All</button><button className="lhq-mini lhq-outline" onClick={()=>{setHidden([]);setWidths({});setMetrics(DEFAULT_METRICS);setShowTrends(true);}}>Reset to defaults</button><button className="lhq-mini lhq-outline" onClick={()=>setManage(false)}>Done</button></footer></section></div>,document.body)}</>;
}
