import {useEffect,useMemo,useState} from 'react';
import {Bars,Chips,Field,Grid,MetricSelect,Picker,PlayerName,Pool,Shell,Source,Status,Tiles,Tip,useJson,useStored} from './shared.jsx';
import {COLORS,POSITIONS,SCORING,csvDownload,fmt,salary,sortRows,stamp} from './model.js';
import {trendValue} from '../trendMetrics.js';
import {DEFAULT_VISIBLE_STATS,DEFAULT_COLUMN_WIDTHS,MARKER_TYPES,TEAM_BOX_PREFERENCE_KEY,WEEK_COLUMN_REGISTRY,sanitizeTeamBoxPreferences} from '../teamBoxColumns.js';
const SYMBOLS={favorite:'★',like:'▲',dislike:'▼',maybe:'?',watch:'◉',research:'≡'};
const COMMON=[['snaps','SNP',36,'misc'],['snap_pct','SNP%',44,'misc']],PASS=[['passing_line','C-A',54,'passing'],['passing_yards','YDS',40,'passing'],['passing_tds','TD',30,'passing'],['interceptions','INT',32,'passing']],REC=[['targets','TGT',36,'receiving'],['receptions','REC',36,'receiving'],['receiving_yards','YDS',40,'receiving'],['receiving_tds','TD',30,'receiving']],TAIL=[['carries','ATT',36,'rushing'],['rushing_yards','YDS',40,'rushing'],['rushing_tds','TD',30,'rushing'],['fantasy_points','FPTS',48,'fantasy'],['position_finish','FIN',50,'fantasy'],['draft_kings_price','DK$',50,'dfs'],['draft_kings_projection','PROJ',42,'dfs']];
const tone={QB:'#a87cff',RB:'#3ecf8e',WR:'#5aa9ff',TE:'#d8bf79'};
export function median(values){const a=values.filter(Number.isFinite).sort((a,b)=>a-b);return a.length?(a[Math.floor((a.length-1)/2)]+a[Math.ceil((a.length-1)/2)])/2:null;}
const finite = value => typeof value === 'number' && Number.isFinite(value);
const DFS_STATS = new Set(['draft_kings_price','draft_kings_projection']);
export function teamWeekValue(item,key) {
 if(!item || (!DFS_STATS.has(key) && (!item.played || item.stats_available===false)))return null;
 if(key==='passing_line')return finite(item.completions)&&finite(item.passing_attempts)?item.passing_attempts:null;
 return finite(item[key])?item[key]:null;
}
export function teamBoxWidths(saved={}) {
 const allowed=new Set(['marker','player','trend',...DEFAULT_VISIBLE_STATS]);
 const entries={...Object.fromEntries(Object.entries(saved.columnWidths||{}).filter(([key,value])=>allowed.has(key)&&finite(value)&&value!==DEFAULT_COLUMN_WIDTHS[key])),...(saved.lhqWidths&&typeof saved.lhqWidths==='object'&&!Array.isArray(saved.lhqWidths)?saved.lhqWidths:{})};
 return Object.fromEntries(Object.entries(entries).filter(([key,value])=>allowed.has(key)&&finite(value)).map(([key,value])=>[key,Math.max(28,Math.min(420,value))]));
}
export function shortKickoff(game) {
 if(!game?.gameday)return 'Date unavailable';
 const day=new Date(`${game.gameday}T12:00:00Z`),date=Number.isNaN(day.getTime())?game.gameday:day.toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'});
 const match=/^(\d{1,2}):(\d{2})/.exec(game.gametime||'');
 return match?`${date}, ${Number(match[1])%12||12}:${match[2]}${Number(match[1])>=12?'p':'a'} ET`:date;
}
const sumKnown=values=>values.length&&values.every(finite)?values.reduce((sum,value)=>sum+value,0):null;
const scoredRows=(rows)=>rows.filter(row=>row?.played&&row.stats_available!==false);
const gameTotal=game=>finite(game?.pointsFor)&&finite(game?.pointsAgainst)?game.pointsFor+game.pointsAgainst:null;
const topScorer=(rows,read)=>rows.filter(row=>finite(read(row))).sort((a,b)=>read(b)-read(a)||a.player_display_name.localeCompare(b.player_display_name))[0];
export function teamCsvColumns(stats,team,scoring,markers={}) {
 return [{key:'player_id',label:'Player ID'},{key:'player_display_name',label:'Player'},{key:'position_group',label:'Position'},
 {key:'team',label:'Team',value:()=>team},{key:'season',label:'Stats season'},{key:'week',label:'Stats week'},{key:'game_id',label:'Game ID'},
 {key:'scoring',label:'Stats scoring',value:()=>scoring},{key:'played',label:'Played'},{key:'stats_available',label:'Stats available'},
 {key:'marker',label:'Local marker',value:row=>markers[row.player_id]||''},
 ...stats.map(key=>({key,label:WEEK_COLUMN_REGISTRY[key].name,value:row=>key==='passing_line'?(teamWeekValue(row,key)==null?null:`${row.completions}-${row.passing_attempts}`):teamWeekValue(row,key)})),
 ...['season','week','slateKey','label','capturedAt','salarySource','salaryUrl','projectionSource','projectionUrl','projectionCapturedAt'].map(key=>({key:`dfs_${key}`,label:`DFS ${key}`,value:row=>row.dfs_meta?.[key]??null}))];
}
export function TeamBoxScores({season,setSeason,scoring,setScoring,onOpen}){
 const [team,setTeam]=useState('NYG'),[position,setPosition]=useState('All'),[pool,setPool]=useState('all'),[markerFilter,setMarkerFilter]=useState(''),[search,setSearch]=useState(''),[end,setEnd]=useState(null),[sorts,setSorts]=useState({}),[trendAnchor,setTrendAnchor]=useState(''),[trendMetric,setTrendMetric]=useState('snaps'),[trendWeeks,setTrendWeeks]=useState(5),[dragged,setDragged]=useState(false);
 const [saved,setSaved]=useStored(TEAM_BOX_PREFERENCE_KEY,{}),old=sanitizeTeamBoxPreferences(saved),markers=old.markers,visibleStats=old.visibleStats.filter(key=>Object.hasOwn(WEEK_COLUMN_REGISTRY,key));
 const n=[1,2,3,4,6].includes(saved.weeksPerView)?saved.weeksPerView:3,hidden=Array.isArray(saved.hiddenWeeks)?saved.hiddenWeeks.filter(key=>/^(2025|2026)-(?:[1-9]|1\d|2[0-2])$/.test(key)):[],heat=saved.heatOn!==false,dfs=saved.dfsOn!==false;
 const widths=teamBoxWidths(saved);
 const patch=value=>setSaved(s=>({...s,...value}));const setMarker=(id,value)=>patch({markers:{...markers,[id]:value}});
 const meta=useJson(`/api/v1/meta?season=${season}`),available=meta.data?.availableWeeks||[1],previous=season===2026?2025:null;
 const req=s=>`/api/v1/team-box-scores?${new URLSearchParams({season:s,team,seasonType:'ALL',scoring,weeks:Array.from({length:s===previous?18:22},(_,i)=>i+1).join(','),trendAnchors:trendAnchor.startsWith(`${s}-`)?trendAnchor.split('-')[1]:'',trendWeeks})}`;
 const current=useJson(req(season)),prior=useJson(previous?req(previous):null);
 useEffect(()=>{setEnd(null);setSorts({});setTrendAnchor('');},[season,team]);
 const timeline=useMemo(()=>[...(previous?Array.from({length:18},(_,i)=>({season:previous,week:i+1})):[]),...Array.from({length:22},(_,i)=>({season,week:i+1}))].map(w=>{const payload=w.season===season?current.data:prior.data,g=payload?.meta?.schedule?.find(g=>g.week===w.week);return {...w,...g,key:`${w.season}-${w.week}`,label:`${String(w.season).slice(-2)}·${w.week}`};}),[previous,season,current.data,prior.data]);
 const endIndex=end===null?(previous?18:0)+Math.max(...available)-1:Math.max(n-1,Math.min(timeline.length-1,end)),windowWeeks=timeline.slice(Math.max(0,endIndex-n+1),endIndex+1),weeks=windowWeeks.filter(w=>!hidden.includes(w.key));
 const data=[...(prior.data?.data||[]),...(current.data?.data||[])];
 const players=useMemo(()=>{const map=new Map();for(const row of data){if(!windowWeeks.some(w=>w.season===row.season&&w.week===row.week))continue;const id=row.player_id;const r=map.get(id)||{player_id:id,player_display_name:row.player_display_name,position:row.position_group||row.position,team,season,weeks:{}};r.weeks[`${row.season}-${row.week}`]=row;map.set(id,r);}return [...map.values()];},[current.data,prior.data,windowWeeks.map(w=>w.key).join(','),team,season]);
 const filtered=players.filter(r=>(position==='All'||r.position===position)&&(pool!=='marked'||markers[r.player_id])&&(pool!=='every'||weeks.length>0&&weeks.every(w=>r.weeks[w.key]?.played))&&(!markerFilter||markers[r.player_id]===markerFilter)&&r.player_display_name.toLowerCase().includes(search.toLowerCase()));
 const value=(r,w,key)=>teamWeekValue(r.weeks[w],key);
 const display=(item,key,total=false)=>{if(!item)return '—';const v=item[key];if(total&&['snap_pct','position_finish','draft_kings_projection'].includes(key))return '—';if(key==='passing_line')return item.completions==null||item.passing_attempts==null?'—':`${item.completions}-${item.passing_attempts}`;if(key==='draft_kings_price')return salary(v);if(key==='position_finish')return v==null?'—':`${item.position_group||item.position}${v}`;if(key==='snap_pct')return v==null?'—':`${fmt(v)}%`;return fmt(v,['fantasy_points','draft_kings_projection'].includes(key)?1:0);};
 const latest=[...timeline].reverse().find(w=>finite(w.pointsFor)&&finite(w.pointsAgainst)),totalFpts=r=>sumKnown(scoredRows(weeks.map(w=>r.weeks[w.key])).map(row=>row.fantasy_points));
 const latestRows=latest?data.filter(row=>row.season===latest.season&&row.week===latest.week):[],latestTop=topScorer(scoredRows(latestRows),row=>row.fantasy_points);
 const exportedStats=visibleStats.filter(key=>dfs||!DFS_STATS.has(key));
 const exportCsv=()=>{const ids=new Set(filtered.map(row=>row.player_id));const rows=data.filter(row=>ids.has(row.player_id)&&weeks.some(w=>w.season===row.season&&w.week===row.week));csvDownload(`team-${team}-${weeks.map(w=>w.key).join('_')}-${scoring}.csv`,teamCsvColumns(exportedStats,team,scoring,markers),rows);};
 const latestPanel=<><div className="lhq-summary">{latest?`${team} ${latest.scoreLabel} · ${latest.season} W${latest.week}`:'No completed game available'}</div><table><tbody>{[['Opponent',latest?.opponent],['Result',latest?.scoreLabel],['Kickoff',latest?shortKickoff(latest):null],['Players with a snap',latest&&latestRows.some(r=>teamWeekValue(r,'snaps')!=null)?latestRows.filter(r=>teamWeekValue(r,'snaps')>0).length:null],['Top scorer',latestTop?`${latestTop.player_display_name} · ${fmt(latestTop.fantasy_points,1)} pts`:null]].map(([k,v])=><tr key={k}><td>{k}</td><td>{v??'—'}</td></tr>)}</tbody></table></>;
 const totalsPanel=<table><thead><tr><th>Pos</th><th>Players</th><th>Fpts</th><th>Per wk</th><th>Top scorer</th></tr></thead><tbody>{POSITIONS.map(p=>{const a=filtered.filter(r=>r.position===p),pts=sumKnown(a.map(totalFpts)),top=topScorer(a,totalFpts);return <tr key={p}><td>{p}</td><td>{a.length}</td><td style={{color:COLORS.fantasy}}>{fmt(pts,1)}</td><td>{weeks.length&&pts!=null?fmt(pts/weeks.length,1):'—'}</td><td>{top?`${top.player_display_name} · ${fmt(totalFpts(top),1)}`:'—'}</td></tr>;})}</tbody></table>;
 const settings=<><Field label="Weeks per view"><select value={n} onChange={e=>patch({weeksPerView:Number(e.target.value)})}>{[1,2,3,4,6].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Window ends at"><select value={timeline[endIndex]?.key} onChange={e=>setEnd(timeline.findIndex(w=>w.key===e.target.value))}>{timeline.map(w=><option key={w.key} value={w.key}>{w.season} W{w.week}</option>)}</select></Field><label><input type="checkbox" checked={heat} onChange={e=>patch({heatOn:e.target.checked})}/>Judged-cell shading</label><label><input type="checkbox" checked={dfs} onChange={e=>patch({dfsOn:e.target.checked})}/>DFS columns</label><div className="lhq-stat-toggles">{DEFAULT_VISIBLE_STATS.map(k=><label key={k}><input type="checkbox" checked={visibleStats.includes(k)} onChange={e=>patch({visibleStats:e.target.checked?[...visibleStats,k]:visibleStats.filter(v=>v!==k)})}/>{WEEK_COLUMN_REGISTRY[k].name}</label>)}</div><Field label="Insert trend after"><select value={trendAnchor} onChange={e=>setTrendAnchor(e.target.value)}><option value="">No inserted trend</option>{weeks.map(w=><option key={w.key} value={w.key}>{w.season} W{w.week}</option>)}</select></Field><MetricSelect label="Trend metric" value={trendMetric} onChange={setTrendMetric}/><Field label="Trend history"><select value={trendWeeks} onChange={e=>setTrendWeeks(Number(e.target.value))}>{[5,8,10,18].map(v=><option key={v}>{v}</option>)}</select></Field><p className="lhq-note">Drag the inserted trend header onto a week header to place it after that week. Each stat width is shared by every week and position section.</p><button className="lhq-mini lhq-outline" onClick={()=>patch({lhqWidths:{},columnWidths:{},visibleStats:DEFAULT_VISIBLE_STATS,hiddenWeeks:[]})}>Reset table defaults</button></>;
 const markerPanel=<><div className="lhq-markers-legend">{MARKER_TYPES.map(m=><button key={m} className="lhq-data-link" onClick={()=>setMarkerFilter(markerFilter===m?'':m)}>{SYMBOLS[m]} {m} ({players.filter(r=>markers[r.player_id]===m).length})</button>)}</div><p className="lhq-note">Markers are local research preferences. League ownership filtering is unavailable until private Yahoo rosters are loaded. Saved league selections are retained.</p><a href="#/yahoo">Connect Yahoo</a></>;
 return <Shell page="team-box-scores" defaultHidden sidebarWidth={400} panels={[{id:'latest',title:'Latest game',content:latestPanel},{id:'totals',title:'Position Totals',content:totalsPanel},{id:'markers',title:'Markers & leagues',content:markerPanel},{id:'settings',title:'Filters & settings',content:settings}]} stacks={<><Picker label="Team" value={team} options={meta.data?.teams||[team]} onChange={setTeam}/><Picker label="Season" value={season} options={[2025,2026]} onChange={v=>setSeason(Number(v))}/><div className="lhq-stack"><span>Weeks shown</span><strong>{windowWeeks[0]?.label} → {windowWeeks.at(-1)?.label}</strong></div><Picker label="Scoring" value={scoring} options={SCORING} onChange={setScoring}/></>} actions={<><div className="lhq-week-controls"><button aria-label="Previous week window" disabled={endIndex<n} onClick={()=>setEnd(endIndex-1)}>‹</button>{windowWeeks[0]?.label} → {windowWeeks.at(-1)?.label}<button aria-label="Next week window" disabled={endIndex>=timeline.length-1} onClick={()=>setEnd(endIndex+1)}>›</button></div>{weeks.at(-1)?.gameId&&<a className="lhq-mini lhq-outline" href={`#/game/${weeks.at(-1).gameId}?scoring=${scoring}`}>Open game breakdown</a>}</>} sources={<><Source label="LATEST GAME" title={latest?`${team} · ${latest.scoreLabel}`:'Unavailable'} detail={latest?`${latest.season} W${latest.week} · ${latest.opponent} · ${latest.gameday}`:'No completed games'} help="Actual completed-game score from nflverse."/><Source label="DFS SOURCE" title="DraftKings Classic" detail="Historical salary per exact week" help="Each salary and projection is joined to the exact season/week archive. Missing historical captures remain unavailable."/><button className="lhq-icon" aria-label="Download team weeks CSV" onClick={exportCsv}>↓</button></>} options={<><Field label="Weeks per view"><select value={n} onChange={e=>patch({weeksPerView:Number(e.target.value)})}>{[1,2,3,4,6].map(v=><option key={v}>{v}</option>)}</select></Field><label><input type="checkbox" checked={heat} onChange={e=>patch({heatOn:e.target.checked})}/>Judged-cell shading</label><label><input type="checkbox" checked={dfs} onChange={e=>patch({dfsOn:e.target.checked})}/>DFS columns</label></>}>
 <div className="lhq-pool-line"><Pool tabs={[{key:'all',label:'All',count:players.length},{key:'marked',label:'Marked',count:players.filter(r=>markers[r.player_id]).length},{key:'every',label:'Played every week',count:weeks.length?players.filter(r=>weeks.every(w=>r.weeks[w.key]?.played)).length:0}]} value={pool} onChange={setPool} transfer={()=>patch({markers:{...markers,...Object.fromEntries(filtered.map(r=>[r.player_id,'favorite']))}})}/><div className="lhq-marker-chips">{MARKER_TYPES.map(m=><button key={m} className={markerFilter===m?'active':''} onClick={()=>setMarkerFilter(markerFilter===m?'':m)}>{SYMBOLS[m]} {m}</button>)}</div></div>
 <div className="lhq-strip"><Chips values={['All',...POSITIONS]} value={position} onChange={setPosition}/><Tiles tiles={windowWeeks.map(w=>({key:w.key,title:`${w.label}${gameTotal(w)!=null?` · ${gameTotal(w)} pts`:''}`,detail:`${w.homeAway==='away'?'@':'vs'} ${w.opponent||'BYE'} · ${w.scoreLabel||'—'}`,sub:w.gameday?shortKickoff(w):'No game'}))} selected={weeks.map(w=>w.key)} onClear={()=>patch({hiddenWeeks:[]})} onToggle={k=>patch({hiddenWeeks:hidden.includes(k)?hidden.filter(x=>x!==k):[...hidden,k]})}/></div><Status loading={current.loading||prior.loading} error={current.error||prior.error}/>
 {POSITIONS.filter(p=>position==='All'||position===p).map(p=>{const group=filtered.filter(r=>r.position===p),scope=players.filter(r=>r.position===p),defs=[...COMMON,...(p==='QB'?PASS:REC),...TAIL].filter(([k,,,g])=>visibleStats.includes(k)&&(dfs||g!=='dfs'));
 const columns=[{key:'marker',label:'Mark',width:40,widthKey:'marker',group:'identity',groupLabel:'Player details',pin:'left',value:r=>markers[r.player_id]||'',render:r=><select className="lhq-marker-select" aria-label={`Marker for ${r.player_display_name}`} value={markers[r.player_id]||''} onChange={e=>setMarker(r.player_id,e.target.value)}><option value="">☆</option>{MARKER_TYPES.map(m=><option value={m} key={m}>{SYMBOLS[m]} {m}</option>)}</select>},{key:'player_display_name',label:'Player',width:150,widthKey:'player',group:'identity',pin:'left',value:r=>r.player_display_name,render:r=><PlayerName row={r} onOpen={onOpen} marked={!!markers[r.player_id]}/>}];
 const groupContent={};for(const w of weeks){groupContent[w.key]=<><button className={`lhq-week-sort ${(sorts[p]?.key||`${weeks.at(-1)?.key}:fantasy_points`).startsWith(`${w.key}:`)?'active':''}`} onClick={()=>setSorts(s=>({...s,[p]:{key:`${w.key}:fantasy_points`,desc:true}}))}>SORT WEEK</button><span className="lhq-week-drop" onDragOver={e=>{if(dragged)e.preventDefault();}} onDrop={e=>{e.preventDefault();setTrendAnchor(w.key);setDragged(false);}}>↤</span></>;for(const [k,label,width,subgroup]of defs)columns.push({key:`${w.key}:${k}`,label,width,widthKey:k,group:w.key,groupLabel:<span className="lhq-week-label">{w.label} · {w.homeAway==='away'?'@':'vs'} {w.opponent||'BYE'} · {w.scoreLabel||'—'}{gameTotal(w)!=null?` · ${gameTotal(w)} pts`:''} · {w.gameday?shortKickoff(w):''}</span>,subgroup,subgroupLabel:{misc:'MISC',passing:'PASS',receiving:'REC',rushing:'RUSH',fantasy:'FANTASY',dfs:'DFS'}[subgroup],value:r=>value(r,w.key,k),help:`${WEEK_COLUMN_REGISTRY[k].name} · ${w.season} W${w.week}; missing data is unavailable`,render:r=>{const item=r.weeks[w.key];return <Tip text={subgroup==='dfs'?item?.dfs_meta?.label||'No archived source for this week':`${w.season} W${w.week} · ${WEEK_COLUMN_REGISTRY[k].name}`}><span style={{fontWeight:k==='fantasy_points'?700:undefined,color:teamWeekValue(item,k)==null?'#4a4a4a':undefined}}>{display(DFS_STATS.has(k)||item?.played&&item.stats_available!==false?item:null,k)}</span></Tip>;},stat:k,weekKey:w.key});
 if(trendAnchor===w.key){const dataSource=w.season===season?current.data:prior.data;const history=r=>dataSource?.data?.find(x=>x.player_id===r.player_id)?.trendsByAnchor?.[w.week]||dataSource?.meta?.trendsByAnchor?.[w.week]?.slots||[];columns.push({key:`trend:${w.key}`,label:'Trend',width:180,widthKey:'trend',group:`trend:${w.key}`,groupLabel:<span draggable onDragStart={()=>setDragged(true)} onDragEnd={()=>setDragged(false)}>{trendMetric} · {trendWeeks} weeks ↔</span>,value:r=>trendValue(history(r).at(-1),trendMetric),render:r=><Bars history={history(r)} metric={trendMetric} domain={dataSource?.meta?.trendsByAnchor?.[w.week]?.domains?.[trendMetric]}/>});}}
 const requested=sorts[p]||{key:`${weeks.at(-1)?.key}:fantasy_points`,desc:true},sort=columns.some(c=>c.key===requested.key)?requested:{key:'player_display_name',desc:false},sorted=sortRows(group,sort,columns);
 const footer=<tr>{columns.map(c=>{if(c.key==='player_display_name')return <td key={c.key}>TOTAL</td>;if(!c.stat)return <td key={c.key}/>;const values=group.map(r=>r.weeks[c.weekKey]).filter(x=>x&&(DFS_STATS.has(c.stat)||x.played&&x.stats_available!==false));const sum={position:p};for(const k of [...DEFAULT_VISIBLE_STATS,'completions','passing_attempts']){sum[k]=sumKnown(values.map(r=>r[k]));}return <td key={c.key} style={{color:c.stat==='fantasy_points'?COLORS.fantasy:undefined}}>{display(sum,c.stat,true)}</td>;})}</tr>;
 return <section className="lhq-position-window" key={p}><div className="lhq-window-title"><b style={{background:tone[p]}}>{p}</b><strong>{{QB:'Quarterbacks',RB:'Running backs',WR:'Wide receivers',TE:'Tight ends'}[p]}</strong><span>{group.length} players · <b style={{color:COLORS.fantasy}}>{fmt(sumKnown(group.map(totalFpts)),1)} pts</b> · {weeks.length} weeks</span><em style={{marginLeft:'auto'}}>sorted by {columns.find(c=>c.key===sort.key)?.label} · {timeline.find(w=>w.key===sort.key.split(':')[0])?.label||sort.key.split(':')[0]} {sort.desc?'▼':'▲'}</em></div><Grid columns={columns} rows={sorted} sort={sort} onSort={v=>setSorts(s=>({...s,[p]:v}))} search={search} onSearch={setSearch} label={`${p} weekly team box scores`} height="none" small subgroups widths={widths} resizable onResize={(k,v)=>patch({lhqWidths:{...widths,[k]:v}})} groupContent={groupContent} footer={footer} cellStyle={(r,c)=>{if(!heat||!['fantasy_points','targets','carries'].includes(c.stat))return {};const v=value(r,c.weekKey,c.stat),m=median(scope.map(x=>value(x,c.weekKey,c.stat)));if(v==null||m==null||v===m)return {};return {background:v>m?'rgba(62,207,142,.16)':'rgba(232,115,90,.16)',color:v>m?'#3ecf8e':'#e8735a'};}}/></section>;
 })}<p className="lhq-footnote">Historical salary and projection archives follow each column’s exact season/week. Calendar gaps stay unavailable.</p></Shell>;
}
