import {TREND_METRICS} from '../trendMetrics.js';
import {useState} from 'react';
import {Bars,Chips,Field,Grid,MetricSelect,Picker,PlayerName,Pool,Ranges,Shell,Source,Status,Tiles,Tip,useJson,useStored} from './shared.jsx';
import {COLORS,POSITIONS,SCORING,csvDownload,fmt,inRanges,sortRows,stamp} from './model.js';
import {LeagueResearchPanel,MarkPickupButton,useLeaguePickups} from './LeagueResearch.jsx';
import {leagueKeyFromTeam} from './playerIdentity.js';
import {columnValue,faabValue,favoriteKey,formatFAAB,playerKey,validateFavorites,waiverColumns} from '../waiverTable.js';
const MODES=[['native','Native units'],['percent','Percent of budget'],['dollars','Dollars of budget']];
export function Waivers({season,setSeason,scoring,setScoring,onOpen,yahoo}){
 const [rowLimit,setRowLimit]=useState('');
 const [week,setWeek]=useState(2),[weeks,setWeeks]=useState('1'),[revision,setRevision]=useState(0),[search,setSearch]=useState(''),[pool,setPool]=useState('all'),[position,setPosition]=useState('All'),[teams,setTeams]=useState([]),[ranges,setRanges]=useState({}),[sort,setSort]=useState({key:'fantasy_points',desc:true}),[notice,setNotice]=useState('');
 const [saved,setFavorites]=useStored(favoriteKey(season,week),[]),favorites=validateFavorites(saved),ids=favorites.map(f=>f.id);
 const [mode,setMode]=useStored('bowser:lhq:waivers:mode','native'),[annual,setAnnual]=useStored('bowser:lhq:waivers:annual',100),[remaining,setRemaining]=useStored('bowser:lhq:waivers:remaining',''),[hiddenSources,setHiddenSources]=useStored('bowser:lhq:waivers:sources',[]),[storedHistory,setHistory]=useStored('bowser:lhq:waivers:history',10),[widths,setWidths]=useStored('bowser:lhq:waivers:widths',{}),[storedMetrics,setMetrics]=useStored('bowser:lhq:waivers:metrics',{usage:'snaps',rushing:'rush_attempts',receiving:'targets'}),[extra,setExtra]=useStored('bowser:lhq:waivers:stats',false),[storedResearchTeam,setResearchTeam]=useStored('bowser:lhq:waivers:researchTeam','');
 const history=[5,8,10,18].includes(storedHistory)?storedHistory:10,metrics=Object.fromEntries(Object.entries({usage:'snaps',rushing:'rush_attempts',receiving:'targets'}).map(([key,fallback])=>[key,TREND_METRICS[storedMetrics[key]]?storedMetrics[key]:fallback]));
 const result=useJson(`/api/v1/waivers?${new URLSearchParams({season,week,weeks,scoring,trendWeeks:history})}`,revision),all=result.data?.rows||[],meta=result.data?.meta||{},sources=meta.sources||[];
 const budgets={annual:Number(annual)>0?Number(annual):null,remaining:remaining!==''&&Number(remaining)>0?Number(remaining):null};
 const researchTeam=yahoo?.teams?.some(t=>t.key===storedResearchTeam)?storedResearchTeam:yahoo?.teams?.[0]?.key||'',pickups=useLeaguePickups(season,leagueKeyFromTeam(researchTeam));
 const entry=r=>({id:playerKey(r),profileId:r.playerId||null,name:r.name,position:r.position,team:r.team,bid:null,notes:''});
 const toggle=r=>setFavorites(f=>validateFavorites(f).some(x=>x.id===playerKey(r))?validateFavorites(f).filter(x=>x.id!==playerKey(r)):[...validateFavorites(f),entry(r)]);
 const update=(id,key,value)=>setFavorites(f=>validateFavorites(validateFavorites(f).map(x=>x.id===id?{...x,[key]:value}:x)));
 const definitions=waiverColumns(sources,metrics).filter(c=>!['passing','rushing','receiving'].includes(c.group)||extra).filter(c=>!c.source||!hiddenSources.includes(c.source.id));
 const widthsByKey={favorite:33,name:141,position:47,team:56,adds:77,drops:77,rosterPct:72,startPct:68,games_played:47,snaps:62,snap_pct:68,snap_trend:150,fantasy_points:62,position_finish:78};
 const columns=[{key:'pickup',label:'Pick',group:'identity',width:58,kind:'identity',sortable:false,pin:'left',groupLabel:'Player',render:r=><MarkPickupButton row={r} name={r.name} pickups={pickups}/>},...definitions].map(c=>({...c,width:c.kind==='rank'?106:c.kind==='faab'?118:widthsByKey[c.key]||c.width,groupLabel:{identity:'Player',rank:'Positional waiver ranks',faab:'Source FAAB bids',market:'Market activity',usage:'Usage',fantasy:'Fantasy'}[c.group]||c.group,pin:c.group==='identity'?'left':c.group==='fantasy'?'right':undefined,
 value:r=>c.kind==='faab'?faabValue(r.faab?.[c.source.id],mode,budgets)?.low:columnValue(r,c,ids),
 exportValue:r=>c.kind==='faab'?`${formatFAAB(faabValue(r.faab?.[c.source.id],mode,budgets))} (${r.faab?.[c.source.id]?.budgetBasis||'basis unknown'})`:columnValue(r,c,ids),
 color:c.kind==='rank'?'#d8d8d8':undefined,help:c.source?`${c.source.label}: ${c.source.rankScoring||c.source.scoring}; ${c.source.coverageNote||''}; ${c.source.publishedAt||c.source.capturedAt}`:undefined,
 render:r=>{const value=columnValue(r,c,ids);if(c.key==='pickup')return <MarkPickupButton row={r} name={r.name} pickups={pickups}/>;if(c.kind==='favorite')return <button className={`lhq-star ${ids.includes(playerKey(r))?'active':''}`} aria-label={`Favorite ${r.name}`} onClick={()=>toggle(r)}>{ids.includes(playerKey(r))?'★':'☆'}</button>;if(c.key==='name')return <PlayerName row={r} onOpen={onOpen} marked={ids.includes(playerKey(r))}/>;if(c.kind==='identity')return value||'—';if(c.kind==='rank')return value==null?'':<a style={{color:'inherit'}} href={c.source.rankUrl} target="_blank" rel="noreferrer" title={c.source.rankMethod}>{value===1?<strong>1</strong>:value}</a>;if(c.kind==='faab'){const bid=faabValue(r.faab?.[c.source.id],mode,budgets);return bid?<a className="lhq-two-line" href={c.source.faabUrl} target="_blank" rel="noreferrer"><b>{formatFAAB(bid)}</b><small>{['annual','remaining'].includes(bid.budgetBasis)?bid.budgetBasis:'basis unknown'}{bid.converted?' · converted':''}</small></a>:'';}if(c.kind==='trend')return <Bars history={r.stats?.trends} metric={c.metric} domain={meta.trendDomains?.[c.metric]} color={COLORS[c.group]}/>;if(c.key==='position_finish')return value==null?'—':`${r.position}${value}`;return <span style={{color:c.group==='fantasy'?COLORS.fantasy:undefined}}>{value==null?'—':`${fmt(value,c.decimal||c.percent?1:0)}${c.percent?'%':''}`}</span>;}}));
 const best=r=>{const values=Object.values(r.rankings||{}).map(v=>v.rank).filter(Number.isFinite);return values.length?Math.min(...values):null;};
 const filtered=all.filter(r=>(pool!=='favorites'||ids.includes(playerKey(r)))&&(pool!=='faab'||Object.keys(r.faab||{}).length)&&(position==='All'||r.position===position||position==='FLEX'&&['RB','WR','TE'].includes(r.position))&&(!teams.length||teams.includes(r.team))&&r.name.toLowerCase().includes(search.toLowerCase())&&inRanges(r,ranges,{rank:best,roster:r=>r.activity?.rosterPct,snaps:r=>r.stats?.snaps,points:r=>r.stats?.fantasy_points})),rows=sortRows(filtered,sort,columns);
 const committed=favorites.reduce((n,f)=>n+(f.bid||0),0);
 const favoritePanel=<><div className="lhq-summary">Committed ${fmt(committed)} · Remaining {remaining===''?'—':`$${fmt(Number(remaining)-committed)}`} · {favorites.length} targets</div>{<table className="lhq-favorite-table"><thead><tr><th>Player</th><th>Pos</th><th>Bid $</th><th>Notes</th><th/></tr></thead><tbody>{favorites.map(f=><tr key={f.id}><td><PlayerName row={{...f,playerId:f.profileId}} onOpen={onOpen}/></td><td>{f.position}</td><td><input aria-label={`${f.name} bid`} type="number" min="0" value={f.bid??''} onChange={e=>update(f.id,'bid',e.target.value===''?null:Number(e.target.value))}/></td><td><input aria-label={`${f.name} notes`} value={f.notes} onChange={e=>update(f.id,'notes',e.target.value)}/></td><td><button aria-label={`Remove ${f.name}`} onClick={()=>setFavorites(favorites.filter(x=>x.id!==f.id))}>×</button></td></tr>)}</tbody></table>}{!favorites.length&&<p className="lhq-note">Star a player in the pool, or use ⇄ to add every filtered player.</p>}<div className="lhq-panel-actions"><button className="lhq-mini lhq-outline" onClick={()=>setFavorites(favorites.map(f=>({...f,bid:null,notes:''})))}>Reset bids</button><button className="lhq-mini" onClick={()=>setNotice('Claim drafts saved on this device. No waiver claim was submitted to Yahoo.')}>♥ Save claims</button></div>{notice&&<p role="status" className="lhq-note">{notice}</p>}</>;
 const waiverOptions=<><p className="lhq-note">Top waiver options use the selected position filter, existing source ranks, and public market activity.</p><div className="lhq-research-list">{sortRows(all.filter(r=>position==='All'||r.position===position||position==='FLEX'&&['RB','WR','TE'].includes(r.position)),{key:'fantasy_points',desc:true},columns).slice(0,12).map(r=><div className="lhq-research-player" key={playerKey(r)}><div><PlayerName row={r} onOpen={onOpen}/><small>{r.position} · {r.team} · best rank {best(r)??'—'}</small></div><span>{r.activity?.rosterPct==null?'—':`${fmt(r.activity.rosterPct,1)}%`}</span><small>{r.activity?.startPct==null?'—':`${fmt(r.activity.startPct,1)}% start`}</small></div>)}</div>{researchTeam&&<LeagueResearchPanel yahoo={yahoo} season={season} rows={rows} selectedTeamKey={researchTeam} onTeamChange={setResearchTeam} title="Waivers league context" onOpen={onOpen}/>}</>;
 const sourcePanel=<table><thead><tr><th>Source</th><th>Ranks</th><th>FAAB</th><th>Show</th></tr></thead><tbody>{sources.map(s=><tr key={s.id}><td><Tip text={s.coverageNote}><a href={s.rankUrl||s.faabUrl} target="_blank" rel="noreferrer">{s.label}</a></Tip></td><td>{s.rankCount}</td><td>{s.faabCount}</td><td><input type="checkbox" aria-label={`Show ${s.label}`} checked={!hiddenSources.includes(s.id)} onChange={e=>setHiddenSources(h=>e.target.checked?h.filter(x=>x!==s.id):[...h,s.id])}/></td></tr>)}</tbody></table>;
 const settings=<><Field label="Annual budget $"><input type="number" min="1" value={annual} onChange={e=>setAnnual(Number(e.target.value))}/></Field><Field label="Remaining budget $"><input type="number" min="0" value={remaining} onChange={e=>setRemaining(e.target.value)} placeholder="Unknown"/></Field><Field label="Stats weeks"><input value={weeks} onChange={e=>setWeeks(e.target.value)} aria-label="Waiver stats weeks"/></Field>{Object.keys(metrics).map(g=><MetricSelect key={g} label={`${g} trend`} value={metrics[g]} onChange={v=>setMetrics({...metrics,[g]:v})}/>)}<label><input type="checkbox" checked={extra} onChange={e=>setExtra(e.target.checked)}/>Passing, rushing & receiving stats</label></>;
 return <Shell page="waivers" panels={[{id:'favorites',title:`Favorites (${favorites.length})`,content:favoritePanel},{id:'options',title:'Waiver options',content:waiverOptions},{id:'league',title:'Yahoo league research',content:<LeagueResearchPanel yahoo={yahoo} season={season} rows={rows} selectedTeamKey={researchTeam} onTeamChange={setResearchTeam} title="Waivers league context" onOpen={onOpen}/>},{id:'sources',title:'Sources',content:sourcePanel},{id:'settings',title:'Filters & settings',content:settings}]} defaultPanel="favorites" stacks={<><Picker label="Season" value={season} onChange={v=>setSeason(Number(v))} options={[2025,2026]}/><Picker label="Waiver week" value={week} onChange={v=>setWeek(Number(v))} options={Array.from({length:18},(_,i)=>[i+1,`W${i+1}`])}/><Picker label="Stats week(s)" value={weeks} onChange={setWeeks} options={[[weeks,`W${weeks}`],...Array.from({length:22},(_,i)=>[String(i+1),`W${i+1}`]).filter(v=>v[0]!==weeks)]}/><Picker label="Scoring" value={scoring} onChange={setScoring} options={SCORING}/></>} actions={<><small>SHOW <input type="number" min="0" aria-label="Displayed row limit" value={rowLimit===''?rows.length:rowLimit} onChange={e=>setRowLimit(e.target.value)}/> PLAYERS USING</small><Picker label="Sort" value={sort.key} onChange={key=>setSort({key,desc:true})} options={columns.filter(c=>c.sortable!==false).map(c=>[c.key,`${c.groupLabel||c.group||''} · ${c.label}`])}/><button className="lhq-mini" onClick={()=>setRevision(n=>n+1)}>Refresh</button></>} sources={<><Source label="WAIVER SOURCES" title={`${sources.length} sources · W${week}`} detail={`Updated: ${stamp(meta.capturedAt)}`} help="Published positional ordinal ranks and source-native FAAB bids. Each source column links to its evidence."/><Source label="YAHOO RESEARCH" title={researchTeam?'Owned league selected':'Unavailable'} detail={researchTeam?'private reads on demand':'connect Yahoo to enable'} help="League availability and ownership are read only, bounded, and never inferred from missing pages."/><Source label="FAAB DISPLAY" title={MODES.find(m=>m[0]===mode)?.[1]||MODES[0][1]} detail={`Budget $${annual} annual · ${remaining===''?'unknown':`$${remaining}`} remaining`} onClick={()=>setMode(MODES[(MODES.findIndex(m=>m[0]===mode)+1)%3][0])} help="Conversions require a stated budget basis. Unknown bases retain native source units."/><button className="lhq-icon" aria-label="Download waivers CSV" onClick={()=>csvDownload(`waivers-${season}-w${week}.csv`,columns,rows)}>↓</button></>}>
 <div className="lhq-pool-line"><Pool tabs={[{key:'all',label:'All',count:all.length},{key:'favorites',label:'Favorites',count:favorites.length},{key:'faab',label:'Has FAAB bid',count:all.filter(r=>Object.keys(r.faab||{}).length).length}]} value={pool} onChange={setPool} transfer={()=>setFavorites(validateFavorites([...favorites,...filtered.filter(r=>!ids.includes(playerKey(r))).map(entry)]))}/><Ranges definitions={[["rank","Best rank"],["roster","Roster %"],["snaps","Snaps"],["points","FPTS"]]} values={ranges} onChange={setRanges}/></div>
 <div className="lhq-strip"><Chips values={['All',...POSITIONS,'FLEX']} value={position} onChange={setPosition}/><Chips label="TREND WEEKS" values={[5,8,10,18]} value={history} onChange={setHistory}/><Tiles tiles={[...new Set(all.map(r=>r.team).filter(Boolean))].sort().map(t=>({key:t,title:t,detail:`${all.filter(r=>r.team===t).length} players`,sub:(()=>{const known=all.filter(r=>r.team===t).map(r=>r.activity?.adds).filter(Number.isFinite);return known.length?`${fmt(known.reduce((a,b)=>a+b,0))} observed adds`:'Adds unavailable';})()}))} selected={teams} onClear={()=>setTeams([])} onToggle={t=>setTeams(a=>a.includes(t)?a.filter(x=>x!==t):[...a,t])}/></div>
 <Status loading={result.loading} error={result.error}/><Grid columns={columns} rows={rowLimit===''?rows:rows.slice(0,Math.max(0,Number(rowLimit)||0))} rowKey={playerKey} search={search} onSearch={setSearch} sort={sort} onSort={setSort} reset={()=>{setRowLimit('');setSearch('');setPosition('All');setTeams([]);setRanges({});setPool('all');}} widths={widths} resizable onResize={(k,v)=>setWidths(w=>({...w,[k]:v}))} groupContent={{rank:<small>lower is better</small>,faab:<small>{MODES.find(m=>m[0]===mode)?.[1]}</small>}}/><div className="lhq-footnote"><span>{rowLimit===''?rows.length:Math.min(rows.length,Math.max(0,Number(rowLimit)||0))} shown · {rows.length} of {all.length} targets · Waivers W{week} · statistics W{weeks}</span><span>Ranks & FAAB captured {stamp(meta.capturedAt)} · market activity has separate capture dates</span></div>
 </Shell>;
}
