import {useState} from 'react';
import {Field,Picker,PlayerName,Pool,Shell,Source,Status,Tip} from './shared.jsx';
import {fmt,sortRows,stamp} from './model.js';
export function AccountTable({columns,rows,title,note,empty,group=true,onOpen}){
 const [sort,setSort]=useState(null),[widths,setWidths]=useState({});const ordered=sort?sortRows(rows,sort,columns):rows;
 const resize=(e,c)=>{e.preventDefault();const x=e.clientX,w=e.currentTarget.parentElement.getBoundingClientRect().width;const move=e=>setWidths(old=>({...old,[c.key]:Math.max(40,w+e.clientX-x)}));const end=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',end);document.removeEventListener('pointercancel',end);};document.addEventListener('pointermove',move);document.addEventListener('pointerup',end);document.addEventListener('pointercancel',end);};
 return <div className="lhq-account-scroll" role="region" aria-label={`${title} scrollable table`} tabIndex={0}><table className="lhq-grid lhq-account-table"><colgroup>{columns.map(c=><col key={c.key} style={{width:widths[c.key]||c.width}}/>)}</colgroup><thead>{group&&<tr className="lhq-group-band"><th colSpan={columns.length}><div>{title}<small>{note}</small></div></th></tr>}<tr className="lhq-leaf-band">{columns.map(c=><th key={c.key} aria-sort={sort?.key===c.key?(sort.desc?'descending':'ascending'):'none'} className={sort?.key===c.key?'sorted':''}><Tip text={c.help||c.label}><button onClick={()=>setSort({key:c.key,desc:sort?.key===c.key?!sort.desc:true})}>{c.label}{sort?.key===c.key?(sort.desc?' ▼':' ▲'):''}</button></Tip><span className="lhq-column-resize" role="separator" aria-label={`Resize ${c.label}`} aria-orientation="vertical" tabIndex={0} onPointerDown={e=>resize(e,c)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const w=e.currentTarget.parentElement.getBoundingClientRect().width;setWidths(old=>({...old,[c.key]:Math.max(40,w+(e.key==='ArrowRight'?4:-4))}));}}}/></th>)}</tr></thead><tbody>{ordered.map((r,i)=><tr key={r.key||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):c.value?c.value(r)??'—':r[c.key]??'—'}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="lhq-account-empty">{empty||`${title} — Data unavailable for this selection.`}</div>}</div>;
}
export const YahooErrors=({y})=><>{[...new Set(Object.values(y.errors))].map(e=><p className="lhq-error" role="alert" key={e}>{e}</p>)}{y.connectionNotice&&<p className="lhq-error">{y.connectionNotice}</p>}</>;
export function YahooConnection({season,setSeason,yahoo:y,onOpen}){
 const [tab,setTab]=useState('leagues'),[search,setSearch]=useState(''),[league,setLeague]=useState('all');const connected=y.status?.connected,verified=Boolean(y.account),status=verified?'Connected':connected?'Authorized · league access unverified':'Not connected';
 const action=<button className={`lhq-button ${connected?'lhq-outline':''}`} disabled={y.busy||!y.status?.configured} onClick={()=>connected?y.load():y.connect()}>{y.busy?'Checking Yahoo…':connected?'Refresh leagues':'Connect Yahoo'}</button>;
 const leagues=y.teams.map(t=>{const l=y.leagues.find(l=>l.key===t.leagueKey),s=y.summaries.find(s=>s.teamKey===t.key);return {key:t.key,leagueKey:t.leagueKey,name:l?.name,size:l?.teams,scoring:l?.scoring,team:t.name,rank:s?.standing?.rank};});
 const rosters=y.teams.flatMap(t=>(y.dashboards[t.key]?.roster?.players||[]).map(p=>({...p,key:`${t.key}:${p.key}`,leagueKey:t.leagueKey,league:y.leagues.find(l=>l.key===t.leagueKey)?.name,ownedTeam:t.name,season})));
 const filtered=a=>a.filter(r=>(league==='all'||r.leagueKey===league)&&`${r.name||''} ${r.team||''} ${r.league||''}`.toLowerCase().includes(search.toLowerCase()));
 const columns=tab==='leagues'?[{key:'name',label:'League',width:'30%'},{key:'size',label:'Size',width:'14%'},{key:'scoring',label:'Scoring',width:'22%'},{key:'team',label:'Your team',width:'20%'},{key:'rank',label:'Standing',width:'14%'}]:tab==='rosters'?[{key:'name',label:'Player',width:'30%',render:r=><PlayerName row={r} onOpen={onOpen}/>},{key:'position',label:'Pos',width:'12%'},{key:'team',label:'Team',width:'12%'},{key:'league',label:'League',width:'30%'},{key:'slot',label:'Slot',width:'16%'}]:[{key:'at',label:'Time',width:'24%',render:r=>stamp(r.at)},{key:'event',label:'Event',width:'40%'},{key:'message',label:'Detail',width:'36%'}];
 const rows=tab==='leagues'?filtered(leagues):tab==='rosters'?filtered(rosters):y.log.map((r,i)=>({...r,key:i}));
 const empty=<><p>Connect Yahoo to test access to your real leagues and rosters. Yahoo will ask you to sign in and approve read access.</p><p>Nothing is written back. Revoke at any time from <a href="https://login.yahoo.com/account/security" target="_blank" rel="noreferrer">Yahoo account security</a>.</p>{action}</>;
 const statusPanel=<><div className="lhq-connection-status"><b style={{background:verified?'#3ecf8e':'#c9d6dc'}}/>{status}</div><table><tbody>{[['Account',verified?'Authorized team owner':'—'],['Scope','fspt-r · read only'],['Session expires',y.status?.expiresAt?stamp(y.status.expiresAt):'—'],['Last sync',y.account?.checkedAt?stamp(y.account.checkedAt):'—'],['Leagues',verified?y.leagues.length:'—']].map(([k,v])=><tr key={k}><td>{k}</td><td>{v}</td></tr>)}</tbody></table><div className="lhq-panel-actions">{connected&&<button className="lhq-mini lhq-outline lhq-danger" disabled={y.busy} onClick={y.disconnect}>Disconnect</button>}{action}</div></>;
 return <Shell page="yahoo" sidebarWidth={400} panels={[{id:'status',title:'Status',shortTitle:'Status',content:statusPanel},{id:'privacy',title:'Privacy & scope',shortTitle:'Privacy',content:<div className="lhq-note"><p>Yahoo permissions are read only: no roster moves, trades, or lineup changes.</p><p>Tokens stay encrypted in Secure, HttpOnly cookies for an eight-hour browser session.</p><p>Private league data stays in memory and is never saved to the public player warehouse or browser storage.</p></div>},{id:'unlocks',title:'What unlocks',shortTitle:'Unlocks',content:<table><thead><tr><th>Page</th><th>With Yahoo</th></tr></thead><tbody>{[['League Hub','Lineups, matchups, health'],['Waivers','League free-agent research'],['Exposure','Shared roster holdings']].map(([a,b])=><tr key={a}><td>{a}</td><td>{b}</td></tr>)}</tbody></table>},{id:'filters',title:'Filters & settings',shortTitle:'Filters',content:<><Field label="Search"><input value={search} onChange={e=>setSearch(e.target.value)}/></Field><Field label="League"><select value={league} onChange={e=>setLeague(e.target.value)}><option value="all">All leagues</option>{y.leagues.map(l=><option key={l.key} value={l.key}>{l.name}</option>)}</select></Field><Field label="Roster week"><select value={y.week} onChange={e=>y.setWeek(e.target.value)}><option value="current">Current in each league</option>{Array.from({length:18},(_,i)=><option key={i+1}>{i+1}</option>)}</select></Field>{connected&&<div className="lhq-panel-actions"><button className="lhq-mini lhq-outline" disabled={y.busy} onClick={y.refresh}>Test token refresh</button><button className="lhq-mini lhq-outline" disabled={y.busy} onClick={y.connect}>Switch account</button></div>}</>}]} stacks={<><Picker label="Season" value={season} onChange={v=>setSeason(Number(v))} options={[2025,2026]}/><div className="lhq-stack"><span>Sport</span><strong>NFL</strong></div><div className="lhq-stack"><span>Yahoo status</span><strong style={{color:verified?'#3ecf8e':'#e8735a'}}>{status}</strong></div><div className="lhq-stack"><span>Scope</span><strong>Private · read only</strong></div></>} actions={action} sources={<><Source label="LEAGUE SOURCE" title="Yahoo Fantasy" detail={verified?`${y.leagues.length} leagues · ${stamp(y.account.checkedAt)}`:'sign in and approve read access'} help="Sign in with the account that owns your fantasy teams. Developer email does not select the teams."/><Source label="ACCESS LEVEL" title="fspt-r · read only" detail="no writes, no lineup changes"/><a className="lhq-source-note" href="https://fantasysports.yahoo.com/" target="_blank" rel="noreferrer">Fantasy data provided by Yahoo Fantasy</a></>}>
 <Pool tabs={[{key:'leagues',label:'Leagues',count:y.leagues.length},{key:'rosters',label:'Rosters',count:Object.keys(y.dashboards).filter(k=>y.dashboards[k].roster).length},{key:'log',label:'Connection log'}]} value={tab} onChange={setTab}/><div className="lhq-strip lhq-oauth-steps">{['Sign in with Yahoo','Approve read access','Return to Bowser','Leagues load'].map((s,i)=><div key={s}><b style={{background:verified||connected&&i<3?'#272f3e':!connected&&i===0||connected&&i===3?'#3ecf8e':'#c9d6dc'}}>{verified||connected&&i<3?'✓':i+1}</b>{s}{i<3&&<span>→</span>}</div>)}</div><YahooErrors y={y}/>{y.status&&!y.status.configured&&<p className="lhq-error">Yahoo connection is not configured on this deployment.</p>}<Status loading={y.busy}/><AccountTable key={tab} title={tab==='leagues'?'Your leagues':tab==='rosters'?'Your rosters':'Connection log'} note="Private · read only" columns={columns} rows={rows} empty={connected?`No ${tab} records returned for this selection. ${verified?'':'League access is not yet verified.'}`:empty}/><p className="lhq-footnote">{y.coverage.loadedTeams} of {y.teams.length} owned-team dashboards loaded · Unavailable fields show —.<a href="#/league-hub">Open League Hub</a></p>
 </Shell>;
}
