// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
import { closeFantasyNewsWindows, FantasyNews, NEWS_LAYOUT_KEY, safeNewsUrl, validateNewsLayout } from '../src/lhq/FantasyNews.jsx';
import { LhqProvider } from '../src/lhq/shared.jsx';

const props = { season: 2026, scoring: 'half', onOpen: vi.fn() };
const source = { sourceName: 'Official Fixture', url: 'https://example.test/report', publishedAt: '2026-09-30T12:00:00Z', sourceType: 'OFFICIAL', isOriginalSource: true, access: 'public', accessLabel: 'Public source', timestampBasis: 'published_at' };
const report = (id, name, category, position, extra = {}) => ({ id, headline: `${name} fixture report`, summary: `${name} exact sourced summary`, fantasyAnalysis: `${name} source context`, category, categories: [category], players: [{ playerId: `id-${id}`, name, team: 'NYG', position }], source: source.sourceName, url: source.url, publishedAt: '2026-09-30T12:00:00Z', updatedAt: '2026-09-30T13:00:00Z', sources: [source], status: 'CONFIRMED', evidence: { kind: 'official_report', label: 'Confirmed report', confidence: 92 }, freshness: { state: 'stale' }, urgency: {score:4,basis:'A confirmed injury may affect the next lineup decision.',method:'AI estimate from public reporting',estimatedAt:'2026-10-01T12:00:00Z'}, ...extra });
const articles = [
  report('a', 'Fixture Alpha', 'injury', 'RB', { injury: { isInjuryRelated: true, bodyPart: 'ankle', practiceStatus: 'DNP', gameStatus: 'OUT', expectedReturn: null }, affectedPlayers:[{name:'Fixture Gamma',team:'NYG',position:'WR',relationship:'potential_beneficiary',impact:'Additional work is possible; the role remains unconfirmed.'}] }),
  report('b', 'Fixture Beta', 'practice', 'QB', { publishedAt: '2026-09-30T11:00:00Z', sources: [{ ...source, sourceName: 'Second Publication', url: 'https://example.test/beta' }],urgency:null }),
  report('c', 'Fixture Gamma', 'playing_time', 'WR', { publishedAt: '2026-09-30T10:00:00Z', players: [{ name: 'Fixture Gamma', team: 'NYG', position: 'WR' }] }),
  report('d', 'Fixture Delta', 'fantasy_news', 'TE', { publishedAt: '2026-09-30T09:00:00Z', evidence: { kind: 'rumor', label: 'Rumor', confidence: null },urgency:{score:99,basis:'bad',method:'AI estimate from public reporting'} }),
];
const payload = (rows = articles, patch = {}) => ({ articles: rows, meta: {version:1,scope:'public_nfl_news',snapshotMode:'durable_active_snapshot',state:'stale',live:false,message:'Public source reports are stale; verify the original reporting.',readAt:'2026-10-01T12:00:00Z',total:rows.length,freshness:{latestSourcePublishedAt:source.publishedAt},coverage:{complete:false,limitations:['Bounded source coverage']},refresh:{schedulerVerified:false,ready:false},sources:[],...patch} });
const reply = data => ({ok:true,json:async()=>data});
const renderPage = (overrides={}) => render(<LhqProvider><FantasyNews {...props} {...overrides}/></LhqProvider>);
const pane = name => screen.getByRole('region',{name,exact:true});
const left = () => pane('Status table');
const rows = () => within(left()).queryAllByRole('button',{name:/^Expand .* fixture report$/});
const ready = () => within(left()).findByRole('button',{name:'Expand Fixture Alpha fixture report'});
const togglePane = name => screen.getByRole('button',{name:`Toggle ${name}`});
const nowClock = (offset=0) => new Date(Date.now()-offset).toISOString();
function yahoo(label='Private Account A') {
  const teams = [1,2,3].map(n=>({key:`461.l.${n}.t.1`,leagueKey:`461.l.${n}`,name:`${label} Team ${n}`}));
  const leagues = [1,2,3].map(n=>({key:`461.l.${n}`,season:2026,name:`${label} League ${n}`}));
  const check = nowClock(60000), dashboards={},research={};
  for (const [index,team] of teams.entries()) {
    dashboards[team.key]={teamKey:team.key,season:2026,week:4,checkedAt:check,roster:{week:4,players:index===0?[{key:'461.p.1',name:'Fixture Alpha',team:'NYG',position:'RB',slot:'RB'}]:[]}};
    research[team.key]={teamKey:team.key,leagueKey:team.leagueKey,season:2026,checkedAt:nowClock(),availability:{status:index===2?'W':'FA',start:0,pageSize:25,nextStart:25,complete:false,checkedAt:check,players:index===0?[]:[{key:'461.p.3',name:'Fixture Gamma',team:'NYG',position:'WR',checkedAt:check},...(index===2?[{key:'461.p.4',name:'Fixture Delta',team:'NYG',position:'TE',checkedAt:check}]:[])]}};
  }
  return {status:{connected:true,expiresAt:new Date(Date.now()+3600000).toISOString()},account:{season:2026,teams,leagues,privateSecret:label},teams,leagues,dashboards,research,coverage:{loadedTeams:3},errors:{}};
}
function childWindow(){const child={closed:false,focus:vi.fn(),postMessage:vi.fn(),close:vi.fn()};child.close.mockImplementation(()=>{child.closed=true;});return child;}
beforeEach(()=>{localStorage.clear();sessionStorage.clear();window.history.replaceState(null,'','/#/fantasy-news');vi.stubGlobal('fetch',vi.fn(async url=>reply(String(url).includes('/schedule')?{data:[{gameId:'NYG-LA',awayTeam:'NYG',homeTeam:'LA',gameday:'2026-10-04',gametime:'13:00'},{gameId:'MIA-MIN',awayTeam:'MIA',homeTeam:'MIN',gameday:'2026-10-04',gametime:'16:05'}]}:payload())));vi.stubGlobal('PointerEvent',MouseEvent);vi.stubGlobal('ResizeObserver',class {observe(){} disconnect(){}});props.onOpen.mockClear();});
afterEach(()=>{cleanup();closeFantasyNewsWindows();vi.restoreAllMocks();vi.unstubAllGlobals();vi.useRealTimers();});

const allTab=()=>fireEvent.click(within(left()).getByRole('tab',{name:/^All/}));
const openLeague=()=>fireEvent.click(togglePane('League desk'));
const pop=id=>{const target=pane(id);fireEvent.click(within(target).getByLabelText(`${id} window menu`));fireEvent.click(within(target).getByRole('button',{name:'Open browser window ↗'}));};
test('v2 independent windows render source data and Status rows expand without selecting Evidence',async()=>{
 renderPage();await ready();expect(rows()).toHaveLength(1);for(const n of ['Wire','Evidence desk','Role board','Feed health & sources'])expect(pane(n)).toBeInTheDocument();expect(screen.queryByRole('region',{name:'League desk'})).not.toBeInTheDocument();allTab();expect(rows()).toHaveLength(4);
 fireEvent.click(within(left()).getByRole('button',{name:'Expand Fixture Beta fixture report'}));expect(left()).toHaveTextContent('Fixture Beta exact sourced summary');expect(pane('Evidence desk')).toHaveTextContent('Fixture Alpha exact sourced summary');fireEvent.click(within(left()).getByRole('button',{name:'Inspect Fixture Beta fixture report'}));expect(pane('Evidence desk')).toHaveTextContent('Fixture Beta exact sourced summary');
 fireEvent.click(within(pane('Evidence desk')).getByRole('button',{name:'Fixture Beta',exact:true}));expect(props.onOpen.mock.calls[0][0]).toMatchObject({player_id:'id-b',season:2026,scoring:'half'});
});
test('Status tabs are keyboard operable; confirmed injuries exclude rumor; daily grades are gaps',async()=>{
 const rumor=report('rumor','Fixture Rumor','injury','RB',{status:'REPORTED',injury:{isInjuryRelated:true,practiceStatus:'DNP'},evidence:{kind:'rumor'}});fetch.mockImplementation(async()=>reply(payload([...articles,rumor])));renderPage();await ready();expect(rows()).toHaveLength(1);const row=within(left()).getByRole('button',{name:'Expand Fixture Alpha fixture report'}).closest('[role=row]');expect(row.querySelectorAll('[title="Per-day practice grades not supplied"]')).toHaveLength(2);expect(row).toHaveTextContent('DNP');
 const tab=within(left()).getByRole('tab',{name:/Injuries/});fireEvent.keyDown(tab,{key:'ArrowRight'});expect(within(left()).getByRole('tab',{name:/Practice/})).toHaveFocus();expect(rows()).toHaveLength(1);fireEvent.keyDown(within(left()).getByRole('tab',{name:/Practice/}),{key:'End'});expect(within(left()).getByRole('tab',{name:/Sources/})).toHaveFocus();
});
test('global Teams + Pos + Status + search intersect all windows; clearing restores',async()=>{
 renderPage();await ready();allTab();fireEvent.click(screen.getByRole('button',{name:'Teams ▾'}));fireEvent.click(screen.getByRole('checkbox',{name:/^NYG \d+$/}));fireEvent.click(screen.getByRole('button',{name:'Pos ▾'}));fireEvent.click(screen.getByRole('checkbox',{name:/^RB \d+$/}));expect(rows()).toHaveLength(1);expect(within(pane('Wire')).queryAllByRole('button',{name:/^Expand/})).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Status ▾'}));fireEvent.click(screen.getByRole('checkbox',{name:/^OUT \d+$/}));fireEvent.change(screen.getByLabelText('Search news'),{target:{value:'missing'}});expect(rows()).toHaveLength(0);expect(pane('Wire')).toHaveTextContent('No reports match');fireEvent.click(screen.getByRole('button',{name:'Clear all filters'}));expect(rows()).toHaveLength(4);
});
test('DFS matchup and source filters affect only Status; week change clears games and no schedule stays unfiltered',async()=>{
 renderPage();await ready();allTab();fireEvent.click(within(left()).getByRole('button',{name:/MIA @ MIN/}));expect(rows()).toHaveLength(0);expect(within(pane('Wire')).getAllByRole('button',{name:/^Expand/})).toHaveLength(4);fireEvent.change(screen.getByLabelText('DFS week'),{target:{value:'5'}});await waitFor(()=>expect(rows()).toHaveLength(4));expect(fetch).toHaveBeenCalledWith('/api/v1/schedule?season=2026&week=5',expect.objectContaining({cache:'no-store'}));fireEvent.change(screen.getByLabelText('News source'),{target:{value:'Second Publication'}});expect(rows()).toHaveLength(1);expect(within(pane('Wire')).getAllByRole('button',{name:/^Expand/})).toHaveLength(4);
});
test('Evidence history, pin and selector remain independent; arrows follow Wire order',async()=>{
 renderPage();await ready();allTab();fireEvent.click(within(left()).getByRole('button',{name:'Inspect Fixture Beta fixture report'}));fireEvent.click(within(pane('Evidence desk')).getByRole('button',{name:'PIN',exact:true}));fireEvent.click(within(left()).getByRole('button',{name:'Inspect Fixture Gamma fixture report'}));expect(screen.getByLabelText('Evidence report')).toHaveValue('b');fireEvent.change(screen.getByLabelText('Evidence report'),{target:{value:'c'}});expect(screen.getByLabelText('Evidence report')).toHaveValue('c');fireEvent.click(screen.getByRole('button',{name:'Evidence back'}));expect(screen.getByLabelText('Evidence report')).toHaveValue('b');fireEvent.click(screen.getByRole('button',{name:'Next evidence'}));expect(screen.getByLabelText('Evidence report')).toHaveValue('c');fireEvent.change(screen.getByLabelText('Search news'),{target:{value:'Alpha'}});expect(screen.getByLabelText('Evidence report')).toHaveValue('c');expect(within(pane('Evidence desk')).getByRole('option',{name:/Outside filters/})).toBeInTheDocument();
});
test('Wire category, group and check sort work; only one inline report expands',async()=>{
 renderPage();await ready();const w=within(pane('Wire'));fireEvent.click(w.getByRole('button',{name:'Role 1'}));expect(w.getAllByRole('button',{name:/^Expand/})).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Next evidence'}));expect(screen.getByLabelText('Evidence report')).toHaveValue('c');fireEvent.click(w.getByRole('button',{name:'All 4'}));fireEvent.click(w.getByRole('button',{name:'By team'}));expect(w.getByText('NYG',{exact:true})).toBeInTheDocument();fireEvent.click(w.getByRole('button',{name:'Checked',exact:true}));fireEvent.click(w.getByRole('button',{name:'Expand Fixture Alpha fixture report'}));fireEvent.click(w.getByRole('button',{name:'Expand Fixture Beta fixture report'}));expect(w.getByRole('button',{name:'Expand Fixture Alpha fixture report'})).toHaveAttribute('aria-expanded','false');expect(w.getByRole('button',{name:'Expand Fixture Beta fixture report'})).toHaveAttribute('aria-expanded','true');
});
test('window scales and page scales clamp, preserve widths and store only validated preferences',async()=>{
 renderPage();await ready();const width=screen.getByRole('separator',{name:'Resize Status table'}).getAttribute('aria-valuenow');for(let i=0;i<9;i++)fireEvent.click(screen.getByRole('button',{name:'Increase Wire text'}));expect(pane('Wire').style.getPropertyValue('--t')).toBe('1.5');expect(pane('Evidence desk').style.getPropertyValue('--t')).toBe('1');expect(pane('Wire').style.getPropertyValue('--k')).toBe('0.5');for(let i=0;i<12;i++)fireEvent.click(screen.getByRole('button',{name:'Increase page text'}));fireEvent.click(screen.getByRole('button',{name:'Compact',exact:true}));expect(screen.getByRole('main').style.getPropertyValue('--p')).toBe('1.4');expect(screen.getByRole('main').style.getPropertyValue('--d')).toBe('0.84');expect(screen.getByRole('separator',{name:'Resize Status table'})).toHaveAttribute('aria-valuenow',width);const saved=JSON.parse(localStorage.getItem(NEWS_LAYOUT_KEY));expect(saved.ts.wire).toBe(1.5);expect(JSON.stringify(saved)).not.toContain('Fixture');
});
test('strict layout shape rejects payloads and unknown keys, clamps fractions/widths/scales',()=>{
 const v=validateNewsLayout({version:2,leftW:99999,pfW:-2,pageScale:9,ts:{wire:-1,private:'payload'},colFr:[NaN,999],rowFr:[-1],colW:{name:999,private:500},order:['wire','wire','private'],show:{wire:false,private:true},articles,account:yahoo(),tab:'bad'});expect(v.leftW).toBe(1100);expect(v.pfW).toBe(400);expect(v.ts.wire).toBe(.8);expect(v.colFr.slice(0,2)).toEqual([1,5]);expect(v.rowFr[0]).toBe(.3);expect(v.colW).toEqual({name:420});expect(v.order).toEqual(['wire','evidence','role','health']);expect(JSON.stringify(v)).not.toMatch(/Fixture|Private|payload/);expect(v.tab).toBe('injuries');expect(validateNewsLayout({version:1}).version).toBe(2);
});
test('drag and keyboard resizing persist, sort stays DESC-first, reset returns geometry',async()=>{
 renderPage();await ready();allTab();const grip=screen.getByRole('separator',{name:'Resize Player column'});fireEvent.pointerDown(grip,{clientX:100});fireEvent.pointerMove(document,{clientX:140});fireEvent.pointerUp(document);expect(grip).toHaveAttribute('aria-valuenow','170');fireEvent.keyDown(grip,{key:'ArrowRight'});expect(grip).toHaveAttribute('aria-valuenow','178');fireEvent.click(within(left()).getByRole('button',{name:'Player',exact:true}));expect(within(left()).getByRole('columnheader',{name:/Player/})).toHaveAttribute('aria-sort','descending');fireEvent.click(within(left()).getByRole('button',{name:'Player ▾'}));expect(within(left()).getByRole('columnheader',{name:/Player/})).toHaveAttribute('aria-sort','ascending');const g=screen.getByRole('separator',{name:'Resize center column 1'});fireEvent.keyDown(g,{key:'ArrowRight'});expect(JSON.parse(localStorage.getItem(NEWS_LAYOUT_KEY)).colFr[0]).toBe(1.1);fireEvent.keyDown(screen.getByRole('separator',{name:'Resize center row 1'}),{key:'ArrowDown'});expect(JSON.parse(localStorage.getItem(NEWS_LAYOUT_KEY)).rowFr[0]).toBe(1.1);fireEvent.click(screen.getByRole('button',{name:'Columns',exact:true}));expect(JSON.parse(localStorage.getItem(NEWS_LAYOUT_KEY)).colFr[0]).toBe(1);fireEvent.click(screen.getByRole('button',{name:'Reset layout'}));expect(JSON.parse(localStorage.getItem(NEWS_LAYOUT_KEY)).colW).toEqual({});
});
test('window close, rail, maximize, move and taskbar reopen are independent and persist',async()=>{
 const view=renderPage();await ready();fireEvent.click(screen.getByRole('button',{name:'Collapse Status table'}));expect(screen.queryByRole('region',{name:'Status table'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Expand Status table'}));fireEvent.click(screen.getByRole('button',{name:'Maximize Wire'}));expect(screen.queryByRole('region',{name:'Evidence desk'})).not.toBeInTheDocument();expect(left()).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Restore Wire'}));fireEvent.click(screen.getByRole('button',{name:'Move Evidence desk left'}));expect(JSON.parse(localStorage.getItem(NEWS_LAYOUT_KEY)).order[0]).toBe('evidence');fireEvent.click(screen.getByRole('button',{name:'Close Wire'}));expect(togglePane('Wire')).toHaveAttribute('aria-pressed','false');view.unmount();renderPage();await ready();expect(screen.queryByRole('region',{name:'Wire'})).not.toBeInTheDocument();fireEvent.click(togglePane('Wire'));expect(pane('Wire')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Stack',exact:true}));expect(screen.queryByRole('separator',{name:'Resize center column 1'})).not.toBeInTheDocument();
});
test('role board uses returned affectedPlayers and hides unsourced curated chains',async()=>{
 renderPage();await ready();expect(pane('Role board')).toHaveTextContent('Fixture Gamma');expect(pane('Role board')).not.toHaveTextContent('Breece Hall');fireEvent.click(within(pane('Role board')).getByRole('button',{name:'Fixture Alpha fixture report'}));expect(pane('Role board')).toHaveTextContent('Additional work is possible');fireEvent.click(within(pane('Role board')).getByRole('button',{name:'Inspect role NYG RB'}));expect(screen.getByLabelText('Evidence report')).toHaveValue('a');
});
test('health names all unsupplied fields, sources scope Status only and unknown clocks stay distinct',async()=>{
 const unknown={...articles[0],publishedAt:null,publishedDate:null,publishedAtRaw:null,updatedAt:null,urgency:null,evidence:{confidence:null},players:[{name:'Fixture Alpha',team:'NYG',position:'RB'}],affectedPlayers:[],checkedAt:nowClock()};fetch.mockImplementation(async()=>reply(payload([unknown,articles[1]])));renderPage();await ready();fireEvent.click(within(left()).getByRole('button',{name:'Inspect Fixture Alpha fixture report'}));expect(pane('Evidence desk')).toHaveTextContent('publication age unknown');expect(pane('Evidence desk')).toHaveTextContent('record updated Unavailable');for(const k of ['urgency','confidence','affectedPlayers','playerId','per-day practice grades'])expect(pane('Feed health & sources')).toHaveTextContent(`${k}: not supplied`);fireEvent.click(within(pane('Feed health & sources')).getByRole('button',{name:/Second Publication/}));expect(rows()).toHaveLength(1);expect(within(pane('Wire')).getAllByRole('button',{name:/^Expand/})).toHaveLength(2);
});
test('league desk disconnected state has no fixture teams and no private persistence',async()=>{
 renderPage();await ready();openLeague();expect(pane('League desk')).toHaveTextContent('Yahoo not connected');expect(pane('League desk')).not.toHaveTextContent('LOEG');expect(within(pane('League desk')).getByRole('link',{name:/Open Yahoo/})).toHaveAttribute('href','#/yahoo');expect(localStorage.getItem(NEWS_LAYOUT_KEY)).not.toMatch(/Fixture|Yahoo|summary/);
});
test('league tabs, matchup, rosters, availability and news hits use authorized observations',async()=>{
 renderPage({yahoo:yahoo()});await ready();openLeague();const l=within(pane('League desk'));expect(l.getAllByRole('tab',{name:/Private Account A League/})).toHaveLength(3);expect(pane('League desk')).toHaveTextContent('Fixture Alpha');expect(pane('League desk')).toHaveTextContent('Opponent player rosters');fireEvent.click(l.getByRole('tab',{name:/^Rosters/}));expect(l.getByTitle('Fixture Alpha · OUT')).toBeInTheDocument();fireEvent.click(l.getByRole('tab',{name:/News hits/}));expect(pane('League desk')).toHaveTextContent('Fixture Alpha fixture report');fireEvent.click(l.getByRole('tab',{name:/Private Account A League 2/}));fireEvent.click(l.getByRole('tab',{name:/Free agents/}));expect(pane('League desk')).toHaveTextContent('Fixture Gamma');expect(pane('League desk')).not.toHaveTextContent('Fixture Beta');expect(pane('League desk')).toHaveTextContent('absence does not imply owned');expect(localStorage.getItem(NEWS_LAYOUT_KEY)).not.toMatch(/Private Account|461\.l|Fixture/);
});
test('stale or unknown Yahoo observation age is explicit; expiry and account replacement clear context',async()=>{
 const y=yahoo();delete y.dashboards[y.teams[0].key].checkedAt;y.research[y.teams[1].key].availability.stale=true;const v=renderPage({yahoo:y});await ready();expect(left().querySelector('.cc-league-badge').title).toContain('capture age unverified');openLeague();v.rerender(<LhqProvider><FantasyNews {...props} yahoo={{...y,status:{connected:true,expiresAt:new Date(Date.now()-1).toISOString()}}}/></LhqProvider>);expect(pane('League desk')).toHaveTextContent('Yahoo not connected');expect(pane('League desk')).not.toHaveTextContent('Private Account');
});
test('malformed feed scope and unsafe source links fail closed',async()=>{
 expect(safeNewsUrl('javascript:alert(1)')).toBeNull();expect(safeNewsUrl('https://example.test/report')).toBe('https://example.test/report');fetch.mockResolvedValue(reply({articles,meta:{scope:'private_yahoo'}}));renderPage();expect(await screen.findByRole('alert')).toHaveTextContent('unexpected response');expect(rows()).toHaveLength(0);
});
test('failed refresh retains last good feed labeled stale, then recovers',async()=>{
 renderPage();await ready();fetch.mockRejectedValueOnce(new Error('Temporary read failure'));fireEvent.click(screen.getByRole('button',{name:'Refresh feed'}));expect(await screen.findByRole('alert')).toHaveTextContent('Last successful feed retained');expect(rows()).toHaveLength(1);expect(pane('Feed health & sources')).toHaveTextContent('stale');fireEvent.click(screen.getByRole('button',{name:'Refresh feed'}));await waitFor(()=>expect(screen.queryByRole('alert')).not.toBeInTheDocument());
});
test('blocked storage still allows controls',async()=>{
 vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('blocked')});renderPage();await ready();expect(screen.getByRole('alert')).toHaveTextContent('Layout could not be saved');fireEvent.click(screen.getByRole('button',{name:'Collapse Status table'}));fireEvent.click(screen.getByRole('button',{name:'Expand Status table'}));expect(rows()).toHaveLength(1);
});
test('popups are deduplicated, blocked popup stays docked, dock messages authenticate source',async()=>{
 const child=childWindow(),open=vi.spyOn(window,'open').mockReturnValueOnce(null).mockReturnValue(child);renderPage();await ready();pop('Evidence desk');expect(await screen.findByRole('alert')).toHaveTextContent('browser blocked');expect(pane('Evidence desk')).toHaveTextContent('Fixture Alpha');pop('Evidence desk');expect(pane('Evidence desk')).toHaveTextContent('Open in browser window');fireEvent.click(within(pane('Evidence desk')).getByRole('button',{name:'Focus window'}));expect(open).toHaveBeenCalledTimes(2);expect(child.focus).toHaveBeenCalled();act(()=>window.dispatchEvent(new MessageEvent('message',{origin:'https://attacker.test',source:child,data:{type:'bowser-fantasy-news-dock',pane:'evidence'}})));expect(child.close).not.toHaveBeenCalled();act(()=>window.dispatchEvent(new MessageEvent('message',{origin:window.location.origin,source:child,data:{type:'bowser-fantasy-news-dock',pane:'evidence'}})));expect(child.close).toHaveBeenCalled();expect(pane('Evidence desk')).toHaveTextContent('Fixture Alpha');expect(open.mock.calls[1][0]).not.toMatch(/Private|summary/);for(const [m] of child.postMessage.mock.calls){expect(Object.keys(m).sort()).toEqual(m.type==='bowser-fantasy-news-selection'?['articleId','hours','type']:['filters','type']);expect(JSON.stringify(m)).not.toMatch(/Private Account|461\.l|summary/);}
});
test('logout closes detached league window and removes private context',async()=>{
 const child=childWindow();vi.spyOn(window,'open').mockReturnValue(child);const v=renderPage({yahoo:yahoo()});await ready();openLeague();pop('League desk');v.rerender(<LhqProvider><FantasyNews {...props} yahoo={{account:null,status:{connected:false}}}/></LhqProvider>);expect(child.close).toHaveBeenCalledTimes(1);expect(pane('League desk')).toHaveTextContent('Yahoo not connected');
});
test('standalone window accepts only same-origin opener public IDs; never writes layout',async()=>{
 window.history.replaceState(null,'','/#/fantasy-news?pane=evidence&popout=1');const opener=childWindow();vi.stubGlobal('opener',opener);renderPage();await within(pane('Evidence desk')).findByText('Fixture Alpha exact sourced summary');expect(localStorage.getItem(NEWS_LAYOUT_KEY)).toBeNull();const before=fetch.mock.calls.length;act(()=>window.dispatchEvent(new MessageEvent('message',{origin:'https://attacker.test',source:opener,data:{type:'bowser-fantasy-news-selection',hours:24,articleId:'b'}})));expect(fetch).toHaveBeenCalledTimes(before);expect(screen.getByLabelText('Evidence report')).toHaveValue('a');act(()=>window.dispatchEvent(new MessageEvent('message',{origin:window.location.origin,source:opener,data:{type:'bowser-fantasy-news-selection',hours:24,articleId:'b'}})));await waitFor(()=>expect(fetch.mock.calls.some(([url])=>url.includes('hours=24'))).toBe(true));expect(localStorage.getItem(NEWS_LAYOUT_KEY)).toBeNull();
});
test('window registry poll recovers closed and orphaned browser windows',async()=>{
 const child=childWindow();vi.spyOn(window,'open').mockReturnValue(child);renderPage();await ready();pop('Evidence desk');const dispatch=vi.spyOn(window,'dispatchEvent').mockImplementation(()=>true);act(()=>closeFantasyNewsWindows());dispatch.mockRestore();await waitFor(()=>expect(pane('Evidence desk')).toHaveTextContent('Fixture Alpha'),{timeout:2200});
});
test('60-second stored-feed polling can be paused without starting ingestion',async()=>{
 renderPage();await ready();vi.useFakeTimers();fireEvent.click(screen.getByRole('checkbox',{name:'60s'}));fireEvent.click(screen.getByRole('checkbox',{name:'60s'}));const before=fetch.mock.calls.filter(([u])=>u.includes('fantasy-news')).length;await act(async()=>{await vi.advanceTimersByTimeAsync(60000)});expect(fetch.mock.calls.filter(([u])=>u.includes('fantasy-news')).length).toBe(before+1);fireEvent.click(screen.getByRole('checkbox',{name:'60s'}));await act(async()=>{await vi.advanceTimersByTimeAsync(60000)});expect(fetch.mock.calls.filter(([u])=>u.includes('fantasy-news')).length).toBe(before+1);expect(fetch.mock.calls.every(([,opts])=>!opts.method||opts.method==='GET')).toBe(true);
});

test('returned but unresolved roster occupant is never reported as an empty slot',async()=>{
 const y=yahoo();const d=y.dashboards[y.teams[0].key];d.settings={rosterPositions:[{position:'RB',count:2}]};delete d.roster.players[0].team;
 renderPage({yahoo:y});await ready();openLeague();expect(pane('League desk')).toHaveTextContent('Player identity unavailable');expect(within(pane('League desk')).getAllByText('empty slot')).toHaveLength(1);
 fireEvent.click(within(pane('League desk')).getByRole('tab',{name:/^Rosters/}));expect(within(pane('League desk')).getByTitle('Player identity unavailable · —')).toBeInTheDocument();expect(within(pane('League desk')).getAllByText('empty',{exact:true})).toHaveLength(1);
});
test('global status uses public designation in League desk rather than Yahoo badge',async()=>{
 const y=yahoo();y.dashboards[y.teams[0].key].roster.players[0].status='Q';renderPage({yahoo:y});await ready();openLeague();fireEvent.click(screen.getByRole('button',{name:'Status ▾'}));fireEvent.click(screen.getByRole('checkbox',{name:/^OUT \d+$/}));const player=within(pane('League desk')).getByRole('button',{name:'Fixture Alpha',exact:true});expect(player.parentElement).not.toHaveClass('cc-dimmed');expect(pane('League desk')).toHaveTextContent('OUT');
});
test('filter-only changes do not resend Evidence selection to independent popouts',async()=>{
 const child=childWindow();vi.spyOn(window,'open').mockReturnValue(child);renderPage();await ready();pop('Evidence desk');act(()=>window.dispatchEvent(new MessageEvent('message',{origin:window.location.origin,source:child,data:{type:'bowser-fantasy-news-ready',pane:'evidence'}})));child.postMessage.mockClear();fireEvent.change(screen.getByLabelText('Search news'),{target:{value:'Beta'}});expect(child.postMessage.mock.calls.length).toBeGreaterThan(0);expect(child.postMessage.mock.calls.every(([m])=>m.type==='bowser-fantasy-news-filters')).toBe(true);
});
test('child retains pending league ordinal through Yahoo account hydration without clearing parent scope',async()=>{
 window.history.replaceState(null,'','/#/fantasy-news?pane=wire&popout=1');const opener=childWindow();vi.stubGlobal('opener',opener);const v=renderPage({yahoo:{status:{connected:false}}});await within(pane('Wire')).findByRole('button',{name:'Expand Fixture Alpha fixture report'});
 const filters={search:'',teams:[],pos:[],status:[],league:{mode:'mine-league',index:0}};act(()=>window.dispatchEvent(new MessageEvent('message',{origin:window.location.origin,source:opener,data:{type:'bowser-fantasy-news-filters',filters}})));expect(opener.postMessage.mock.calls.filter(([m])=>m.type==='bowser-fantasy-news-filters')).toHaveLength(0);
 v.rerender(<LhqProvider><FantasyNews {...props} yahoo={yahoo()}/></LhqProvider>);await waitFor(()=>expect(within(pane('Wire')).getAllByRole('button',{name:/^Expand/})).toHaveLength(1));expect(screen.getByRole('button',{name:'Leagues 1 ▾'})).toBeInTheDocument();for(const [m] of opener.postMessage.mock.calls.filter(([m])=>m.type==='bowser-fantasy-news-filters'))expect(m.filters.league).toEqual({mode:'mine-league',index:0});expect(localStorage.getItem(NEWS_LAYOUT_KEY)).toBeNull();
});
