// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {afterEach,beforeEach,expect,test,vi} from 'vitest';
import {PlayerProfile} from '../src/PlayerProfile.jsx';
import {Waivers} from '../src/Waivers.jsx';
const reply=data=>({ok:true,json:async()=>data});
const profile={data:{player:{playerId:'review',name:'Review Player',position:'RB',team:'BUF'},gameLogs:[{season_type:'REG',week:1,opponent_team:'KC',fantasy_points:5,carries:4,rushing_yards:12},{season_type:'REG',week:2,opponent_team:'NYJ',fantasy_points:30,carries:12,rushing_yards:72}],history:[{season:2026,week:1,fantasy_points:5,rushing_yards:12},{season:2026,week:2,fantasy_points:30,rushing_yards:72}],seasonStats:[],depthChart:{team:'BUF',groups:[]}},meta:{season:2026,scoring:'ppr'}};
const waivers={rows:[{id:'a',playerId:'a',name:'Review Player',position:'RB',team:'BUF',stats:{fantasy_points:20,snaps:40,rushing_yards:40},activity:{adds:100},rankings:{publisher:{rank:1}},faab:{publisher:{low:10,high:20,unit:'percent'}}}],meta:{season:2026,sources:[{id:'publisher',label:'Publisher',rankCount:1,faabCount:1}],availableWeeks:[2],statsWeeks:[1]}};
beforeEach(()=>{localStorage.clear();global.fetch=vi.fn(async()=>reply(profile));});afterEach(()=>{cleanup();vi.restoreAllMocks();});
const renderProfile=()=>render(<PlayerProfile player={{playerId:'review',name:'Review Player'}} season={2026} scoring='ppr' onClose={()=>{}}/>);
const tableRows=()=>within(screen.getByRole('table')).getAllByRole('row').filter(row=>row.querySelector('td'));
test('profile history-window change preserves selected statistic',async()=>{renderProfile();await screen.findByLabelText('Player trajectory metric');fireEvent.change(screen.getByLabelText('Player trajectory metric'),{target:{value:'rushing_yards'}});expect(screen.getByLabelText('Player trajectory metric')).toHaveValue('rushing_yards');fireEvent.change(screen.getByLabelText('Player trajectory history'),{target:{value:'5'}});await screen.findByLabelText('Player trajectory metric');expect(screen.getByLabelText('Player trajectory metric').value).toBe('rushing_yards');});
test('profile heat-group change clears filters for fields absent from new group',async()=>{renderProfile();await screen.findByLabelText('Player trajectory metric');fireEvent.click(screen.getByRole('tab',{name:'Heat Map'}));const select=screen.getByLabelText('Review Player heat map numeric filter');fireEvent.change(select,{target:{value:'fantasy_points'}});fireEvent.change(screen.getByLabelText('Review Player heat map minimum'),{target:{value:'20'}});expect(tableRows()).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Rushing',exact:true}));expect(screen.getByLabelText('Review Player heat map numeric filter').value).toBe('');expect(tableRows().length).toBe(2);});
test('waiver Numeric fields preset retains statistical columns',async()=>{fetch.mockImplementation(async()=>reply(waivers));render(<Waivers/>);await screen.findByRole('button',{name:'Review Player',exact:true});fireEvent.click(screen.getByRole('button',{name:'Table',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Numeric fields',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Apply settings',exact:true}));expect(!!screen.queryByRole('button',{name:'Sort Fantasy FPTS'})).toBe(true);});
test('waiver column order is constrained to its semantic section',async()=>{fetch.mockImplementation(async()=>reply(waivers));render(<Waivers/>);await screen.findByRole('button',{name:'Review Player',exact:true});fireEvent.click(screen.getByRole('button',{name:'Table',exact:true}));expect(screen.getByRole('button',{name:'Move FPTS earlier',exact:true})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'Move FPTS later',exact:true}));fireEvent.click(screen.getByRole('button',{name:'Apply settings',exact:true}));const names=within(screen.getByRole('table')).getAllByRole('button').map(button=>button.getAttribute('aria-label'));expect(names.indexOf('Sort Fantasy FPTS')).toBeGreaterThan(names.indexOf('Sort Fantasy POS FIN'));});
